<script src="/BO/theme/gebo/lib/tiny_mce/jquery.tinymce.js"></script>
{literal}

<script type="text/javascript">
$(document).ready(function() {
    $('textarea').tinymce({
        // Location of TinyMCE script
        script_url 							: '/BO/theme/gebo/lib/tiny_mce/tiny_mce.js?' + new Date().getTime(),
        // General options
        theme 								: "advanced",
        plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
        // Theme options
        theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
        theme_advanced_buttons3 			: "",
        theme_advanced_toolbar_location 	: "top",
        theme_advanced_toolbar_align 		: "left",
        theme_advanced_statusbar_location 	: "bottom",
        theme_advanced_resizing 			: false,
        height                              : 300,
        content_css                         : "/BO/theme/gebo/css/tinymce_styles.css?" + new Date().getTime(),
        theme_advanced_font_sizes           : "8px,10px,12px,13px,14px,16px,18px,20px",
        font_size_style_values              : "8px,10px,12px,13px,14px,16px,18px,20px",
        init_instance_callback				: function(){

            function resizeWidth() {
                document.getElementById(tinyMCE.activeEditor.id+'_tbl').style.width='100%';
            }
            resizeWidth();
            $(window).resize(function() {
                resizeWidth();
            })
        }
    });
    $(".uni_style").uniform();
    $(".toggle-button").each(function(obj){
        $('#text-toggle-button'+obj).toggleButtons({
            width:75,
            label: {
                enabled: "Yes",
                disabled: "NO"
            },
            onChange: function (data) {
                var user = $('#blackstatus'+obj).val();
                if($("#blackstatus"+obj).is(":checked")){
                    var target_page = "/processao/blackcontributor?status=yes&user_id="+user;
                    $.post(target_page, function(data){ //alert(data);
                        smoke.alert("Contributor Blacklisted");
                    });
                }
                else{
                    var target_page = "/processao/blackcontributor?status=no&user_id="+user;
                    $.post(target_page, function(data){
                        smoke.alert("Contributor Unblacklisted");
                    });
                }
            }
        });
    });
});
////to send the email when editor correct the corrector version and want to disapporve ////////
function getRefuseComment(partid, mode)
{
    var buttonmode = mode;
    if(buttonmode == 'permanent')
    {
        var mailid = 74;
        if (tinymce.getInstanceById('commentsRefusePerm_'+partid))
        {
            tinymce.execCommand('mceRemoveControl', true, 'commentsRefusePerm_'+partid);
            loadEditors('commentsRefusePerm_'+partid);
        }
        else if (!tinymce.getInstanceById('commentsRefusePerm_'+partid))
        {
            loadEditors('commentsRefusePerm_'+partid);
        }
        var target_page = "/processao/getcommentpopup?mailId="+mailid+"&particip_id="+partid; //
        $.post(target_page, function(data){   //alert(data);
            $('#commentsRefusePerm_'+partid).html(data);
            $("#pop_s0art_permdisapprove").show();
            $("#pop_s0art_disapprove").hide();
            $("#mailcontent").css("display", "none");
            $("#mailcontentpermanent").css("display", "block");
        });
    }
    else if(buttonmode == 'temporary')
    {
        var mailid = 73;
        if (tinymce.getInstanceById('commentsRefuse_'+partid))
        {
            tinymce.execCommand('mceRemoveControl', true, 'commentsRefuse_'+partid);
            loadEditors('commentsRefuse_'+partid);
        }
        else if (!tinymce.getInstanceById('commentsRefuse_'+partid))
        {
            loadEditors('commentsRefuse_'+partid);
        }
        var target_page = "/processao/getcommentpopup?mailId="+mailid+"&particip_id="+partid; //
        $.post(target_page, function(data){  // alert(data);
            $('#commentsRefuse_'+partid).html(data);
            $("#pop_s0art_disapprove").show();
            $("#s0art_permdisapprove").hide();
            $("#mailcontent").css("display", "block");
            $("#mailcontentpermanent").css("display", "none");
        });
    }
    $(".alert").show();
}

function sendToFo()
{
    smoke.confirm("Item will be back online",function(e){
        if (e)
        {
            smoke.confirm("Announce by Email",function(e2){
                if (e2)
                {
                    $("#sendtofo").val('yes');
                    $("#anouncebyemail").val('yes');
                    $("#s0correction").submit();
                    return true;
                }
                else
                {
                    $("#sendtofo").val('yes');
                    $("#s0correction").submit();
                    return true;
                }
            });
        }
        else
        {
           $("#sendtofo").val('no');
            $("#s0correction").submit();
            return true;
        }
    });
}

function getRefuseTemp(valtempId)
{
   $("#comment_s1").text('')
      var $b = $('input[type=checkbox]');
      var countselected = $b.filter(':checked').length;
      ////////////////////////////////////
      var selected = new Array();
      $b.filter(':checked').each(function() {
          selected.push($(this).attr('value'));
           $("#hide_total1").val(selected);////for posting the value which are checked
      });
     ////////////////////////////////////
   for(var i=1; i<=countselected; i++)
   {
        var target_page = "/template/getrefusevalidtemp?valtempId="+selected[i-1];
        $.post(target_page, function(data){  //alert(data);
        var obj = $.parseJSON(data);
         $("#comment_s1").append(obj[0].content+'\n\n');
      });
   }
}

function getDensity(artproid, density)
{
    if(density == .5)
    {
        var  densval = density;
    }
    else
    {
        densval = $("#denval").val();
    }
    var target_page = "/proofread/showkeyworddensity?artprocessId="+artproid+"&density="+densval;

    $.post(target_page, function(data){ //alert(data);
        // var obj = $.parseJSON(data);
        $('#density').modal('show');
        $('#density_body').html(data);
    });
}
function showUploadFile(mode)
{
   if(mode == 'close')
      $("#alert").hide();
   else
   {
      $("#alert").show();
      $("#pop-s0comments").hide();
   }
}
///////////for all contributors details list in popup////////////////
function s0CorrectionPlagarism(partId)
{
    $("#loading").modal('show');
    var target_page = "/correction/s0correctionplagarism?participateId="+partId;
    $.post(target_page, function(data){  //alert(data);

       // var data1 = data.trim();
       // if(data1 == 'Please Wait')$maxpercentage
        if(data <= 20)
        {
            $('#loading').modal('hide');
            window.location.href = '/proofread/stage-deliveries?submenuId=ML3-SL11';
        }
        else  if(data > 20)
        {
           window.location.reload();
        }
        else if(data == 'Fail')
        {
            $("#loading").html('process failed');
        }
        else
            $("#loading").html(data);
    });

}
 ////click on plag result should take u to acutaly page////
function plagres(val)   {
    var resFile = $('#resultFile').html() ;
    window.open("https://admin-test.edit-place.co.uk/seotool/plagcontents?s0plagfile="+resFile+"&idx="+val);
}
</script>
<style>
    .bgplain{background-color:#ffffff;}
    .filetitle{font-size:18px;font-weight: bold;}
    .contentwrap{ padding-left:5px; padding-right:10px;
        box-sizing:border-box;
        -moz-box-sizing:border-box;
        webkit-box-sizing:border-box;
        display:block;
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -pre-wrap;
        white-space: -o-pre-wrap;
        word-wrap: normal;
        width:100%; overflow-x:auto;}
    .yellowlink{background-color:yellow; display: inline-block;}
    .bluelink{color:blue;}
</style>
{/literal}
<!-- Div on Load Starts here -->

<!-- Div on Load Ends here -->

<h3 class="heading">Stage 0 Correction<a class="label label-inverse pull-right"  id="return">retour</a></h3>

<table id="grptabledetails" class="table btn-gebo tdleftalign" >
  <tr>
      <td><b>Article : </b>{$articledetails[0].title|escape:'htmlall'}</td>
      <td><b>Ao name : </b>{$articledetails[0].deliveryTitle|escape:'htmlall'}</td>
      <td><b>Article Type : </b>{$articledetails[0].type|stripslashes}</td>
  </tr>
  <tr>
      <td><b>Counting mode : </b>{if $articledetails[0].signtype == 'words'}Words
          {elseif $articledetails[0].signtype == 'chars'}Characters
          {elseif $articledetails[0].signtype == 'sheets'}Sheets {/if}</td>
      <td><b>Min {if $articledetails[0].signtype == 'words'}Words / article
          {elseif $articledetails[0].signtype == 'chars'}Characters / article
          {elseif $articledetails[0].signtype == 'sheets'}Sheets / article {/if}: </b>{$articledetails[0].num_min}</td>
      <td><b>Max {if $articledetails[0].signtype == 'words'}Words / article
            {elseif $articledetails[0].signtype == 'chars'}Characters / article
            {elseif $articledetails[0].signtype == 'sheets'}Sheets / article {/if}: </b>{$articledetails[0].num_max}</td>
  </tr>
  <tr>
    <td><b>Editorial Brief : </b>{if $articledetails[0].filepath neq NULL}
        <a href="/proofread/downloadfile?submenuId={$submenuId}&spec={$articledetails[0].id}" class="label label-warning">Download</a>{else}No file{/if}</td>
    <td></td>
     <td></td>
  </tr>
</table>

<div class="row-fluid">
  <div class="span12">
<form action="/proofread/stage0-correction?submenuId={$submenuId}&articleId={$articledetails[0].id}" method="post" id="s0correction" name="s0correction" enctype="multipart/form-data">
    <table id="s1crtgrid" class="table table-bordered table-striped table_vam">
        <thead>
        <tr>
            <th>Version</th>
            <th>File name</th>
            <th>writer</th>
            <th>step</th>
            <th>Status</th>
            <th>Date</th>
            <th>Article</th>
            <th>Density</th>
            <th>plagiarism internal</th>
            <th>plagiarism external</th>
            <th>{if $articledetails[0].signtype == 'words' || $articledetails[0].signtype == ''}words
                {elseif $articledetails[0].signtype == 'chars'}Characters
                {elseif $articledetails[0].signtype == 'sheets'}sheets {/if}
            </th>
            <th>Black List</th>
        </tr>
        </thead>
        <tbody>
        {foreach from=$versions_details key=versions_key item=versions_item name=versions_loop}
        <tr>
            <td>{$versions_item.version}</td>
            <td>{$versions_item.article_name}</td>
            <td>{if $versions_item.first_name eq ''}{$versions_item.email}{else}{$versions_item.first_name}{/if}</td>
            <td>{if $versions_item.stage eq 's1'}stage 1{else}stage 2{/if}</td>
             <td>{if $versions_item.status eq ''}new {elseif $versions_item.status eq 'process'}revised {else}{$versions_item.status} {/if} </td>
            <td>{$versions_item.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
            <!--<td><a href="/proofread/downloadfile?submenuId={$submenuId}&path={$versions_item.id}">Download</a></td>-->
            <td><a href="/download_article.php?path={$versions_item.id}">Download</a></td>
            <td><a href=""  data-target="#density" data-toggle="modal" onclick="return getDensity('{$versions_item.id}');">Density</a></td>
            <td><a data-target="#plagiarism" data-toggle="modal" href="/proofread/contentplagiarism?artprocessId={$versions_item.id}" class="label label-success">Internal</a></td>
            <td><!--<a data-target="#plagexternalresults" data-toggle="modal" href="/correction/plagdetails?part_id={$versions_item.participate_id}&art_id={$articledetails[0].id}&version={$versions_item.version}"> External</a>({$versions_item.plag_percent})-->
                {if $versions_item.plag_percent neq ''}
                {if $versions_item.plag_percent gt 20}
                <a data-target="#plagexternalresults" data-toggle="modal" href="/correction/plagdetails?part_id={$versions_item.participate_id}&art_id={$articledetails[0].id}&version={$versions_item.version}" class="label label-important" > {$versions_item.plag_percent|string_format:"%d"} %</a>
                {else}
                <a data-target="#plagexternalresults" data-toggle="modal" href="/correction/plagdetails?part_id={$versions_item.participate_id}&art_id={$articledetails[0].id}&version={$versions_item.version}" class="label label-success" > {$versions_item.plag_percent|string_format:"%d"} %</a>
                {/if}
                {else}
                <span class="label label-inverse">N/A</span>
                {/if}
            </td>
            <td>{if $versions_item.article_words_count > $articledetails[0].num_max ||  $versions_item.article_words_count < $articledetails[0].num_min}
                    <span class="label label-important">{$versions_item.article_words_count} </span>
                {else}
                    <span class="label label-success">{$versions_item.article_words_count}</span>
                {/if}
            </td>
            <td><div id="text-toggle-button{$smarty.foreach.versions_loop.index}" name="text-toggle-button{$versions_item.user_id}" class="toggle-button">
                <input name="blackstatus{$versions_item.user_id}" id="blackstatus{$smarty.foreach.versions_loop.index}" type="checkbox" value="{$versions_item.user_id}" {if $versions_item.blackstatus=='yes'} checked="checked" {/if} >
            </div></td>
        </tr>
        {/foreach}
        </tbody>
    </table>
    <div class="alignright" class="span6"><button type="submit" name="s0art_approve" id="s0art_approve" class="btn btn-success">Validate</button>
    {if $refused_count.refused_count < 3}
        <button type="button" id="s0art_disapprove" name="s0art_disapprove" class="btn btn-danger"  onclick="return getRefuseComment('{$partId}', 'temporary');">Refuse</button>
    {/if}
    <button type="button" id="s0art_disapprove_permanent" name="s0art_disapprove_permanent" class="btn btn-danger"  onclick="return getRefuseComment('{$partId}', 'permanent');">Refuse Definite</button>
    <input type="hidden" name="participateId" id="participateId"  />
    </div>
    <div id="alert" class="alert alert-block alert-warning fade in hide" style="height: auto;position:relative;top:50px;">
        <div id="mailcontent">
            <textarea  name="commentsRefuse_{$partId}" id="commentsRefuse_{$partId}"  class="textarea" rows="10"></textarea>

            <button type="submit" class="btn btn-inverse" name="pop_s0art_disapprove" id="pop_s0art_disapprove" >Refuse</button>

            &nbsp;&nbsp;<a onclick="return showUploadFile('close');" class="btn"><i class="splashy-error_small"></i> Close</a>
        </div>
        <div id="mailcontentpermanent">

            <textarea  name="commentsRefusePerm_{$partId}" id="commentsRefusePerm_{$partId}" class="textarea"   rows="10"></textarea>

            <button type="button" class="btn btn-inverse hide" name="pop_s0art_permdisapprove" id="pop_s0art_permdisapprove" data-toggle="modal" data-target="#republish" href="/processao/republishpopup?close=no&stage=0&artId={$smarty.get.articleId}" >Refuse Definite</button>
            &nbsp;&nbsp;<a onclick="return showUploadFile('close');" class="btn"><i class="splashy-error_small"></i> Close</a>
            <input type="hidden" id="sendtofo" name="sendtofo" value="">
            <input type="hidden" id="anouncebyemail" name="anouncebyemail" value="">
            <input type="hidden" id="pop_s0art_permdisapprove_jq" name="pop_s0art_permdisapprove" value="yes">
        </div>
    </div>

</form>
  </div>
</div>

{if $xmlplagfile != ""}
<div id="plagresults" class="alert alert-block alert-info" style="height: auto; position: relative;top:20px;" >

    <h3>Plagiarism Results</h3></div>
    {$xmlplagfile}

{/if}

{if $plagdetails eq 'no'}
<div id="alertplag" class="alert alert-block alert-info" style="height: auto; position: relative;top:20px;" >
<b>No plagiarism check has been made on this file !</b>
<button type="button" class="btn btn-warning" value="" id="s0art_pagiarism" name="s0art_pagiarism" onclick="return s0CorrectionPlagarism('{$smarty.get.participateId}');" >Plagiarism Checker</button>

</div>
{/if}

<!--///show the density details ///-->
<div class="modal4 hide fade" id="density">
    <div class="modal-header">
        <button class="close" onclick="closePopup('density');">&times;</button>
        <h3>Density Details</h3>
    </div>
    <div class="modal-body" id="density_body">
    </div>
    <div class="modal-footer">

    </div>
</div>
<!--///show the plagiarism details ///-->
<div class="modal4 hide fade" id="plagiarism">
    <div class="modal-header">
        <button  class="close" onclick="closePopup('plagiarism');">&times;</button>
        <h3>Plagiarism Details</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">

    </div>
</div>
<!--///show the plagiarism external results details ///-->
<div class="modal4 hide fade" id="plagexternalresults">
    <div class="modal-header">
        <button  class="close" onclick="closePopup('plagexternalresults');">&times;</button>
        <h3>Detail of plagarism</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">

    </div>
</div>
<!--///show loading time for fetching the plagiarism details ///-->
<div class="modal fade hide" id="loading">
       <h3>Plagiarism Results are Loading. Please wait..<img src="/BO/theme/gebo/img/ajax_loader.gif"></h3>
</div>

<!--///when republish the popup comes for edit details and mail for republish article///-->
<div class="modal4 hide fade" id="republish">
    <div class="modal-header">
        <button class="close" onclick="closePopup('republish');">&times;</button>
        <h3>Edit details for republish</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

