<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" type="text/css"/>
		<link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css" type="text/css"/>
		<link rel="stylesheet" href="css/custom_mission.css" type="text/css"/>
		<link rel="stylesheet" href="lib/chosen/chosen.css" type="text/css"/>
		<link rel="stylesheet" href="lib/iCheck/skins/square/blue.css" type="text/css"/>

		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/jquery.validate.min.js"></script>
		<script src="lib/chosen/chosen.jquery.js" type="text/javascript"></script>
		<script src="lib/iCheck/icheck.min.js" type="text/javascript"></script>
	<style>
	#additional{
     background-color: #
	}
	</style>
	<div class="container text-center" id="additional">
			<div class="row">
				<div class="col-ms-10">
					<div class="row">
						 <div class="modal-header" style="border-bottom:0px !important">
			                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			                <h1 class="text-uppercase">Precisions & additional informations</h1>
			             </div>	
					</div>	

					<div class="row">
						<div class="col-md-6 form-group">
						 <p class="form-label" >Please select tempo </p>
							 <textarea class="form-control" rows="4" style="resize:none"></textarea>
						</div>
						<div class="col-md-6 form-group">
						 <textarea class="form-control" rows="4"></textarea>
						</div>
					</div>
				</div>
			</div>	
	</div>