
 {if $missions_details && $smarty.get.m_index}
 <div class="modal-header" style="background-color:#588b58;color:#FFF;">
		   <div class="col-md-11 text-center" >
				<h3 class="text-uppercase">Mission de {$missions_details.product_name} {if $missions_details.producttype_name}/ {$missions_details.producttype_name} {/if}</h3>
				<p class="grey-text text-uppercase">{$missions_details.language_name} {if $missions_details.languagedest_name neq ""}  >  {$missions_details.languagedest_name} {/if}</p>
		  </div>
		  <div align="right" style="margin-bottom: 10px;min-height: 120px;">
		  {if $user_type eq 'superadmin' || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($missions_details.product eq 'translation' || $missions_details.product eq 'redaction') && ($user_type eq 'produser' || $user_type eq 'prodmanager')) || ($missions_details.product eq 'content_strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager')) }
		   <a href="/quote-new/create-quote-mission-popup?quote_id={$smarty.get.quote_id}&mission=edit&mid={$smarty.get.m_index}" data-dismiss="modal" class="btn btn-simple"  data-toggle="modal" data-target="#mission-step" style="color: #fff"><span class="glyphicon glyphicon-pencil"></span></a>
		   <a href="/quote-new/duplicate-quote-mission-popup?quote_id={$smarty.get.quote_id}&mission=duplicate&mid={$smarty.get.m_index}" data-dismiss="modal" class="btn btn-simple"  data-toggle="modal" data-target="#mission-step" style="color: #fff"><span class="glyphicon glyphicon-duplicate"></span></a>
		   <a  class="btn btn-simple delete-mission" style="color: #fff" rel="{$smarty.get.m_index}" data-id='mid' {if $missions_details.linked_product}data-link="{$missions_details.linked_product}"{/if}><span class="glyphicon glyphicon-remove"></span></a>
		   {/if}
			<a class="close btn btn-simple" data-dismiss="modal" aria-label="Close" style="color: #fff"><span class="glyphicon glyphicon-minus"></span></a>
		   </div>
		   
	  </div>
	  <div class="modal-body">
		<!--<span class="label label-info">INFOS</span>
		<span class="label label-success">COMMENTS</span>-->
		
		<h4>Mission Informations</h4>
		
		<div align="center">	
			<p>MISSION TYPE : <strong>{$missions_details.product_name}</strong></p>
			<p>LANGUAGE : <strong>{$missions_details.language_name}</strong></p>
			{if $missions_details.languagedest_name neq ""}
			<p>LANGUAGE DESTINATION: <strong>{$missions_details.languagedest_name}</strong></p>
			{/if}
			{if $missions_details.product_name neq 'Content Strategy'}
					<p>PRODUCT TYPE : <strong>{$missions_details.producttype_name}</strong></p>
					<p>WORDS : <strong>{$missions_details.nb_words}</strong></p>
					<p>VOLUME : <strong>{$missions_details.volume}</strong></p>
					{if $missions_details.oneshot eq 'yes'}
					<p>TEMPO :  <strong>One Shot</strong></p>
					{else}
					<p>TEMPO :  <strong>Recurring</strong></p>
					<p>TEMPO DETAILS :  <strong>{$missions_details.volume_max} {$tempo_array[$missions_details.tempo_type]} {$volume_option_array[$missions_details.delivery_volume_option]} {$missions_details.tempo_length} {$tempo_duration_array[$missions_details.tempo_length_option]}</strong></p>
					{/if}
			{else}
					{if $missions_details.mission_length}
					<p>MISSION DURATION : <strong>{$missions_details.mission_length} {if $missions_details.mission_length_option eq 'days'}JOURS{else}{$missions_details.mission_length_option}{/if}</strong></p>
					{else}
					<p>MISSION DURATION : <strong>Je ne sais pas</strong></p>
					{/if}
			{/if}
		</div>
	  </div>
{/if}
{if $techmission_details && $smarty.get.t_index}
<div class="modal-header" style="background-color:#588b58;color:#FFF;">
		   <div class="col-md-11 text-center" >
				<h3 class="text-uppercase">Mission de  {$techmission_details.product} / {$techmission_details.tech_type}</h3>
				<p class="grey-text text-uppercase">{$techmission_details.product}</p>
		  </div>
		  <div align="right" style="margin-bottom: 10px;min-height: 120px;">
		  {if $user_type eq 'superadmin' || $user_type eq 'techmanager' || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser'}
		   <a href="/quote-new/create-quote-mission-popup?quote_id={$smarty.get.quote_id}&techmission=edit&tid={$smarty.get.t_index}" data-dismiss="modal" class="btn btn-simple"  data-toggle="modal" data-target="#mission-step" style="color: #fff"><span class="glyphicon glyphicon-pencil"></span></a>
		   <a href="/quote-new/duplicate-quote-mission-popup?quote_id={$smarty.get.quote_id}&techmission=duplicate&tid={$smarty.get.t_index}" data-dismiss="modal" class="btn btn-simple"  data-toggle="modal" data-target="#mission-step" style="color: #fff"><span class="glyphicon glyphicon-duplicate"></span></a>
		   <a  class="btn btn-simple delete-mission" style="color: #fff" rel="{$smarty.get.t_index}" data-id='tid'><span class="glyphicon glyphicon-remove"></span></a>
		   {/if}
			<a class="close btn btn-simple" data-dismiss="modal" aria-label="Close" style="color: #fff"><span class="glyphicon glyphicon-minus"></span></a>
		   </div>
		   
	  </div>
	  <div class="modal-body">
		<!--<span class="label label-info">INFOS</span>
		<span class="label label-success">COMMENTS</span>-->
		
		<h4>Mission Informations</h4>
		
		<div align="center">	
			<p>MISSION TYPE : <strong class="text-uppercase">{$techmission_details.product}</strong></p>
			<p>TECH TITLE : <strong>{$techmission_details.tech_type|utf8_encode}</strong></p>
			<p>TECH LANGUAGE : <strong>{$techmission_details.language|utf8_encode}</strong></p>
			<p>VOLUME : <strong>{$techmission_details.volume}</strong></p>
			{if $techmission_details.tech_oneshot eq 'yes'}
			<p>TEMPO :  <strong>One Shot</strong></p>
			{else}
			<p>TEMPO :  <strong>Recurring</strong></p>
			<p>TEMPO DETAILS :  <strong>{$techmission_details.volume_max} {$tempo_array[$techmission_details.tempo_type]} {$volume_option_array[$techmission_details.delivery_volume_option]} {$techmission_details.tempo_length} {$tempo_duration_array[$techmission_details.tempo_length_option]}</strong></p>
			{/if}
			{if $techmission_details.tech_mission_length}
			<p>MISSION DURATION : <strong>{$techmission_details.tech_mission_length} {if $techmission_details.tech_mission_length_option eq 'days'}JOURS{else}{$techmission_details.tech_mission_length_option}{/if}</strong></p>
			{else}
			<p>MISSION DURATION : <strong>Je ne sais pas</strong></p>
			{/if}
		</div>
	  </div>
{/if}
{literal}

<script type="text/javascript">
	$(document).ready(function(){
		var quote_id='{/literal}{$smarty.get.quote_id}{literal}';
		$(".delete-mission").on('click',function(){
			$("#viewmission").modal('hide');
			var m_id=$(this).attr('rel');
			var id=$(this).attr('data-id');
			if($(this).attr('data-link'))
				var pid=$(this).attr('data-link');

			utl='/quote-new/delete-quote-mission?quote_id='+quote_id+'&'+id+'='+m_id;
			swal(
			{
				title: "Are you sure?",
            	    text: "You will not be able to recover this mission!",
            	    type: "warning",
            	    showCancelButton: true,
            	    confirmButtonText: "Yes, delete it!",
            	    cancelButtonText: "No, cancel plx!",
            	    closeOnConfirm: false,
            	    closeOnCancel: false
                },function(isConfirm)
                {
                    if (isConfirm)
					{
						$.ajax
						({
							url:utl,
							success:function(html)
							{
								//alert(html);
								if(id=='tid')
								{
									$("table tr#tmid_"+m_id).remove();
								}
								else
								{
									$("table tr#"+id+'_'+m_id).remove();
									if(pid)
									{
										techid=pid.split(",");
											
										if(techid ){
											for(var i=0; i<techid.length; i++){
											   $("table tr#tmid_"+techid[i]).remove(); //This gets its place
											}
										}
									}
								}
								if($('#price-list tr').length==1)
								{
									location.reload();	
								}
								swal("Deleted!", "Your mission has been deleted.", "success");
								calculateTurnover();
								
							}
						});
					}
					else
					{
						swal("Cancelled", "Your mission not deleted", "error");
					}
				});
			

		});
	});
</script>
{/literal}