<div class="modal-header">
	<button class="close" data-dismiss="modal" >&times;</button>
	<h3>Relance</h3>
</div>
<div class="modal-body">

	<form action="/quote-new/close-reasion-relance/" method="post" id="closequote">
			<input type="hidden" name="quote_id" id="closequoteid" value="{$qid}" />
		
		<div class="form-group">
			<label>Reason<span class="f_req">*</span></label>
			<div class="controls">
				<select name="reason" id="reason" class="validate[required]" data-title="Select Reason">
					{html_options  options=$closedreasons selected=$selected_reasons}
				</select>
			</div>
		</div>
		
	
		<div class="form-group">
			<label>Commentaire concernant la fermeture du devis<span class="f_req">*</span></label>
			<div class="controls">
				<textarea cols="30" id="closetxt" name="closetxt" rows="5" class="form-control validate[required]" >{$closed_comments|escape:'htmlall'}</textarea>
			</div>
		</div>
	
		<div class="form-group">
			<div class="controls">
				<button class="btn btn-primary" type="submit">Valider</button>
				<button  class="btn" data-dismiss="modal" type="reset">Annuler</button>
			</div>
		</div>			
	</form>
</div>
{literal}
<script>
var prefix = "close_";
	<!-- Bootstrap Select Picker -->
	$("#reason").selectpicker();
	$('select').each(function() {
        $(this).next('div.select').attr("id", prefix + this.id).removeClass("validate[required]");
    });	
	$("#closequote").validationEngine({prettySelect : true,usePrefix: prefix});	
	$('textarea').attr('data-prompt-position','topLeft');
</script>
{/literal}
