{literal}
<link href="/BO/theme/lbd/css/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>	
 <!--  Datatable Plugin    -->
 <script src="/BO/theme/lbd/js/bootstrap-table.js" type="text/javascript" charset="utf-8"></script>
 <script src="/BO/theme/lbd/js/jquery.mCustomScrollbar.concat.min.js" type="text/javascript" charset="utf-8"></script>
  
<script src="/BO/theme/lbd/js/jquery.sieve.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript">
$(document).ready(function() {

	 var searchTemplate = "<div class='row form-inline'><label style='float: right;'>Find a Quote: <input type='text' placeholder='Search'></label></div>"
    $("#quote-card").sieve({ searchTemplate: searchTemplate, itemSelector: ".card" });
	
	$('body').on('hidden.bs.modal', '.modal', function () {
	 $(this).removeData('bs.modal');
	 $('.modal-backdrop').remove();
		});
	 
	getQuoteActivities(1);
	$('body').on("click",'.more_button',function() 
	{
		var getId = $(this).attr("id");
		if(getId)
		{
			$("#load_more_"+getId).html('<img src="/BO/theme/gebo/img/ajax_loader.gif" style="padding:10px 0 0 100px;"/>'); 
			getQuoteActivities(getId);
			$("#load_more_"+getId).remove();
		}
		else
		{
			$(".more_tab").html('The End');
		}
		return false;
	});
});

	function getQuoteActivities(page)
	{
		var targetPage="/quote-new/quote-activities-list?page="+page;
		$.get(targetPage,function(data){
		
			$("ul#quote-activities-list").append(data);
			 $('[data-toggle="popover"]').popover();
		});
	}


//scroll bar styling
 (function($){
	        $(window).load(function(){
	            $(".scrollnow").mCustomScrollbar();
	        });
	    })(jQuery);


</script>
{/literal}

<h1>All Quotes 
	{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type 	=='ceouser' || $user_type =='facturation'}
		<a href="/quote-new/create-step1?qaction=new" class="btn btn-primary btn-fill">Create</a>
	{/if}
</h1> 
	
<div id="quote-card" class="row row-horizon">
	<!-- Brief, start --> 
	<div class="col-xs-6 col-sm-4 col-md-3">
		<div class="w">
			<h4><small>First Discussion</small>{$brief_quotes_count} quotes</h4>
		</div>
		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
			{if $quote_list|@count>0}
				{foreach from=$quote_list item=bquote_item name=bquote_loop}
					{if $bquote_item.sales_review eq 'briefing'}
						<!-- card, start -->
						<div class="card" id="quote-{$bquote_item.identifier}">
							<div class="content">
								<div class="card-header">  
									<img src="{$fo_path}profiles/clients/logos/{$bquote_item.client_id}/{$bquote_item.client_id}_global.png?12345" class="brand_l">
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$bquote_item.estimate_sign_percentage}%</span>
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
											<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">
											<li><a href="/quote-new/client-brief?qaction=briefing&quote_id={$bquote_item.identifier}">Editer</a></li>
											<li class="divider"></li>
											{if $user_type=='superadmin'}
												<li>
													<a href="javascript:void(0);"class="delete-quote" data-id="{$bquote_item.identifier}">Delete</a>
												</li>
											{/if}
										</ul>
									</div> 
								</div>
								<a href="/quote-new/client-brief?qaction=briefing&quote_id={$bquote_item.identifier}" class="qt">{$bquote_item.title}</a>
								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										<li>{$bquote_item.created_at|date_format:"%d/%m/%Y"}</li>
										<li>v{$bquote_item.version}</li>
									</ul>
									<div class="owner"><img src="{$fo_path}profiles/bo/{$bquote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$bquote_item.owner}"></div>
								</div>
							</div>                    
						</div>
						<!-- card, stop -->				
					{/if}			
				{/foreach}
			{/if}			
		</div>

	</div>
	<!-- Brief, end -->
	
	<!-- Ongoing, start -->
   <div class="col-xs-6 col-sm-4 col-md-3">
		<div class="w">
			<h4><small>Ongoing</small>{$total_ongoing_turnover|zero_cut_t:2} &euro;</h4>
		</div>

		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
		
			{if $quote_list|@count>0}								
				{foreach from=$quote_list item=quote_item name=oquote_loop}
					{if $quote_item.sales_review eq 'not_done' || $quote_item.sales_review eq 'challenged' || $quote_item.sales_review eq 'to_be_approve'}						<!-- card, start ($user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation')) -->
						<div class="card" id="quote-{$quote_item.identifier}">
							<div class="content">
								 <div class="card-header"> 
									<img src="{$fo_path}profiles/clients/logos/{$quote_item.client_id}/{$quote_item.client_id}_global.png?12345" class="brand_l">
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$quote_item.estimate_sign_percentage}%</span>
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
											<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">
											{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation'}
												{if $quote_item.sales_review eq 'to_be_approve'}
													{if $user_type =='salesuser'}
														{* <!--Pour &ecirc;tre valid&eacute; par le gestionnaire -->*}
														<li>En attente de validation -Head of sales</li>
													{else}
														<li><a href="/quote-new/create-step1?qaction=edit&quote_id={$quote_item.identifier}" tabindex="-1" role="menuitem"><i class="splashy-okay"></i> Accepter</a></li>
													{/if}
												{else}		
													<li>
														<a class="check_quote_edit" href="/quote-new/create-step1?qaction=edit&quote_id={$quote_item.identifier}">Editer</a>
													</li>
													<li>
														<a href="/quote-new/create-step1?qaction=duplicate&quote_id={$quote_item.identifier}" tabindex="-1" role="menuitem"><i class="splashy-document_copy"></i> Dupliquer</a>
													</li>
													{if $quote_item.prod_review eq 'auto_skipped'|| $quote_item.prod_review eq 'skipped' || $quote_item.prod_review eq 'validated'}
														<li>
															<a href="/quote-new/sales-final-validation?qaction=briefing&quote_id={$quote_item.identifier}">Valider</a>
														</li>								
													{/if}
													{if $user_type=='superadmin'}
														<li class="divider"></li>
														<li>
															<a href="javascript:void(0);"class="delete-quote" data-id="{$quote_item.identifier}">Delete</a>
														</li>	
													{/if}	
												{/if}	
											{elseif $user_type == 'seouser' || $user_type =='seomanager'}
												<li>
													<a class="check_quote_edit" href="/quote-new/create-step1?qaction=edit&quote_id={$quote_item.identifier}">Edit</a>
												</li>
												
											{elseif $user_type == 'techuser' || $user_type =='techmanager'}
												<li>
													<a class="check_quote_edit" href="/quote-new/create-step1?qaction=edit&quote_id={$quote_item.identifier}">Edit</a>
												</li>	
											{elseif $user_type == 'produser' || $user_type =='multilingue' || $user_type =='prodsubmanager' || $user_type =='prodmanager'}
												<li>
													<a class="check_quote_edit" href="/quote-new/create-step1?qaction=edit&quote_id={$quote_item.identifier}">Edit</a>
												</li>
											{/if}
										</ul>
									</div>
								</div>
								{if $quote_item.prod_review eq 'auto_skipped'|| $quote_item.prod_review eq 'skipped' || $quote_item.prod_review eq 'validated'}
									<a href="/quote-new/sales-final-validation?qaction=briefing&quote_id={$quote_item.identifier}">
								{else}	
									<a href="/quote-new/client-brief?qaction=briefing&quote_id={$quote_item.identifier}">
								{/if}
								
									<div class="qp">
										{if $quote_item.turnover > 0}
											{$quote_item.turnover|zero_cut_t:2} &{$quote_item.sales_suggested_currency};
										{else}
											-
										{/if}
									</div>		
									<div class="qt">{$quote_item.title}</div>
								</a>
								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										
										{if ($quote_item.prod_review eq 'auto_skipped'|| $quote_item.prod_review eq 'skipped' || $quote_item.prod_review eq 'validated') && ($quote_item.sales_review neq 'validated' && $quote_item.sales_review neq 'closed' && $quote_item.sales_review neq 'briefing')}
											<li>
												{if $smarty.now lt $quote_item.sales_validation_expires}
													<span class="label label-success" data-html="true" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="Quote is ready to be validated by sales <span id='time_{$quote_item.identifier}_{$quote_item.sales_validation_expires}'>
																	 <span id='text_{$quote_item.identifier}_{$quote_item.sales_validation_expires}'></span>
																</span>">Ready
													</span>
												{else}
													<span class="label label-warning" data-html="true" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="Quote is ready to be validated by sales <br> En retard : <span id='time_{$quote_item.identifier}_{$quote_item.sales_validation_expires}' class='enretard'>
																 <span id='text_{$quote_item.identifier}_{$quote_item.sales_validation_expires}'></span>
															</span>">Ready
													</span>
												{/if}
											</li>
										
										{/if}										
										<li>{$quote_item.created_at|date_format:"%d/%m/%Y"}</li>
										<li>v{$quote_item.version}</li>
									</ul>
								   <div class="owner"><img src="{$fo_path}profiles/bo/{$quote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$quote_item.owner}"></div>
								</div>
							</div>                    
						</div>
					<!-- card, stop -->
					{/if}
				{/foreach}	
			{/if}			
		</div>
	</div>
	<!-- Ongoing, end -->
	
	<!-- SENT, start -->
	<div class="col-xs-6 col-sm-4 col-md-3 ">
		<div class="w">
			<h4><small>Sent</small>{$validated_turnover|zero_cut_t:2} &euro;</h4>
		</div>
		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
			{if $quote_list|@count>0}
				{foreach from=$quote_list item=vquote_item name=vquote_loop}
					{if $vquote_item.validated_status eq '1'}
						<!-- card, start -->
						<div class="card" id="quote-{$vquote_item.identifier}">
							<div class="content">
								<div class="card-header">  
									<img src="{$fo_path}profiles/clients/logos/{$vquote_item.client_id}/{$vquote_item.client_id}_global.png?12345" class="brand_l">
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$vquote_item.estimate_sign_percentage}%</span>
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
											<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">
											{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation'}
												<li>
													<a class="newversion" href="/quote-new/create-step1?qaction=edit&quote_id={$vquote_item.identifier}">  Modifier mission</a>
												</li>
												<li>
													<a href="/quote-new/sales-final-validation?qaction=briefing&quote_id={$vquote_item.identifier}"> Modifier la marge</a>
												</li>
												<li class="divider"></li>
												<li>
													<a href="/quote-new/close-quote-view?qid={$vquote_item.identifier}" data-toggle="modal" data-target="#close_quote" class="closequote">Perdu</a>
												</li>
												<li>
													<a data-toggle="modal"  data-target="#sign_quote" href="/quote-new/sign-quote-view?qid={$vquote_item.identifier}"  class="signquote">Signer</a>
												</li>
												{if $user_type=='superadmin'}
													<li>
														<a href="javascript:void(0);"class="delete-quote" data-id="{$vquote_item.identifier}">Delete</a>
													</li>
												{/if}	
												<li>
													<a href="/quote/download-quote-xls?quote_id={$vquote_item.identifier}" >T&eacute;l&eacute;charger xls</a>
												</li>
											{else}	
												<li>
													<a href="/quote/download-quote-xls?quote_id={$vquote_item.identifier}" >T&eacute;l&eacute;charger xls</a>
												</li>
											{/if}	
										</ul>
									</div> 
								</div>
								<a data-toggle="modal"  data-target="#sign_quote" href="/quote-new/sign-quote-view?qid={$vquote_item.identifier}"  class="signquote">
									<div class="qp">
										{if $vquote_item.turnover > 0}
											{$vquote_item.turnover|zero_cut_t:2} &{$vquote_item.sales_suggested_currency};
										{else}
											-
										{/if}
									</div>		
									<div class="qt">{$vquote_item.title}</div>
								</a>
								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										<li>
											<span class="label label-info" data-html="true" data-trigger="hover" data-toggle="popover" data-placement="top" data-content=" Quote will be considered as relance in : <span id='time_{$vquote_item.identifier}_{$vquote_item.sign_expire_timeline}' >
											<span id='text_{$vquote_item.identifier}_{$vquote_item.sign_expire_timeline}'></span>
										</span>">Relance
											</span>
										</li>
										
										<li>{$vquote_item.updated_at|date_format:"%d/%m/%Y"}</li>
										<li>v{$vquote_item.version}</li>
									</ul>
									<div class="owner"><img src="{$fo_path}profiles/bo/{$vquote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$vquote_item.owner}"></div>
								</div>
							</div>                    
						</div>
						<!-- card, stop -->				
					{/if}			
				{/foreach}
			{/if}			
		</div>
	</div>
	<!-- SENT, end -->
	<!-- SIGNED, start -->
   <div class="col-xs-6 col-sm-4 col-md-3">
		<div class="w">
			<h4 class="text-success"><small>Won deal / Signed</small>{$signed_turnover|zero_cut_t:2} &euro;</h4>
		</div>
		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
			{if $quote_list|@count>0}
				{foreach from=$quote_list item=squote_item name=squote_loop}
					{if $squote_item.sales_review eq 'signed'}
						<!-- card, start-->
						<div class="card">
							<div class="content">
								<div class="card-header"> 
									<img src="{$fo_path}profiles/clients/logos/{$squote_item.client_id}/{$squote_item.client_id}_global.png?12345" class="brand_l">
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$squote_item.estimate_sign_percentage}%</span>									
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
												<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">
											{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation'}
												<li>
													{if $squote_item.signed_exist eq '1'}
														<a href="/contractmission/contract-edit?contract_id={$squote_item.signed_contractid}">View contract</a>
													{else}
														<a href="/contractmission/create-contract?quote_id={$squote_item.identifier}">Create the contract</a>												
													{/if}
												</li>
											{/if}
											<li>
												<a href="/quote/download-quote-xls?quote_id={$squote_item.identifier}">T&eacute;l&eacute;charger xls</a>
											</li>
											<li class="divider"></li>
											{if $user_type=='superadmin'}
												<li>
													<a href="javascript:void(0);"class="delete-quote" data-id="{$squote_item.identifier}">Delete</a>
												</li>
											{/if}
										</ul>
									</div>
								</div>
						
								<a href="/quote-new/sales-final-validation?qaction=briefing&quote_id={$squote_item.identifier}">									
									<div class="qp">
										{if $squote_item.turnover > 0}
											{$squote_item.turnover|zero_cut_t:2} &{$squote_item.sales_suggested_currency};
										{/if}
									</div>		
									<div class="qt">{$squote_item.title}</div>
								</a>

								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										<li>
											{if $squote_item.signed_exist eq '1'}
												<span class="label label-info" data-html="true" data-trigger="hover"  data-toggle="popover" data-placement="top" data-content="{$squote_item.signed_contract}">Contract created</span>
											{else}	
												<span class="label label-danger" data-html="true" data-trigger="hover" data-toggle="popover" data-placement="top" data-content="Pending contract creation">Contract to create</span>
											{/if}
										</li>
										<li>{$squote_item.signed_at|date_format:"%d/%m/%Y"}</li><li>v{$squote_item.version}</li>
									</ul>
								  <div class="owner"><img src="{$fo_path}profiles/bo/{$squote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$squote_item.owner}"></div>
								</div>
							</div>                    
						</div>
					<!-- card, stop -->	
					
					{/if}
				{/foreach}	
			{/if}
		</div> 
    </div>
 <!-- SIGNED, end -->  
<!-- Relaunched, start -->
   <div class="col-xs-6 col-sm-4 col-md-3">
		<div class="w">
			<h4><small>Pending feedback</small>{$relancer_turnover|zero_cut_t:2} &euro;</h4>
		</div>
		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
			{if $quote_list|@count>0}
				{foreach from=$quote_list item=rquote_item name=rquote_loop}
					{if $rquote_item.relancer_status eq '1'}
						<!-- card, start-->
						<div class="card">
							<div class="content">
								<div class="card-header"> 
									<img src="{$fo_path}profiles/clients/logos/{$rquote_item.client_id}/{$rquote_item.client_id}_global.png?12345" class="brand_l">	
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$rquote_item.estimate_sign_percentage}%</span>										
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
												<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">											
											{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation'}
												<li>
													<a href="/quote-new/relance-quote-popup?qid={$rquote_item.identifier}"data-toggle="modal" data-target="#programmer-relance">Schedule reminder</a>
												</li>
												<li>
													<a href="/quote-new/close-relance-view?qid={$rquote_item.identifier}" data-content="{$rquote_item.closed_comments}" data-toggle="modal"  data-target="#close_quote" class="closequote" >Select reason</a>
												</li>
												<li>
													<a class="newversion" href="/quote-new/create-step1?qaction=edit&quote_id={$rquote_item.identifier}">Reactivate Quote</a>
												</li>
												<li>
													<a href="/quote-new/edit-quote-final-step?quote_id={$rquote_item.identifier}"  data-toggle="modal" data-target="#edit_quote_files"> Ajouter des infos</a>
												</li>
												<li class="divider"></li>
												<li>
													<a href="/quote-new/close-relance-view?qid={$rquote_item.identifier}&closed_type=perdu" data-toggle="modal" data-target="#close_quote" class="closequote"> Perdu</a>
												</li>
											{/if}
											
											<li>
												<a href="/quote/download-quote-xls?quote_id={$rquote_item.identifier}">T&eacute;l&eacute;charger xls</a>
											</li>											
											{if $user_type=='superadmin'}
												<li>
													<a href="javascript:void(0);"class="delete-quote" data-id="{$rquote_item.identifier}">Delete</a>
												</li>
											{/if}
										</ul>
									</div>
								</div>
						
								<a class="newversion" href="/quote-new/create-step1?qaction=edit&quote_id={$rquote_item.identifier}">								
									<div class="qp">
										{if $rquote_item.turnover > 0}
											{$rquote_item.turnover|zero_cut_t:2} &{$rquote_item.sales_suggested_currency};
										{/if}
									</div>		
									<div class="qt">{$rquote_item.title}</div>
								</a>

								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										<li>
											{if $rquote_item.boot_customer  && $rquote_item.relancer_commet!="" }
											<span class="hidden">{$rquote_item.boot_customer|date_format:"%Y/%m/%d"}</span>
											<span class="label label-info" data-content="{$rquote_item.boot_customer|date_format:'%d/%m/%Y'} - {if $rquote_item.closed_reason }{$closedreasons[$rquote_item.closed_reason]} - {/if}{$rquote_item.relancer_commet}"  data-html="true" data-trigger="hover" data-placement="top" data-toggle="popover">
												{$rquote_item.boot_customer|date_format:"%d/%m/%Y"} relance
											</span>
										 {else}
											<span class="label label-danger"data-html="true" data-trigger="hover" data-placement="top" data-content="Please, contact the client again" data-toggle="popover">To update</span>
										 {/if}
											
										</li>
										<li>{$rquote_item.updated_at|date_format:"%d/%m/%Y"}</li><li>v{$rquote_item.version}</li>
									</ul>
								  <div class="owner"><img src="{$fo_path}profiles/bo/{$rquote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$rquote_item.owner}"></div>
								</div>
							</div>                    
						</div>
					<!-- card, stop -->	
					
					{/if}
				{/foreach}	
			{/if}
		</div> 
    </div>
 <!-- Relaunched, end -->

<!-- LOST, start -->
   <div class="col-xs-6 col-sm-4 col-md-3">
		<div class="w">
			<h4><small>Lost</small>{$closed_turnover|zero_cut_t:2} &euro;</h4>
		</div>
		<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
			{if $quote_list|@count>0}
				{foreach from=$quote_list item=cquote_item name=cquote_loop}
					{if $cquote_item.closed_status eq '1'}
						<!-- card, start-->
						<div class="card">
							<div class="content">
								<div class="card-header"> 
									<img src="{$fo_path}profiles/clients/logos/{$cquote_item.client_id}/{$cquote_item.client_id}_global.png?12345" class="brand_l">	
									<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$cquote_item.estimate_sign_percentage}%</span>										
									<div class="dropdown clearfix">
										<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
												<b class="caret"></b>
										</a>
										<ul class="dropdown-menu dropdown-menu-right">											
											{if $user_type == 'superadmin' || $user_type =='salesuser' || $user_type =='salesmanager' || $user_type =='ceouser' || $user_type =='facturation'}
												<li>
													<a href="/quote-new/relance-quote-popup?qid={$cquote_item.identifier}"data-toggle="modal" data-target="#programmer-relance">Schedule reminder</a>
												</li>
												<li>
													<a href="/quote-new/close-relance-view?qid={$cquote_item.identifier}" data-content="{$cquote_item.closed_comments}" data-toggle="modal"  data-target="#close_quote" class="closequote" >Select reason</a>
												</li>
												<li>
													<a class="newversion" href="/quote-new/create-step1?qaction=edit&quote_id={$cquote_item.identifier}">Reactivate Quote</a>
												</li>
												<li>
													<a href="/quote-new/edit-quote-final-step?quote_id={$cquote_item.identifier}"  data-toggle="modal" data-target="#edit_quote_files"> Ajouter des infos</a>
												</li>
												<li class="divider"></li>												
											{/if}
											
											<li>
												<a href="/quote/download-quote-xls?quote_id={$cquote_item.identifier}">T&eacute;l&eacute;charger xls</a>
											</li>											
											{if $user_type=='superadmin'}
												<li>
													<a href="javascript:void(0);"class="delete-quote" data-id="{$cquote_item.identifier}">Delete</a>
												</li>
											{/if}
										</ul>
									</div>
								</div>
						
								<a class="newversion" href="/quote-new/create-step1?qaction=edit&quote_id={$cquote_item.identifier}">
									<div class="qp">
										{if $cquote_item.turnover > 0}
											{$cquote_item.turnover|zero_cut_t:2} &{$cquote_item.sales_suggested_currency};
										{/if}
									</div>		
									<div class="qt">{$cquote_item.title}</div>
								</a>

								<div class="qf clearfix">
									<ul class="list-inline text-muted">
										{if $cquote_item.closed_comments}
										<li>
											<span class="label label-info" data-content="{if $cquote_item.boot_customer}{$cquote_item.boot_customer|date_format:'%d/%m/%Y'} - {/if} {$closedreasons[$cquote_item.closed_reason]} - {$cquote_item.closed_comments}"  data-html="true" data-trigger="hover" data-placement="top" data-toggle="popover">
												{$closedreasons[$cquote_item.closed_reason]}
											</span>
										</li>
										{/if}
										<li>{$cquote_item.updated_at|date_format:"%d/%m/%Y"}</li><li>v{$cquote_item.version}</li>
									</ul>
								  <div class="owner"><img src="{$fo_path}profiles/bo/{$cquote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$cquote_item.owner}"></div>
								</div>
							</div>                    
						</div>
					<!-- card, stop -->	
					
					{/if}
				{/foreach}	
			{/if}
		</div> 
    </div>
 <!-- CLOSED, end --> 
	 {if $user_type=='superadmin'}
	 <!-- DELETE, start --> 
		<div class="col-xs-6 col-sm-4 col-md-3">
			<div class="w">
				<h4><small>Deleted</small>{$deleted_turnover|zero_cut_t:2} &euro;</h4>
			</div>
			<div class="scrollnow mCustomScrollbar" data-mcs-theme="minimal-dark">
				{if $quote_list|@count>0}
					{foreach from=$quote_list item=dquote_item name=dquote_loop}
						{if $dquote_item.sales_review eq 'deleted'}
							<!-- card, start -->
							<div class="card" id="quote-{$dquote_item.identifier}">
								<div class="content">
									<div class="card-header">  
										<img src="{$fo_path}profiles/clients/logos/{$dquote_item.client_id}/{$dquote_item.client_id}_global.png?12345" class="brand_l">
										<span class="ps" data-toggle="tooltip" data-placement="bottom" title="Estimation of signature">{$dquote_item.estimate_sign_percentage}%</span>
										<div class="dropdown clearfix">
											<a href="#" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
												<b class="caret"></b>
											</a>
											{if $user_type=='superadmin'}
												<ul class="dropdown-menu dropdown-menu-right">
												
													<li>
														<a href="javascript:void(0);"class="delete-quote-permenent" data-id="{$dquote_item.identifier}">Delete</a>
													</li>											
												</ul>
											{/if}	
										</div> 
									</div>
									<a href="javascript:void(0);"class="delete-quote-permenent" data-id="{$dquote_item.identifier}">									
										<div class="qp">
											{if $dquote_item.turnover > 0}
												{$dquote_item.turnover|zero_cut_t:2} &{$dquote_item.sales_suggested_currency};
											{/if}
										</div>		
										<div class="qt">{$dquote_item.title}</div>
									</a>
									<div class="qf clearfix">
										<ul class="list-inline text-muted">
											<li>{$dquote_item.deleted_at|date_format:"%d/%m/%Y"}</li>
											<li>v{$dquote_item.version}</li>
										</ul>
										<div class="owner"><img src="{$fo_path}profiles/bo/{$dquote_item.quote_by}/logo.jpg?123"  data-toggle="tooltip" data-placement="left" title="{$dquote_item.owner}"></div>
									</div>
								</div>                    
							</div>
							<!-- card, stop -->				
						{/if}			
					{/foreach}
				{/if}			
			</div>

		</div>
		<!-- DELETE, end -->
	{/if}	
</div>
<!--Activities , Start-->

<div id="activities" style="display:none">
	<div class="headerActivities">
		<div class="pictoActivities">
			<i class="material-icons" >notifications_active</i>
		</div>
		<div>
			Activities
		</div>
		<div id="clearActivities" class="pull-right">
			<i class="material-icons">clear</i>
		</div>
	</div>

	<div class="containerActivities">			
		<ul class="list-group activity-list" id="quote-activities-list">
		</ul>				
	</div>	
</div>
<!--Activities , end-->



<!--Estimated sign details -->
<div class="modal hide fade" id="estimate_sign" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
		<h3>Estimation</h3>
    </div>
    <div class="modal-body">
		
    </div>
    <div class="modal-footer">
    </div>
</div>



{literal}
<link rel="stylesheet" href="/BO/theme/lbd/lib/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/lbd/lib/validation-engine/jquery.validationEngine-en.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/lbd/lib/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<script language="JavaScript" type="text/javascript" src="/BO/theme/lbd/js/countdown.js"></script>

<script type="text/javascript">	
$(document).ready(function() {
	
		function upTime(countTo,identy,statetime) {
			var message = "";
			currnttime=(new Date).getTime();
			  difference = (currnttime-countTo);

			  days=Math.floor(difference/(60*60*1000*24)*1);
			  hours=Math.floor((difference%(60*60*1000*24))/(60*60*1000)*1);
			  mins=Math.floor(((difference%(60*60*1000*24))%(60*60*1000))/(60*1000)*1);
			  secs=Math.floor((((difference%(60*60*1000*24))%(60*60*1000))%(60*1000))/1000*1);
				if(days >0 )message += days + " jours "  +"  ";
				if(hours >0 )message += hours + " h ";
				if(mins >0 )message += mins + " min ";
				message += secs + " sec ";
				alert(message);
              $("#text_"+identy+"_"+statetime).html(message);		
              		 
			 
}
	////////////to show the timer of tech time line///////
      var cur_date={/literal}{$smarty.now}{literal};
      var js_date=(new Date().getTime())/ 1000;
      var diff_date=Math.floor(js_date-cur_date);
      
     //////////show timer//////////
	$("[id^=time_]").each(function(i) {
		var article=$(this).attr('id').split("_");
		var ts=article[2];
		if($(this).attr('class') !== undefined && $(this).attr('class')=='enretard'){
		
			$("#text_"+article[1]+"_"+article[2]).countup({
				timestamp   : ts,
				diff_date  : diff_date,
				callback    : function(days, hours, minutes, seconds){
					var message = "";
					if(days >0 )message += days + " jours"  +"  ";
					if(hours >0 )message += hours + " h ";
					if(minutes >0 )message += minutes + " min ";
					message += seconds+" sec ";
					$("#text_"+article[1]+"_"+article[2]).html(message);
					if(days==0 && hours==0 && minutes==0 && seconds==0)
					{
						//window.location.reload();
					}
				}	
			});			  
        
		}else{
		$("#time_"+article[1]+"_"+article[2]).countdown({
			timestamp   : ts,
            diff_date  : diff_date,
			callback    : function(days, hours, minutes, seconds){
				var message = "";
				if(days >0 )message += days + " jours"+"  ";
				if(hours >0 )message += hours + ":";
				if(minutes >0 )message += minutes + ":";
				message += seconds;
				$("#text_"+article[1]+"_"+article[2]).html(message);
				if(days==0 && hours==0 && minutes==0 && seconds==0)
				{
					//window.location.reload();
				}
			}
		});
		}
	});
	//$(".reason").chosen({ allow_single_deselect: false,disable_search: true});
	
		
/* Pop click funciton*/
		$('.pop_clickover').popover({trigger:'click'});

	var flash_message="{/literal}{$actionmessages[0]}{literal}";	
	var flash_message1="{/literal}{$actionmessages[1]}{literal}";
	
	if(flash_message=='Devis cr&eacute;e avec succ&egrave;s' && flash_message1!='Onlysales')
	{	
		$("#quote_created").modal('show');
		$("#quote_created").removeClass( "hide" ).addClass("in");
	}
	
	$('.oselect_rows').click(function () {
		var tableid = $(this).data('tableid');
		//alert(tableid)
		$('#'+tableid).find('input[name="oquote_select[]"]').attr('checked', this.checked);
	});
	$('.oselect_rows').click(function () {
		var tableid = $(this).data('tableid');		
		$('#'+tableid).find('input[name="oquote_select[]"]').attr('checked', this.checked);
	});
	$('.cselect_rows').click(function () {
		var tableid = $(this).data('tableid');		
		$('#'+tableid).find('input[name="cquote_select[]"]').attr('checked', this.checked);
	});
	$('.vselect_rows').click(function () {
		var tableid = $(this).data('tableid');		
		$('#'+tableid).find('input[name="vquote_select[]"]').attr('checked', this.checked);
	});
	$('.sselect_rows').click(function () {
		var tableid = $(this).data('tableid');		
		$('#'+tableid).find('input[name="squote_select[]"]').attr('checked', this.checked);
	});
	
	$( ".newversion" ).click(function( event ) {
				event.preventDefault();
				var href=$(this).attr("href");
				//var msg = "Souhaitez-vous cr&eacute;er une nouvelle version de devis?";
				
			swal(
				{
					title: "nouvelle version de devis",
            	    text: "Souhaitez-vous créer une nouvelle version de devis?",
            	    type: "success",
            	    showCancelButton: true,
            	    confirmButtonText: "Yes",
            	    cancelButtonText: "No",
            	    closeOnConfirm: false,
            	    closeOnCancel: true
                },function(isConfirm)
                {
                	if(isConfirm)
                	{
						window.location.href =href;
					}
				}
				);
	});
	
	
	
	$(".bootcustomer").click(function(){
		var quote_id = $(this).attr('rel');
		var thisvar = $(this);
		thisvar.html('<img alt="" src="/BO/theme/gebo/img/ajax_loader.gif">');
		$.post('/quote/boot-customer',{"qid":quote_id},function(data){
			thisvar.closest("td").html(data);
		})
	})
	
	$(".check_quote_edit").click(function(e){
		e.preventDefault();
		var quote_id = $(this).closest("tr").find("input").val();
		var href=$(this).attr("href");

		 $.ajax({
              url: "/quote/check-edit-quote",
              data: {"qid":quote_id},
              type: "POST",
              async: false,
              success: function(data) {
				
				if($.trim(data))
				{
					swal(
					{
						title: "Edit the Quote",
	            	    text: "Already another Quote is Opened and not submitted still want to proceed?",
	            	    type: "success",
	            	    showCancelButton: true,
	            	    confirmButtonText: "Yes",
	            	    cancelButtonText: "No",
	            	    closeOnConfirm: false,
	            	    closeOnCancel: true
               		 	},function(isConfirm)
                		{
		                	if(isConfirm)
		                	{
								window.location.href =href;
							}
						}
					);
					
				}
				else
				window.location.href =href;
              }
        });
			
	});
	
	/* To delete Quote */
	$(".delete-quote").click(function(e){
		e.preventDefault();
		var quote_id=$(this).attr("data-id");
		
		var msg = "Are you sure want to delete this Quote?";
		swal(
					{
						title: "",
	            	    text: msg,
	            	    type: "warning",
	            	    showCancelButton: true,
	            	    confirmButtonText: "Yes",
	            	    cancelButtonText: "No",
	            	    closeOnConfirm: false,
	            	    closeOnCancel: true
               		 	},function(isConfirm)
                		{
		                	if(isConfirm)
		                	{
								if(quote_id)
								{
									var target_page='/quote-new/delete-quote?quote_id='+quote_id;
									$.post(target_page,function(){
										$("#quote-"+quote_id).remove();
										swal({
											title:"Deleted!",
											text: "Quote has been deleted.",
											type: "success" 
										},function () {
				                        location.reload();
				                        });

									});
									 
								}
								
							}
						}
					);
		
	})
	
	//$('a[rel=popover]').popover({ html: true, trigger: 'hover',placement:'right'});
	
	$(".changewarning").click(function(){
		$(".changewarning").closest("tr").removeClass("warning");
		$(this).closest("tr").addClass("warning");
	});
	
	
	$(".delete-quote-permenent").click(function(e){
		
		e.preventDefault();
		//var href=$(this).attr("href");
		var quote_id=$(this).attr("data-id");
		var msg = "Souhaitez-vous vraiment supprimer cet Quote?";
		
		swal(
				{
				title: "",
				text: msg,
				type: "warning",
				showCancelButton: true,
				confirmButtonText: "Yes",
				cancelButtonText: "No",
				closeOnConfirm: false,
				closeOnCancel: true
				},function(isConfirm)
				{
					if(isConfirm)
		            {
						if(quote_id)
						{
							var target_page='/quote-new/delete-quote-permenent?quote_id='+quote_id;
							$.post(target_page,function(){
								$("#quote-"+quote_id).remove();
								swal("Deleted!", "Quote has been deleted from DB.", "success");
							});
							 
						}
					}	
				}
			);
	})
	
});	

function changestatus(current,quote_id)
{
	$.post('/quote/change-reason',{'quote_id':quote_id,'reason':current.value},function(data){$.sticky('Updated reason successfully', {autoclose : 2000, position: "top-center", type: 'st-success'});});
}

/* //edit QUote in validated quotes
function fneditQuote(quote_id,version)
{
	smoke.confirm("Vous souhaitez &eacute;diter le devis",function(e){
					if (e)
					{						
						window.location='/quote/sales-final-validation?quote_id='+quote_id+'&submenuId=ML13-SL2';
					}
					else
					{
						var msg = "Souhaitez-vous cr&eacute;er une nouvelle version de devis?";
						smoke.confirm(msg,function(e){
							if (e){
									window.location='/quote/create-quote-step1?qaction=edit&quote_id='+quote_id+'&submenuId=ML13-SL2';
								}					
						},{"ok":"Oui","cancel":"Non"});						
						//return false;
					}
				}, {ok:"En phase finale", cancel:"En &eacute;tape 1"});


} */

	/* Pop up to Close Quote */

$(document).on("click",".closequote",function(){
/* 		$("#closequote").validationEngine();
		$('textarea').attr('data-prompt-position','topLeft');
		$('textarea').data('promptPosition','topLeft');
		
		$('#closetxt').val('');
		var quote_id = $(this).closest("tr").find("input").val();
		$("#closequoteid").val(quote_id); */
		$("#close_quote").modal('show');
		$("#close_quote").removeClass( "hide" ).addClass("in");
	});
	
	$(document).on("click",".relance-qu",function(){
/* 		$("#closequote").validationEngine();
		$('textarea').attr('data-prompt-position','topLeft');
		$('textarea').data('promptPosition','topLeft');
		
		$('#closetxt').val('');
		var quote_id = $(this).closest("tr").find("input").val();
		$("#closequoteid").val(quote_id); */
		$("#programmer-relance").modal('show');
		$("#programmer-relance").removeClass( "hide" ).addClass("in");
	})
	/*popover click hide*/
	$('body').on('click', function (e) 
	{
		$('a[data-toggle=popover]').each(function () {
        // hide any open popovers when the anywhere else in the body is clicked
        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
            $(this).popover('hide');
        }
    	});
	 });
	/* Pop up to Sign Quote */
	
	$(document).on("click",".signquote",function(){
		/* $("#signquote").validationEngine();
		$('textarea').attr('data-prompt-position','topLeft');
		$('textarea').data('promptPosition','topLeft');
		
		$('#signtxt').val('');
		var quote_id = $(this).closest("tr").find("input").val();
		$("#signquoteid").val(quote_id); */
		$("#sign_quote").modal('show');
		$("#sign_quote").removeClass( "hide" ).addClass("in");
	});
	
</script>
{/literal}