{literal}
<script type="text/javascript" src="/BO/theme/lbd/js/countdown.js"></script>

<link rel="stylesheet" href="/BO/theme/lbd/lib/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/lbd/lib/validation-engine/jquery.validationEngine-en.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/lbd/lib/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/lbd/js/jquery.MultiFileQuote.js" type="text/javascript" charset="utf-8"></script>


<script src="/BO/theme/lbd/js/moment.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/lbd/js/bootstrap-datetimepicker.js" type="text/javascript" charset="utf-8"></script>


<style type="text/css">
.modal-backdrop{position: relative;}
</style>
<script language="javascript">
function roundnum(number)
{
	return Math.round(number*100)/100;
}
//5 decimal points
function round5num(number)
{
	return Math.round(number*100000)/100000;
}
//user turnover for a mission
function fnCalUserTurnover(mission_id,offer_price,number_writers)
{
	offer_price=offer_price.replace(",",".");
	var userOffer=offer_price*number_writers;
	
	var FreeMissionuserval= $("#free_mission_"+mission_id+":checked").val();
    if(FreeMissionuserval=='yes')
    {
	$("#user_ca_"+mission_id).val(0);	
	}else{
	$("#user_ca_"+mission_id).val(userOffer);	
	}	
	
	
	fncalculateAutoTotal(); //calculate cost automatically
}


//package selection for a mission
function updatepackage(mission_id,package_name,index)
{
	var margin_percentage=0;
	var quote_id='{/literal}{$quotes.quote_id}{literal}';
	if(package_name=='lead')
			margin_percentage=60;
	else if(package_name=='link')
			margin_percentage=30;
	else if(package_name=='team')
			margin_percentage=50;	
			
	if(package_name=='team')
	{
		$("#other_details_team_"+mission_id).show();
		$("#other_details_user_"+mission_id).hide();
		$("#ca_thead_user_"+mission_id).hide();		
		$("#turnover_"+mission_id).css("text-decoration","none");
		$("#margin_percentage_"+mission_id).prop("readonly",false);	
	}
	else if(package_name=='user')
	{
		$("#other_details_team_"+mission_id).hide();
		$("#other_details_user_"+mission_id).show();
		$("#ca_thead_user_"+mission_id).show();
		$("#turnover_"+mission_id).css("text-decoration","line-through");
		$("#margin_percentage_"+mission_id).prop("readonly",true);
	}
	else
	{
		$("#other_details_team_"+mission_id).hide();
		$("#other_details_user_"+mission_id).hide();
		$("#ca_thead_user_"+mission_id).hide();
		$("#turnover_"+mission_id).css("text-decoration","none");
		$("#margin_percentage_"+mission_id).prop("readonly",false);	
	}
	
	
	margin_percentage=roundnum(margin_percentage);
	
	$("#margin_percentage_"+mission_id).val(margin_percentage);

	if(package_name=='team')
	{
		var mission_turnover=parseFloat($("#turnover_"+mission_id).val().replace(",","."));
		var team_fee=parseFloat($("#team_fee_"+mission_id).val().replace(",","."));
		var team_ca=roundnum(mission_turnover+team_fee);		
		$("#team_ca_"+mission_id).val(team_ca);
		
		fncalculateAutoTotal();//calculate cost automatically
	}
	var mindex=parseInt(index)+1;
	if(mission_id!='t'+mindex)
	{
		/*staffing calculations*/
		var staff_target='/quote-new/get-staff-time-config?quote_id='+quote_id+'&index='+index+'&package_name='+package_name+"&margin_percentage="+margin_percentage;
		$.get(staff_target,function(data){
			//alert(mindex);
			if($.trim(data))
			{
				$("#missionlengthval_"+mindex).text(data);
				fnCalculateMissionTime();
			}
		});

	}
	
	fncalculateAutoTotal();//calculate cost automatically
	
	
	

}

//Apply global package to a quote
function quoteupdatepackage(package_name)
{
	$("[id^=package_]" ).each(function(z) {
		var divDetails=$(this).attr('id');
		divDetails=divDetails.split("_");
		var mission_id=divDetails[1];
		$("#package_"+mission_id).val(package_name);
		
		//Updating all mission packages
		updatepackage(mission_id,package_name,z);		
		
	});
}

$(document).ready(function(){

	var quote_id='{/literal}{$quotes.quote_id}{literal}';
	$('body').on('hidden.bs.modal', '.modal', function () {
	 $(this).removeData('bs.modal');
	 $('.modal-backdrop').remove();
		});

	
	var prefix = "final_";	
	
	//select picker and validation for selector
	$("#quote_package").selectpicker();
	$("[id^=package_]").selectpicker();
	
	$('select').each(function() {
        $(this).next('div.select').attr("id", prefix + this.id).removeClass("validate[required]");
    });		
	$("#save_final_validation").validationEngine('attach',{prettySelect : true,autoHidePrompt: true,usePrefix: prefix});
	$("#changeFormValue").validationEngine('attach',{prettySelect : true,autoHidePrompt: true,usePrefix: prefix});
	
	
	
	$("#prod_validation").validationEngine();
	$("#tech_validation").validationEngine();
	$("#seo_validation").validationEngine();

	$("#popupshow").on('click',function(){
		if($("#save_final_validation").validationEngine('validate'))
		{
			target=$(this).data('target');
				$(target).modal('show');
				$(target).removeClass( "hide" ).addClass("in");
				$('#prod_review').find('.review_validate').removeClass('hidden');
				
		}
	});

	$('.icheck').checkbox();
	
	/*form submit by asking team*/

	$(".send_team").on("change",function(){

		if($('.send_team:checked').length==0)
		{
       		$("#saveFinal").removeAttr('disabled');
       		$(".review_validate").removeClass('hidden');
    		$("#popupshow").addClass('hidden');
    	}
    	else
    	{
    		$("#saveFinal").attr('disabled','disable');
    		$("#popupshow").removeClass('hidden');
    		$(".review_validate").addClass('hidden');

    	}
			
	});
	$(".review_validate").on("click",function(){

		
		if($(this).hasClass('validate'))
		{
			$('#save_final_validation').attr('action','/quote-new/save-final-validation?validate=save&quote_id='+quote_id);
			$("#save_final_validation").submit();
		}
	});

	$('#saveFinal').on('click',function(){
		if($("#save_final_validation").validationEngine('validate'))
		{
			$("#save_final_validation").submit();
		}
	});
	
	//$("#estimate_sign_percentage").selectpicker();
	
	//file upload
	$("#sale_documents").MultiFile();
	
	fncalculateAutoTotal();//calculate cost automatically

	/*popover*/
	$(".pop_over").popover({trigger: 'hover'});
	
	//exclude seo missions from the final margin
	$("document").on('click',"[id^=smission_close_]", function() {
		var DivId = $(this).attr('id');			
		var parentDiv=$(this).parents("div:eq(3)").attr('id');
		//alert(parentDiv);
		var mission_identifier=$(this).attr('rel');		
		var	quote_id=$("#quote_id").val();		
		
		if(!mission_identifier)
		{
			//if($("[id^=seo_mission_]").size()>1)					
				$("#"+parentDiv).remove();
				fncalculateAutoTotal();//calculate cost automatically
		}	
		else
		{	
			smoke.confirm("Souhaitez-vous vraiment supprimer cette mission du devis?",function(e){
				if (e)
				{
					$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Suppression de cette mission devis... </center>');
					ajaxSEOMissionUpdate(quote_id,mission_identifier,parentDiv,'');
					fncalculateAutoTotal();//calculate cost automatically
				}
				else
				{
					return false;
				}
			});				
		}	
			
	});	
	
	//exclude Tech missions from the final margin
	
	$("document").on('click',"[id^=tmission_close_]", function() {
		var DivId = $(this).attr('id');			
		var parentDiv=$(this).parents("div:eq(3)").attr('id');
		//alert(parentDiv);
		var mission_identifier=$(this).attr('rel');		
		var	quote_id=$("#quote_id").val();				
		if(!mission_identifier)
		{
			//if($("[id^=seo_mission_]").size()>1)					
				$("#"+parentDiv).remove();
				fncalculateAutoTotal();//calculate cost automatically
		}	
		else
		{	
			smoke.confirm("Souhaitez-vous vraiment supprimer cette mission tech du devis?",function(e){
				if (e)
				{
					$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Suppression de cette mission tech devis... </center>');
					ajaxTECHMissionUpdate(quote_id,mission_identifier,parentDiv,'');
					fncalculateAutoTotal();//calculate cost automatically
				}
				else
				{
					return false;
				}
			});				
		}	
			
	});
	
	$("#delivery_time_calc_modal").on('hidden', function() {
		//alert('test');
		$(this).removeData("modal");
		$("#delivery_time_calc_modal .modal-body").html('');
	});
	
	////////////to show the timer of tech time line///////
      /*var cur_date={/literal}{$smarty.now}{literal};*/
      var cur_date='';
      var js_date=(new Date().getTime())/ 1000;
      var diff_date=Math.floor(js_date-cur_date);
     //////////show timer//////////
	$("[id^=time_]").each(function(i) {
		var article=$(this).attr('id').split("_");
		var ts=article[2];
		
		if($(this).attr('class') !== undefined && $(this).attr('class')=='enretard alert alert-warning pull-right quote-timer'){
		
			$("#text_"+article[1]+"_"+article[2]).countup({
				timestamp   : ts,
				diff_date  : diff_date,
				callback    : function(days, hours, minutes, seconds){
					var message = "";
					if(days >0 )message += days + " jours"  +"  ";
					if(hours >0 )message += hours + " h ";
					if(minutes >0 )message += minutes + " min ";
					message += seconds+" sec ";
					$("#text_"+article[1]+"_"+article[2]).html(message);
					if(days==0 && hours==0 && minutes==0 && seconds==0)
					{
						//window.location.reload();
					}
				}	
			});			  
        
		}else{
		$("#time_"+article[1]+"_"+article[2]).countdown({
			timestamp   : ts,
            diff_date  : diff_date,
			callback    : function(days, hours, minutes, seconds){
				var message = "";
				if(days >0 )message += days + " jours"  +"  ";
				if(hours >0 )message += hours + " h " ;
				if(minutes >0 )message += minutes + " min ";
				message += seconds + " sec ";
				$("#text_"+article[1]+"_"+article[2]).html(message);
				if(days==0 && hours==0 && minutes==0 && seconds==0)
				{
					//window.location.reload();
				}
			}
		});
	}
	});
	
	
	//estimate sign date 
		/* $('#estimate_sign_date').datetimepicker({
			format:'Y-m-d',
			lang:'fr',
			timepicker:false
		}); */
		$('#estimate_sign_date').datetimepicker({
			format:'YYYY-M-D',			
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
         });
		
		
	//free mission cost reduced
	
	$("[id^=free_mission_]").change(function(){
		$input = $(this);
		var checkname = $(this).attr("name");
		if($input.is(':checked'))
		{
			$("input:checkbox[name='" + checkname + "']").val("yes");			
		}
		else{
			 $("input:checkbox[name='" + checkname + "']").val("no");
		}			
		fncalculateAutoTotal();	
			
	});

   $(document).on("click",".deletetech",function(){
	var id_identifier = $(this).attr("rel");
		if(confirm("Are you sure? Want to delete this File"))
		{
			//$(this).closest(".topset2").remove();
			var thisvar =$(this).closest('.onsuccessrep');
			thisvar.html("Please Wait Deleting File.");
			$.post("/quote/delete-document-sale",{"identifier":id_identifier},function(result){
					thisvar.html(result);
			}); 
		}	
	});
	
	$(document).on("click",".deletesales",function(e){
		e.preventDefault();
		var id_identifier = $(this).attr("rel");
		msg="Are you sure? Want to delete this File";
		smoke.confirm(msg,function(e)
		{
			if(e){
			$('#sales-document').html("Please Wait Deleting File.");
			$.post("/quote/delete-sales-document",{"identifier":id_identifier},function(result){
				$('#sales-document').html(result);
			}); 
			}
			
		},{"ok":"Oui","cancel":"Non"});	
	});


function removeDisabled(){	setTimeout(function(){$(".MultiFile-applied").removeAttr("disabled");}, 1000);	}

});

//calculate total staff,total internal cost and total delivery
function fnCalculateMissionTime()
{
		
	var total_delivery_time=0;		
	
	//calculating total delivery time
	total_delivery_time=0;
	total_tech_time=0;
	$("[id^=missionlengthval_]" ).each(function(z) {
		var deliveryTime=parseFloat($(this).text());
		
		if(deliveryTime>total_delivery_time)	
		total_delivery_time=deliveryTime;
	});	
	$("[id^=missionlengtht_]" ).each(function(z) {
		var tdeliveryTime=parseFloat($(this).text());
		
		if(tdeliveryTime>total_tech_time)	
		total_tech_time=tdeliveryTime;
	});

	$("#total_mission_length").val(total_delivery_time+total_tech_time);
	
	
}

//calculate unit price and margin with diminish percentage
function fnCalUnitPriceAndMargin(mission_id,percentage)
{
	var unit_price=parseFloat($("#cost_diminish_"+mission_id).attr('data-price').replace(",","."));	
	var FreeMissionval= $("#free_mission_"+mission_id+":checked").val();	
	
	var internalcost=parseFloat($("#internal_cost_"+mission_id).val().replace(",","."));
	var margin=parseFloat($("#margin_percentage_"+mission_id).val().replace(",","."));
	
	var new_unit_price= roundnum(unit_price*(1-(percentage/100)));
	//alert(new_unit_price);
	
	if(new_unit_price>0 && new_unit_price > internalcost)
	{
		var new_margin=roundnum(100*(1-internalcost/new_unit_price));	
		var new_unit_price_text=new_unit_price.replace(".",".");
		$("#unit_price_"+mission_id).val(new_unit_price_text);
		$("#margin_percentage_"+mission_id).val(new_margin);
		
		var volume=parseFloat($("#volume_"+mission_id).text().replace(",","."));
		if(FreeMissionval=='yes')
		{
		var turnover=(0).toFixed(2);
		}
		else
		{
		var turnover=roundnum(volume*new_unit_price);
		}
		
		var turnover_text=turnover.replace(".",".");
		
		$("#turnover_"+mission_id).val(turnover_text);
	}
	
	//total price
	var total_price=0;
	var total_internalcost=0;
	var total_unitprice=0;
	$("[id^=turnover_]" ).each(function(z) {
		//Added w.r.t package
		var tid = $(this).attr('id');
		var tids=tid.split("_");
		
		var tmission_id=tids[1];
		var FreeMissiontoval= $("#free_mission_"+tmission_id+":checked").val();
		var tpackage=$("#package_"+tmission_id).val();
		if(tpackage=='user') 
		{
			var user_fee=$("#user_fee_"+tmission_id).val();
			var number_profiles=$("#profiles_"+tmission_id).val();
			
			if(FreeMissiontoval=='yes')
			{
			user_total=0;
			var missionPrice=parseFloat($("#user_ca_"+tmission_id).val(user_total));	
			}
			else
			{
			user_total=user_fee*number_profiles;
			var missionPrice=parseFloat($("#user_ca_"+tmission_id).val(user_total));	
			}
			//alert(missionPrice);
		}
		else if(tpackage=='team') 
		{
			var mission_turnover=parseFloat($("#turnover_"+tmission_id).val().replace(",","."));
			var team_fee=parseFloat($("#team_fee_"+tmission_id).val().replace(",","."));
			var team_pack=parseFloat($("#team_packs_"+tmission_id).val().replace(",","."));
			if(isNaN(team_pack))
				team_pack=0;
			var team_turnover=parseFloat(team_fee*team_pack);			
			$("#team_fee_ca_"+tmission_id).val(roundnum(team_turnover));//total team fee
			if(FreeMissiontoval=='yes')
				{
				var missionPrice=0;
				}
				else
				{
				var missionPrice=(mission_turnover+team_turnover);
				}
			
			$("#team_ca_"+tmission_id).val(roundnum(missionPrice));
		}
		else
		{//END
			var missionPrice=parseFloat($(this).val().replace(",","."));
		}
		
		
		if(isNaN(missionPrice))
			missionPrice=0;
			
			//free mission calculate
		
		if(FreeMissiontoval=='yes')
		{
			missionPrice=0;
			total_price=total_price+missionPrice;
		}
		else 
		{
			total_price=total_price+missionPrice;	
		}
		
		
	});
	
	var total_price_text=roundnum(total_price);	
	total_price_text=total_price_text.replace(".",".");
	$("#total_price").text(total_price_text);
	//over all margin calculations
	
	$("[id^=unit_price_]" ).each(function(z) {     //unit price total
		var unitPrice=parseFloat($(this).val().replace(",","."));
		if(isNaN(unitPrice))
			unitPrice=0;
		total_unitprice=total_unitprice+unitPrice;
		
	});
	
	$("[id^=internal_cost_]" ).each(function(z) { //internal cost total
		var internalPrice=parseFloat($(this).val().replace(",","."));
		if(isNaN(internalPrice))
			internalPrice=0;
		total_internalcost=total_internalcost+internalPrice;
		
	});
	//alert(total_internalcost+'--'+total_unitprice);
	
	var FreeMissionvaltot= $("#free_mission_"+mission_id+":checked").val();	
		if(FreeMissionvaltot=='yes')
		{
			$("#total_margin").val();
		}
		else 
		{
			var total_margin=roundnum(100-(total_internalcost/total_unitprice)*100);
			$("#total_margin").val(total_margin);
		}
	

}

//calculate total internal cost and total delivery
function fnCalTotalCosts(mission_id,margin_percentage)
{

	var total_price=0;
	var total_internalcost=0;
	var total_unitprice=0;
	
	var volume=parseFloat($("#volume_"+mission_id).text().replace(",","."));
	var internalcost=parseFloat($("#internal_cost_"+mission_id).val().replace(",","."));
	
	var FreeMissionval= $("#free_mission_"+mission_id+":checked").val();
	
	//var unit_price=parseFloat($("#unit_price_"+mission_id).val().replace(",","."));
	
	/*commended based on the cost*/
	//alert(margin_percentage+' margin '+internalcost);
	var unit_price=(internalcost/(1-margin_percentage/100));
	//alert(unit_price);
	//unit_price=unit_price.toFixed(2);
	unit_price=roundnum(unit_price);
	
	//added w.r.t price diminish
	$("#cost_diminish_"+mission_id).attr('data-price',unit_price);
	$("#cost_diminish_"+mission_id).val(0);
	
	
		if(FreeMissionval=='yes')
		{
		var turnover=(0).toFixed(2);
		}
		else
		{

		var turnover=roundnum(volume*unit_price);
		}
	
			
	var turnover_text=turnover.toString().replace(".",".");
	var unit_price_text=unit_price.toString().replace(".",".");
	
	//alert(internalcost+'--'+volume+'--'+margin_percentage+'--'+unit_price);
	$("#unit_price_"+mission_id).val(unit_price_text);
	$("#turnover_"+mission_id).val(turnover_text);
	
	//total price
	$("[id^=turnover_]" ).each(function(z) {
		//Added w.r.t package
		var tid = $(this).attr('id');
		var tids=tid.split("_");
		
		var tmission_id=tids[1];
		
		var FreeMissiontoval= $("#free_mission_"+tmission_id+":checked").val();
		
		var tpackage=$("#package_"+tmission_id).val();

		if(tpackage=='user') 
		{
			var user_fee=$("#user_fee_"+tmission_id).val();
			var number_profiles=$("#profiles_"+tmission_id).val();
			
			if(FreeMissiontoval=='yes')
			{
			user_total=0;
			var missionPrice=parseFloat($("#user_ca_"+tmission_id).val(user_total));	
			}
			else
			{
			user_total=user_fee*number_profiles;
			$("#user_ca_"+tmission_id).val(user_total);
			var missionPrice=parseFloat(user_total);
			//alert(missionPrice);
			}

		}
		else if(tpackage=='team') 
		{
			var mission_turnover=parseFloat($("#turnover_"+tmission_id).val().replace(",","."));
			var team_fee=parseFloat($("#team_fee_"+tmission_id).val().replace(",","."));
			var team_pack=parseFloat($("#team_packs_"+tmission_id).val().replace(",","."));
			if(isNaN(team_pack))
				team_pack=0;
			var team_turnover=parseFloat(team_fee*team_pack);			
			
			$("#team_fee_ca_"+tmission_id).val(roundnum(team_turnover));//total team fee
			
			if(FreeMissiontoval=='yes')
				{
				var missionPrice=0;
				}
				else
				{
				var missionPrice=(mission_turnover+team_turnover);
				}
			
			$("#team_ca_"+tmission_id).val(roundnum(missionPrice));
		}
		else
		{//END
			var missionPrice=parseFloat($(this).val().replace(",","."));
		}
		
		
		if(isNaN(missionPrice))
			missionPrice=0;
			
		
		
		if(FreeMissiontoval=='yes')
		{
			missionPrice=0;
			total_price=total_price+missionPrice;
		
		}
		else 
		{
			total_price=total_price+missionPrice;	
		
		}
		
	});
	//Calculate For Free Mission
	//alert(total_price);
	var total_price_text=roundnum(total_price);	
	total_price_text=total_price_text.toString().replace(".",".");
	$("#total_price").text(total_price_text);
		
	//over all margin calculations
	
	$("[id^=unit_price_]" ).each(function(z) {     //unit price total
		var unitPrice=parseFloat($(this).val().replace(",","."));
		if(isNaN(unitPrice))
			unitPrice=0;
		
		var divDetails=$(this).attr('id');
		divDetails=divDetails.split("_");
		var mission_id=divDetails[2];
		var FreeMissionval= $("#free_mission_"+mission_id+":checked").val();
		if(FreeMissionval=='yes'){
			total_unitprice=total_unitprice+0;
		}
		else{
			total_unitprice=total_unitprice+unitPrice;
		}
		
	});
	
	$("[id^=internal_cost_]" ).each(function(z) { //internal cost total
		var internalPrice=parseFloat($(this).val().replace(",","."));
		if(isNaN(internalPrice))
			internalPrice=0;
		
		var divDetails=$(this).attr('id');
		divDetails=divDetails.split("_");
		var mission_id=divDetails[2];
		
		var FreeMissionval= $("#free_mission_"+mission_id+":checked").val();	
		if(FreeMissionval=='yes'){
			total_internalcost=total_internalcost+0;
		}
		else
		{
			total_internalcost=total_internalcost+internalPrice;
		}	
		
	});
	//alert(total_internalcost+'--'+total_unitprice);
	
	var total_margin=(100-(total_internalcost/total_unitprice)*100).toFixed(5);
	if(isNaN(total_margin))
		total_margin=0;
	$("#total_margin").val(total_margin);
	

}

function fnChangeAllMargins(margin_percentage)
{	
	margin_percentage=margin_percentage.replace(",",".");
	var NanValue=false;
	if(isNaN(margin_percentage) || margin_percentage=='')
	{
			margin_percentage=0;
		NanValue=true;
	}
	//chage prices of all missions w.r.t total margin
	$("[id^=margin_percentage_]" ).each(function(z) {
		var divDetails=$(this).attr('id');
		divDetails=divDetails.split("_");
		var mission_id=divDetails[2];			
		var percentage=margin_percentage;
		percentage=parseFloat(percentage);
		$(this).val(percentage);
		fnCalTotalCosts(mission_id,percentage);		
	});
	if(!NanValue)
	$("#total_margin").val(margin_percentage);
	else
		$("#total_margin").val('');

}

function fncalculateAutoTotal()
{
	$("[id^=margin_percentage_]" ).each(function(z) {
		var divDetails=$(this).attr('id');
		divDetails=divDetails.split("_");
		var mission_id=divDetails[2];			
		var percentage=parseFloat($(this).val().replace(",","."));
		fnCalTotalCosts(mission_id,percentage);		
	});
}

/** ajax function to update seo mission include_final status**/
function ajaxSEOMissionUpdate(quote_id,mission_identifier,divid,last)
{
        var target_page = "/quote/delete-quote-mission?type=includes_update&quote_id="+quote_id+"&mission_identifier="+mission_identifier;
		//alert(target_page);	
		$.post(target_page, function(data){					
				//alert(data);
				sleep(2000);
				$("#"+divid).remove();
				if(last=='final')
					location.reload();
			});
}


/** ajax function to update tech mission include_final status**/
function ajaxTECHMissionUpdate(quote_id,mission_identifier,divid,last)
{
        var target_page = "/quote/delete-quote-mission?mission_type=tech&type=includes_update&quote_id="+quote_id+"&mission_identifier="+mission_identifier;
		//alert(target_page);	
		$.post(target_page, function(data){					
				//alert(data);
				sleep(2000);
				$("#"+divid).remove();
				if(last=='final')
					location.reload();
			});
}


function loadeditarticle(index,tmission)
{
	if(tmission=='m')
	{
		$('#epmargin').addClass('validate[required,minWriters[0.01],maxWriters[99.99]]');
	}
	else
	{
		$('#epmargin').addClass('validate[required,minWriters[0.00],maxWriters[99.99]]');
	}
		var unit_price=$("#unit_price_"+index).val().replace(",",".");
		var margin=$("#margin_percentage_"+index).val().replace("%","");	
		$("#price_per_article").val(unit_price);
		$("#epmargin").val(margin);
		var internal_cost=roundnum((unit_price*(100-margin))/100);
		//alert(unit_price+'--'+margin+'--'+internal_cost);
		$("#internal_cost_"+index).val(internal_cost);
		$("#missionindex").val(index);	
		
}
function changeOnPrice()
{
	if($("#changeFormValue").validationEngine('validate'))
	{
	var index=$("#missionindex").val();
	var price=$('#internal_cost_'+index).val();
	var price_per_article=$("#price_per_article").val().replace(",",".");
	var margin=(price * 100)/(price_per_article);
	//if(margin<100)
	var marginval=100-margin;
	if(Math.floor(marginval) == marginval)
		$("#epmargin").val(marginval);
	else
		$("#epmargin").val(round5num(marginval));
	}

}
function changeOnMargin()
{
	if($("#changeFormValue").validationEngine('validate'))
{
	var index=$("#missionindex").val();
	var margin=$("#epmargin").val().replace(",",".");
	var internalcost=$('#internal_cost_'+index).val();
	var price_per_article=(internalcost/(1-margin/100));
	if(Math.floor(price_per_article) == price_per_article)
		$("#price_per_article").val(price_per_article);
	else
		$("#price_per_article").val(roundnum(price_per_article));
}
}
function validatearticleprice()
{
	if($("#changeFormValue").validationEngine('validate'))
{
	var index=$("#missionindex").val();
	var quote_id='{/literal}{$quotes.quote_id}{literal}';
	var margin=$("#epmargin").val().replace(",",".");
	var price_per_article=roundnum(parseFloat($("#price_per_article").val().replace(",",".")));
	var internal_cost=$("#internal_cost_"+index).val();		
	$.ajax({
		type: 'GET',
		url: '/quote-new/update-unit-price',
		data: 'quote_id='+quote_id+'&index='+index +'&margin_percentage='+margin+ '&unit_price='+price_per_article+'&internal_cost='+internal_cost+'&updateby=sales',			  
		success: function(data)
		{   
			//alert(data);
			$('#editarticleprice').modal('toggle');			
			$("#unit_price_"+index).val(price_per_article);
			$("#margin_percentage_"+index).val(margin);
			fncalculateAutoTotal();
		}
	 });		
	return false;
	}
}

</script>
<style>
.MultiFile-title{
	width:100% !important;
	font-size:13px !important;
	}
</style>
{/literal}

{include file="gebo-new/quote/header.phtml"}


		<div id="quote-final" class="container-fluid">
			<div class="content">	
			<h1><small>{$create_step1.quote_title}</small><br> Final Quote</h1>

			<div class="">
				<div class="tab-content">
					<div role="tabpanel"  class="tab-pane fade in active " id="overview">
						<form action="/quote-new/save-final-validation?quote_id={$quotes.quote_id}" method="POST" name="save_final_validation" id="save_final_validation" enctype="multipart/form-data" class="form-inline">	
							<input type="hidden" id="quote_id" name="quote_id" value="{$quotes.quote_id}">
							
								<table class="misson-details-text table table-condensed" id="mission-head">
									<tr>
										<th class="col-xs-2">
										<label>{if $quotes.final_mission_length_difference eq 'yes'}
														<span class="version-change pop_over" data-placement="right" data-original-title="Historique devis" data-content="{$quotes.final_mission_length_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i></span>
												{/if}
												Contract duration</label>													
											<div class="form-group">
												
												<div class="input-group">
													<input type="text" id="total_mission_length" value="{if $quotes.final_mission_length}{$quotes.final_mission_length}{/if}" name="total_mission_length" class="validate[required] input-small form-control" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser'} {else}disabled="disable"{/if}>											
													<div class="input-group-addon">Day(s)</div>
												</div>
												<input type="hidden" name="total_time_option" id="total_time_option" value="days">
													<!--final_mission_length_option-->
											</div>
										</th>
										<!--th class="col-xs-2 text-center">
										<label>Exptected launch date</label>
											<div class="form-group">
											<input type="text" id="prod_extra_launch_days" value="{if $quotes.prod_extra_launch_days}{$quotes.prod_extra_launch_days} {/if}" name="prod_extra_launch_days" class="form-control input-small" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser'} {else}disabled="disable"{/if}>
												<label class="text-uppercase" for="text"> Jours</label>
											</div>
										</th-->
									
										
										<th class="col-xs-3">
											<label>Estimation / Date of signature</label><br>
										<div class="form-inline">	
										<div class="form-group" >
																	
													<select name="estimate_sign_percentage" id="estimate_sign_percentage" class="form-control" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser'} {else}disabled="disable"{/if}>			
														<option {if $quotes.estimate_sign_percentage eq '20'} selected {/if} value="20" >20%</option>
														<option value="40" {if $quotes.estimate_sign_percentage eq '40'} selected {/if} >40%</option>
														<option value="60" {if $quotes.estimate_sign_percentage eq '60'} selected {/if} >60%</option>
														<option value="80" {if $quotes.estimate_sign_percentage eq '80'} selected {/if}>80%</option>
													</select>
													
												</div>	
													
											<div class="form-group">
												
												<input class="validate[required] form-control" placeholder="Enter a date" value="{$quotes.estimate_sign_date}" type="text" name="estimate_sign_date" id="estimate_sign_date" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser'} {else}disabled="disable"{/if}/>
											</div>
										</div>
										</th>
										<th class="col-xs-2">
											<div class="form-group">
											<label>{if $quotes.final_margin_difference eq 'yes'}
												<span class="version-change pop_over" data-placement="left" data-original-title="Previous versions" data-content="{$quotes.final_margin_versions|escape|stripslashes}" data-html="true">  <i class="fa fa-bar-chart-o"></i>
											{/if} Margin</label><br>
												<div class="input-group">
											
													<input type="text" id="total_margin" name="total_margin" class="form-control" onkeyup="fnChangeAllMargins(this.value);" value="{$quotes.total_margin}" size="10" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser'} {else}disabled="disable"{/if} >
													<span class="input-group-addon">%</span>
												</div>
												</div>

										</th>
										<th class="col-xs-3 text-right total-price">
											
											
											<h2>
												<small>{if $quotes.final_turnover_difference eq 'yes'}
											<span class="version-change pop_over" data-placement="left" data-original-title="<font style='color:#34495e'>Historique devis</font>" data-content="{$quotes.final_turnover_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
										{/if} Total </small><br>
										<span id="total_price" ></span>&{$create_step1.currency}; </h2>
												
											
										</th>

										<!--<th class="submit-color text-center">
											<div  style="vertical-align: bottom;">
											{*{if $user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager' || $user_type eq 'seouser' || $user_type eq 'seomanager' || $user_type eq 'techuser' || $user_type eq 'techmanager'}*}
											<!--<button type="submit" class="btn btn-lg btn-simple" style="background-color:#3598db;padding:5px;margin: 20px 0 0;color:#fff;"><span class="glyphicon glyphicon-ok"></span></button>-->
											{*{else}*}
												<!--<button type="submit" class="btn btn-lg btn-simple" style="background-color:#3598db;padding:5px;margin: 20px 0 0;color:#fff;"><span class="glyphicon glyphicon-ok"></span> </button></div>
											{*{/if}*}
												
										</th>-->
									</tr>
																												
								</table>
												
							
							{if $quote_missions.tech.linked_to_prod|@count gt 0}
																													
													
								{foreach from=$quote_missions.tech.linked_to_prod item=tmission name="tmission"}
								
								
									{assign var=tn_index value=$smarty.foreach.tmission.index}
									{assign var=tms_index value=$smarty.foreach.tmission.index+1}					{if $tmission eq 'all_prod' && $quote_missions.tech.$tn_index.to_perform eq 'Before'}
										<!--{assign var=ms_index value=$smarty.foreach.misson.index+1}-->
										<div  id="mission_details_t{$tms_index}" class="prod_mission">	
											<div class="mission-details">								
												
												<table class="table table-bordered tech_list">		
													<tr>
													  <td class="col-md-3">
													  <div class="pull-left mission-title">
													  {if $quote_missions.tech.$tn_index.title_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.title_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
														{/if}
														{$quote_missions.tech.$tn_index.tech_type}</div>
													  <div class="pull-left grey-text" style="clear:both"> {$quote_missions.tech.$tn_index.language_name} </div>
													  </td>
													  
													  {if $quote_missions.tech.$tn_index.tech_oneshot eq 'no'}
													  <td class="col-md-2" colspan="2">

													  <div class="text-center pull-left" style="width:50%">
													  <span class="p" id="missionlengtht_{$tms_index}">
													  {if $quote_missions.tech.$tn_index.mission_length_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.mission_length_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
														{/if}{$quote_missions.tech.$tn_index.tech_mission_length}</span>

														<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required"  style="background:#fff;">
													 
															 <div class="text-uppercase grey-text">Days</div>
														 </div>	 
														<div class="text-center pull-right " style="width:50%">
															<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
															
															<div class="text-uppercase grey-text">Volume</div>
															</div>
															
															<span class="col-md-12" style="border-top:1px solid #ddd;"></span>
															<div  class="text-center text-uppercase" >
															<span class="col-md-12" style="padding:5px;">
																<strong>{$quote_missions.tech.$tn_index.volume_max}</strong>  <span class="grey-text">{$quote_missions.tech.$tn_index.delivery_volume_option}</span> <strong>{$quote_missions.tech.$tn_index.tempo_length}</strong> <span class="grey-text">{if $quote_missions.tech.$tn_index.tempo_length_option eq 'days'}JOURS{else}{$quote_missions.tech.$tn_index.tempo_length_option}{/if}</span>
															</span>
															</div>
															
															
															</div>
														</td>
														{else}
													  <td class="col-md-1">
													  <div class="text-center">
													 <span class="p" id="missionlengtht_{$tms_index}">
													  {$quote_missions.tech.$tn_index.tech_mission_length}</span>
														<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required"  style="background:#fff;">
													  </div>
															 <span class="text-uppercase grey-text">Days</span>
															 
														</td>

														<td>
														<div class="text-center">
															<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
															</div>
															<span class="text-uppercase grey-text">	VOLUME</span>
														</td>
														{/if}
														<td class="col-md-1 text-center">
														
															<div class="">
															
															<input  id="unit_price_t{$tms_index}" size="5" name="unit_price_t{$tms_index}" value="{$quote_missions.tech.$tn_index.unit_price|zero_cut:2}" class="highQuote {if $quote_missions.tech.$tn_index.cost_difference eq 'yes'} new-version{/if}" readonly="readonly">
															<sup>&{$create_step1.currency};</sup>
															</div>
															<div class="text-uppercase grey-text">Selling P/ART</div>
															<input  id="internal_cost_t{$tms_index}" name="internal_cost_t{$tms_index}" value="{$quote_missions.tech.$tn_index.internal_cost|zero_cut:2}" class="form-control highQuote" type="hidden"> 
															{if $quote_missions.tech.$tn_index.cost_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.price_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> </span>
															{/if}
															<!--<div class="col-md-12 text-center">
																<div class="input-group">
																	<span class="input-group-addon">-</span>
																<input data-price="{$mission.unit_price|zero_cut:2}" class="form-control validate[required]" type="text" id="cost_diminish_{$ms_index}" name="cost_diminish_{$ms_index}" onkeyup="fnCalUnitPriceAndMargin('{$ms_index}',this.value);" value="0"><span class="input-group-addon">%</span>
																</div>
															</div>-->

														
														
													</td>
														<td class="col-md-1 text-center">
													<a {if $quotes.sales_review neq 'signed'}data-toggle="modal" href="" data-target="#editarticleprice" onClick="loadeditarticle(t{$tms_index},'')" {/if}>
															<div class="input-group" >
																	<input type="text" readonly="readonly"  class="form-control validate[required]" id="margin_percentage_t{$tms_index}" name="margin_percentage_t{$tms_index}" onkeyup="fnCalTotalCosts('t{$tms_index}',this.value);" value="{$quote_missions.tech.$tn_index.margin_percentage}" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} style="cursor:pointer;"><span class="input-group-addon">%</span>
															</div>											
															<span class="text-uppercase grey-text">Margin</span>		
															</a>	
															
														</td>
														
														<td class="mission-pakage col-md-3">
														<div style="display:none;">
															<select name="package_t{$tms_index}" id="package_t{$tms_index}" class="validate[required] pakage-select" onchange="updatepackage('t{$tms_index}',this.value,'{$tn_index}');" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>
																	<option value="lead" {if $quote_missions.tech.$tn_index.package eq 'lead'} selected{/if} >Lead</option>
																	<option value="team" {if $quote_missions.tech.$tn_index.package eq 'team'} selected{/if}>Team</option>
																	<option value="link" {if $quote_missions.tech.$tn_index.package eq 'link'} selected{/if}>Link</option>
																		{*<option value="user" {if $quote_missions.tech.$tn_index.package eq 'user'} selected{/if}>User</option>*}
															</select>
														</div>
														<table>
																<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'team'}style="display:none"{/if} id="other_details_team_t{$tms_index}">
																<td>
																<div class="form-group col-md-12">
																	<!--<span style=" display: block;padding-top: 0px;">Nombre de profils : {$mission.required_writes}</span>-->
																	<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}" >
																
																	<input type="text" class="form-control validate[required]" id="team_packs_t{$tms_index}" name="team_packs_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}" onkeyup="fncalculateAutoTotal();" size="2" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}> x 		
																	
																		<span class="input-group"><input type="text" class="form-control validate[required]" id="team_fee_t{$tms_index}" name="team_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_fee|zero_cut:2}" onkeyup="fncalculateAutoTotal();" size="2"><span class="input-group-addon" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>&{$create_step1.currency};/Pack</span></span>
																	 =
																	<input  id="team_fee_ca_t{$tms_index}" name="team_fee_ca_t{$tms_index}" value="" class="color-normal" style="cursor:text;" readonly="readonly" size="2">&{$create_step1.currency};
																</div>
																	<span style=" display: block;padding-top: 0px;">
																		CA Total : 
																		<input  id="team_ca_t{$tms_index}" name="team_ca_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_package_turnover|zero_cut:2}" class=" highQuote color-normal" style="cursor:text;" readonly="readonly" size="5"> &{$create_step1.currency};
																	</span>	
																</td>
															</tr>
															<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'user'}style="display:none"{/if} id="other_details_user_t{$tms_index}">
																<td >
																<div class="form-group col-md-12">
																	<span style=" display: block;padding-top: 0px;">Nb of profile: {$quote_missions.tech.$tn_index.required_writes}</span>
																	<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}">
																	Fees offre user : 
																	<div class="input-group">
																	<input type="text" class="form-control validate[required]" id="user_fee_t{$tms_index}" name="user_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.user_fee|zero_cut:2}"  onkeyup="fnCalUserTurnover('t{$tms_index}',{$quote_missions.tech.$tn_index.user_fee|zero_cut:2},1);" size="4" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} ><span class="input-group-addon">&{$create_step1.currency};</span>
																	</div>
																
																	<span style=" display: block;padding-top: 0px;">
																		CA Total :  
																		<input  id="user_ca_t{$tms_index}" name="user_ca_t{$tms_index}" value="" class="remove-border highQuote" style="cursor:text;" readonly="readonly" size="5">&{$create_step1.currency};
																	</span>	

																	</div>
																</td>											
																</tr>
														</table>
														</td>

														<td class="mission-turnover col-md-2 text-right" >
															<div class="input-group">
																<input  id="turnover_t{$tms_index}" name="turnover_t{$tms_index}" value="{$quote_missions.tech.$tn_index.turnover|zero_cut:2}" class="remove-border" readonly="readonly"> &{$create_step1.currency};
																
															</div>
															 
															<div class="free-mission">
																<label class="checkbox">
																	<input type="checkbox" name="free_mission_t{$tms_index}" value="{if $quote_missions.tech.$tn_index.free_mission eq 'yes'}yes{else}no{/if}" id="free_mission_t{$tms_index}" {if $quote_missions.tech.$tn_index.free_mission eq 'yes'}checked="checked"{/if} {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} class="icheck"/>
																	<span class="free-label">Free</span>
																</label>
															</div>
															
														</td>
														
													</tr>

												</table>
											</div>
										</div>	
									{/if}
								{/foreach}				
							{/if}
								{if $quote_missions|@count gt 0}						
								{foreach from=$quote_missions item=mission name="misson"}
									{assign var=gn_index value=$smarty.foreach.misson.index}
									{assign var=ms_index value=$smarty.foreach.misson.index+1}
									{if $mission.product_name}
										<!--{assign var=ms_index value=$smarty.foreach.misson.index+1}-->
										<div  id="mission_details_{$gn_index}">	
											<div class="mission-details">								
												
												<table class="table table-bordered prod_seo_list">		
													<tr>
													  <td class="col-md-3">
													  <div class="pull-left mission-title">
													  {if $mission.product_name eq 'Content Strategy'}
													  Mission De {$mission.product_name} {if $mission.producttype_name}/ {$mission.producttype_name} {/if} 
													  {else}
													   <a  data-toggle="modal" data-target="#editmission" href="/quote-new/prod-mission-edit-popup?quote_id={$quotes.quote_id}&id={$mission.identifier}&offset={$ms_index}">Mission De {$mission.product_name} {if $mission.producttype_name}/ {$mission.producttype_name} {/if} {if $mission.nb_words}/ {$mission.nb_words} {/if} </a>
													   {/if}</div>
													  <div class="pull-left grey-text" style="clear:both"> {$mission.language_name} {if $mission.product eq 'translation'} > {$mission.languagedest_name}{/if} </div>
													  </td>
													  
													  {if $mission.oneshot eq 'no'}
													  <td class="col-md-2" colspan="2">

													  <div class="text-center pull-left" style="width:50%">
													  <span class="p" id="missionlengthval_{$ms_index}">{$mission.mission_staff}</span>

														<input type="hidden"  id="mission_length_{$ms_index}" name="mission_length_{$ms_index}" value="{$mission.mission_length}" class="input-small form-control validate[required {if $mission.oneshot eq 'yes'},minWriters[{$mission.mission_length}]{/if}] {if $mission.mission_length_new neq 0 && $mission.mission_length_new neq "" && $mission.oneshot eq 'no'}minWriters[{$newduration[0]}] {/if}"  style="background:#fff;">
													 
															 <div class="text-uppercase grey-text">Days</div>
														 </div>	 
														<div class="text-center pull-right " style="width:50%">
															<span class="p" id="volume_{$ms_index}">{$mission.volume}</span>
															
															<div class="text-uppercase grey-text">VOLUME</div>
															</div>
															
															<span class="col-md-12" style="border-top:1px solid #ddd;"></span>
															<div id="tempo_details_{$ms_index}" class="text-center text-uppercase">
															<span class="col-md-12" style="padding:5px;">
																<strong>{$mission.volume_max}</strong> <span class="grey-text"> {$mission.tempo_type_text} {$mission.delivery_volume_option_text}</span>  <strong>{$mission.tempo_length}</strong> <span class="grey-text">{$mission.tempo_length_option_text}</span>
																</span>
															</div>
															
															
															</div>
														</td>
													  {else}
													  <td class="col-md-1 text-center">
													  <div class="text-center">
														  <span class="p" id="missionlengthval_{$ms_index}">{$mission.mission_staff}</span>

													<input type="hidden"  id="mission_length_{$ms_index}" name="mission_length_{$ms_index}" value="{$mission.mission_length}" class="input-small form-control validate[required {if $mission.oneshot eq 'yes'},minWriters[{$mission.mission_length}]{/if}] {if $mission.mission_length_new neq 0 && $mission.mission_length_new neq "" && $mission.oneshot eq 'no'}minWriters[{$newduration[0]}] {/if}"  style="background:#fff;">
													  </div>
															 <span class="text-uppercase grey-text">Days</span>
															 
										
														</td>

														<td class="col-md-1 text-center">
														<div class="text-center">
															<span class="p" id="volume_{$ms_index}">{$mission.volume}</span>
															</div>
															<span class="text-uppercase grey-text">VOLUME</span>
														</td>
														{/if}
														<td class="col-md-1 text-center">
															{if $mission.product_name neq 'Content Strategy'}
																<a  data-toggle="modal" data-target="#editmission" href="/quote-new/prod-mission-edit-popup?quote_id={$quotes.quote_id}&id={$mission.identifier}&offset={$ms_index}">
															{/if}	
																<div class="">
																	
																	<input  id="unit_price_{$ms_index}" size="5" name="unit_price_{$ms_index}" value="{$mission.unit_price|zero_cut:2}" class="highQuote {if $mission.unit_price_difference eq 'yes'}new-version{/if}" readonly="readonly">
																	<sup>&{$create_step1.currency};</sup>
																</div>
																	
																<div class="text-uppercase grey-text">Selling P/art</div>
																<input  id="internal_cost_{$ms_index}" name="internal_cost_{$ms_index}" value="{$mission.internal_cost|zero_cut:2}" class="form-control highQuote"  type="hidden"> 
															<!--<div class="col-md-12 text-center">
																<div class="input-group">
																	<span class="input-group-addon">-</span>
																<input data-price="{$mission.unit_price|zero_cut:2}" class="form-control validate[required]" type="text" id="cost_diminish_{$ms_index}" name="cost_diminish_{$ms_index}" onkeyup="fnCalUnitPriceAndMargin('{$ms_index}',this.value);" value="0"><span class="input-group-addon">%</span>
																</div>
															</div>-->
															{if $mission.product_name neq 'Content Strategy'}
																</a>
															{/if}

															{if $mission.unit_price_difference eq 'yes'}
																		<span class="version-change pop_over" data-placement="top" data-original-title="Previous versions" data-content="{$mission.price_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> </span>
																	{/if}
	
													</td>
														<td class="col-md-1 text-center">
														{if $mission.margin_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.margin_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i></span>
															</div>	
														{/if}
														<a {if $quotes.sales_review neq 'signed'} data-toggle="modal" href="" data-target="#editarticleprice" onClick="loadeditarticle({$ms_index},'m') " {/if}>
														
															<div class="input-group" >
																	<input type="text" readonly="readonly"  class="form-control validate[required]" id="margin_percentage_{$ms_index}" name="margin_percentage_{$ms_index}" onkeyup="fnCalTotalCosts('{$ms_index}',this.value);" value="{$mission.margin_percentage}" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ( $user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if} style="cursor:pointer;"><span class="input-group-addon">%</span>
															</div>											
															<span class="text-uppercase grey-text">Margin</span>
															</a>
															
														</td>
														
														<td class="mission-pakage col-md-3">
														<div {if $mission.product_name eq 'Content Strategy'} style="display:none;" {/if}>
															<select name="package_{$ms_index}" id="package_{$ms_index}" class="validate[required] pakage-select" onchange="updatepackage('{$ms_index}',this.value,'{$gn_index}');" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ( $user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if}>
																	<option value="lead" {if $mission.package eq 'lead'} selected{/if} >Lead</option>
																	<option value="team" {if $mission.package eq 'team'} selected{/if}>Team</option>
																	<option value="link" {if $mission.package eq 'link'} selected{/if}>Link</option>
																	{*<option value="user" {if $mission.package eq 'user'} selected{/if}>User</option>*}
															</select>
														</div>
														<table>
																<tr class="misson-details-text" {if $mission.package neq 'team'}style="display:none"{/if} id="other_details_team_{$ms_index}">
																<td>
																<div class="form-group col-md-12">
																	<!--<span style=" display: block;padding-top: 0px;">Nombre de profils : {$mission.required_writes}</span>-->
																	<input type='hidden' name="profiles_{$ms_index}" id="profiles_{$ms_index}" value="1" >
																
																	<input type="text" class="form-control validate[required]" id="team_packs_{$ms_index}" name="team_packs_{$ms_index}" value="{$mission.team_packs}" onkeyup="fncalculateAutoTotal();" size="2" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ( $user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if}> x 		
																	
																		<span class="input-group"><input type="text" class="form-control validate[required]" id="team_fee_{$ms_index}" name="team_fee_{$ms_index}" value="{$mission.team_fee|zero_cut:2}" onkeyup="fncalculateAutoTotal();" size="2"><span class="input-group-addon">&{$create_step1.currency};/Pack</span></span>
																	 =
																	<input  id="team_fee_ca_{$ms_index}" name="team_fee_ca_{$ms_index}" value="" class="color-normal" style="cursor:text;" readonly="readonly" size="2">&{$create_step1.currency};
																</div>
																	<span style=" display: block;padding-top: 0px;">
																		CA Total : 
																		<input  id="team_ca_{$ms_index}" name="team_ca_{$ms_index}" value="{$mission.team_package_turnover|zero_cut:2}" class=" highQuote color-normal" style="cursor:text;" readonly="readonly" size="5"> &{$create_step1.currency};
																	</span>	
																</td>
															</tr>
															<tr class="misson-details-text" {if $mission.package neq 'user'}style="display:none"{/if} id="other_details_user_{$ms_index}">
																<td >
																<div class="form-group col-md-12">
																	<span style=" display: block;padding-top: 0px;">Nombre de profils : 1{$mission.required_writes}</span>
																	<input type='hidden' name="profiles_{$ms_index}" id="profiles_{$ms_index}" value="1">
																	Fees offre user : 
																	<div class="input-group">
																	<input type="text" class="form-control validate[required]" id="user_fee_{$ms_index}" name="user_fee_{$ms_index}" value="{$mission.user_fee|zero_cut:2}"  onkeyup="fnCalUserTurnover('{$ms_index}',{$mission.user_fee|zero_cut:2},1);" size="4" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ($user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if}><span class="input-group-addon">&{$create_step1.currency};</span>
																	</div>
																
																	<span style=" display: block;padding-top: 0px;">
																		CA Total :  
																		<input  id="user_ca_{$ms_index}" name="user_ca_{$ms_index}" value="" class="color-normal  highQuote" style="cursor:text;" readonly="readonly" size="5" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ($user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if}><sup>&{$create_step1.currency};</sup>
																	</span>	

																	</div>
																</td>											
																</tr>
														</table>
														</td>

														<td class="mission-turnover col-md-2 text-right">
															<div class="input-group">
																<input id="turnover_{$ms_index}" name="turnover_{$ms_index}" value="{$mission.turnover|zero_cut:2}" class="remove-border mission-price" readonly="readonly">&{$create_step1.currency};
																
															</div>
																<div class="free-mission">
																	<label class="checkbox">
																		<input type="checkbox" name="free_mission_{$ms_index}" value="{if $mission.free_mission eq 'yes'}yes{else}no{/if}" id="free_mission_{$ms_index}" {if $mission.free_mission eq 'yes'}checked="checked"{else if $mission.free_mission eq 'no'}{/if}  {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || (($mission.product eq 'translation' || $mission.product eq 'redaction') && ($user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager')) || ($mission.product_name eq 'Content Strategy' && ($user_type eq 'seouser' || $user_type eq 'seomanager'))} {else}disabled="disable"{/if} class="icheck"> </input>
																		<span class="free-label">Free</span>
																	</label>	
																</div>
																
														</td>
														
													</tr>
													</table>
										</div>
									</div>	
																						
								{if $mission.identifier|in_array:$quote_missions.tech.linked_to_prod}
								{assign var=keys value=$quote_missions.tech.linked_to_prod|@array_search|@array_pop}
								
								{if $quote_missions.tech.linked_to_prod|@count gt 0}
								
													
								{foreach from=$quote_missions.tech.linked_to_prod item=tmission name="tmission"}
								{assign var=tn_index value=$smarty.foreach.tmission.index}
									{assign var=tms_index value=$smarty.foreach.tmission.index+1}
								{if $mission.identifier eq $tmission}
															
										<!--{assign var=ms_index value=$smarty.foreach.misson.index+1}-->
																		
											<div  id="mission_details_t{$tms_index}" class="prod_mission">	
											<div class="mission-details">		
												<table class="table table-bordered tech_list {if $quote_missions.tech.$tn_index.to_perform eq 'Before'} before-prod {elseif $quote_missions.tech.$tn_index.to_perform eq 'After'} after-prod {else}  during-prod{/if}">		
													<tr>
													  <td class="col-md-3">
													  <div class="pull-left mission-title">
													  {if $quote_missions.tech.$tn_index.title_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.title_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
														{/if}
														{$quote_missions.tech.$tn_index.tech_type}</div>
													  <div class="pull-left grey-text" style="clear:both"> {$quote_missions.tech.$tn_index.language_name} </div>
													  </td>
													  
													  {if $quote_missions.tech.$tn_index.tech_oneshot eq 'no'}
													  <td class="col-md-2" colspan="2" style="padding:0px;margin:0px">

													  <div class="text-center pull-left" style="width:50%">
													  <span class="p" id="missionlengtht_{$tms_index}">
													  {if $quote_missions.tech.$tn_index.mission_length_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Previous versions" data-content="{$quote_missions.tech.$tn_index.mission_length_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
														{/if}{$quote_missions.tech.$tn_index.tech_mission_length}</span>

														<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required">
													 
															 <div class="text-uppercase grey-text">Days</div>
														 </div>	 
														<div class="text-center pull-right " style="width:50%">
															<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
															
															<div class="text-uppercase grey-text">VOLUME</div>
															</div>
															
															<span class="col-md-12" style="border-top:1px solid #ddd;"></span>
															<div  class="text-center text-uppercase" >
															<span class="col-md-12" style="padding:5px;">
																<strong>{$quote_missions.tech.$tn_index.volume_max}</strong>  <span class="grey-text">{$quote_missions.tech.$tn_index.delivery_volume_option}</span> <strong>{$quote_missions.tech.$tn_index.tempo_length}</strong> <span class="grey-text">{if $quote_missions.tech.$tn_index.tempo_length_option eq 'days'}JOURS{else}{$quote_missions.tech.$tn_index.tempo_length_option}{/if}</span>
															</span>
															</div>
															
															
															</div>
														</td>
														{else}
													  <td class="col-md-1 text-center">
													  <div class="text-center">
													  <span class="p" id="missionlengtht_{$tms_index}">
													  {$quote_missions.tech.$tn_index.tech_mission_length}</span>
														<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required"  style="background:#fff;">
													  </div>
															 <span class="text-uppercase grey-text">Days</span>
															 
														</td>

														<td class="col-md-1 text-center">
														<div class="text-center">
															<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
															</div>
															<span class="text-uppercase grey-text">VOLUME</span>
														</td>
														{/if}
														<td class="col-md-1 text-center">
														
															<div class="">
															<input  id="unit_price_t{$tms_index}" size="5" name="unit_price_t{$tms_index}" value="{$quote_missions.tech.$tn_index.unit_price|zero_cut:2}" class="highQuote {if $quote_missions.tech.$tn_index.cost_difference eq 'yes'}new-version{/if}" readonly="readonly">
															<sup>&{$create_step1.currency};</sup>
															</div>
															<div class="text-uppercase grey-text">Selling P/ART</div>
															<input  id="internal_cost_t{$tms_index}" name="internal_cost_t{$tms_index}" value="{$quote_missions.tech.$tn_index.internal_cost|zero_cut:2}" class="form-control highQuote"  type="hidden">
															{if $quote_missions.tech.$tn_index.cost_difference eq 'yes'}
															<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.price_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> </span>
															{/if}
															<!--<div class="col-md-12 text-center">
																<div class="input-group">
																	<span class="input-group-addon">-</span>
																<input data-price="{$mission.unit_price|zero_cut:2}" class="form-control validate[required]" type="text" id="cost_diminish_{$ms_index}" name="cost_diminish_{$ms_index}" onkeyup="fnCalUnitPriceAndMargin('{$ms_index}',this.value);" value="0"><span class="input-group-addon">%</span>
																</div>
															</div>-->

														
														
													</td>
														<td class="col-md-1 text-center">
													
															<a {if $quotes.sales_review neq 'signed'} data-toggle="modal" href="" data-target="#editarticleprice" onClick="loadeditarticle('t{$tms_index}','')" {/if}>
															<div class="input-group" >
																	<input type="text" readonly="readonly"  class="form-control validate[required]" id="margin_percentage_t{$tms_index}" name="margin_percentage_t{$tms_index}" onkeyup="fnCalTotalCosts('t{$tms_index}',this.value);" value="{$quote_missions.tech.$tn_index.margin_percentage}" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} style="cursor:pointer;"><span class="input-group-addon">%</span>
															</div>											
															<span class="text-uppercase grey-text">Margin</span>		</a>
															
														</td>
														
														<td class="mission-pakage col-md-3">
														<div style="display:none;">
															<select name="package_t{$tms_index}" id="package_t{$tms_index}" class="validate[required] pakage-select" onchange="updatepackage('t{$tms_index}',this.value,'{$tn_index}');" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>
																	<option value="lead" {if $quote_missions.tech.$tn_index.package eq 'lead'} selected{/if} >Lead</option>
																	<option value="team" {if $quote_missions.tech.$tn_index.package eq 'team'} selected{/if}>Team</option>
																	<option value="link" {if $quote_missions.tech.$tn_index.package eq 'link'} selected{/if}>Link</option>
																	{*<option value="user" {if $quote_missions.tech.$tn_index.package eq 'user'} selected{/if}>User</option>*}
															</select>
														</div>
														<table>
																<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'team'}style="display:none"{/if} id="other_details_team_t{$tms_index}">
																<td>
																<div class="form-group col-md-12">
																	<!--<span style=" display: block;padding-top: 0px;">Nombre de profils : {$mission.required_writes}</span>-->
																	<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}" >
																
																	<input type="text" class="form-control validate[required]" id="team_packs_t{$tms_index}" name="team_packs_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}" onkeyup="fncalculateAutoTotal();" size="2" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}> x 		
																	
																		<span class="input-group"><input type="text" class="form-control validate[required]" id="team_fee_t{$tms_index}" name="team_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_fee|zero_cut:2}" onkeyup="fncalculateAutoTotal();" size="2"><span class="input-group-addon" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>&{$create_step1.currency};/Pack</span></span>
																	 =
																	<input  id="team_fee_ca_t{$tms_index}" name="team_fee_ca_t{$tms_index}" value="" class="color-normal" style="cursor:text;" readonly="readonly" size="2">&{$create_step1.currency};
																</div>
																	<span style=" display: block;padding-top: 0px;">
																		CA Total : 
																		<input  id="team_ca_t{$tms_index}" name="team_ca_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_package_turnover|zero_cut:2}" class=" highQuote color-normal" style="cursor:text;" readonly="readonly" size="5"> &{$create_step1.currency};
																	</span>	
																</td>
															</tr>
															<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'user'}style="display:none"{/if} id="other_details_user_t{$tms_index}">
																<td >
																<div class="form-group col-md-12">
																	<span style=" display: block;padding-top: 0px;">Nombre de profils : {$quote_missions.tech.$tn_index.required_writes}</span>
																	<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}">
																	Fees offre user : 
																	<div class="input-group">
																	<input type="text" class="form-control validate[required]" id="user_fee_t{$tms_index}" name="user_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.user_fee|zero_cut:2}"  onkeyup="fnCalUserTurnover('t{$tms_index}',{$quote_missions.tech.$tn_index.user_fee|zero_cut:2},1);" size="4" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} ><span class="input-group-addon">&{$create_step1.currency};</span>
																	</div>
																
																	<span style=" display: block;padding-top: 0px;">
																		CA Total :  
																		<input  id="user_ca_t{$tms_index}" name="user_ca_t{$tms_index}" value="" class="color-normal  highQuote" style="cursor:text;" readonly="readonly" size="5"><sup>&{$create_step1.currency};</sup>
																	</span>	

																	</div>
																</td>											
																</tr>
														</table>
														</td>

														<td class="mission-turnover col-md-2 text-right">
															<div class="input-group"  >
																<input  id="turnover_t{$tms_index}" name="turnover_t{$tms_index}" value="{$quote_missions.tech.$tn_index.turnover|zero_cut:2}" class="remove-border" readonly="readonly">&{$create_step1.currency};
																
															</div>
															 
															<div class="free-mission">
																<label class="checkbox">
																	<input type="checkbox" name="free_mission_t{$tms_index}" value="{if $quote_missions.tech.$tn_index.free_mission eq 'yes'}yes{else}no{/if}" id="free_mission_t{$tms_index}" {if $quote_missions.tech.$tn_index.free_mission eq 'yes'}checked="checked"{/if} {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} class="icheck"/>
																	<span class="free-label">Free</span>
																</label>
															</div>
														</td>
														
													</tr>

												</table>
										</div>
										</div>
									{/if}
								{/foreach}	
												
							{/if}
									{/if}
											
									{/if}
								{/foreach}							
							{/if}
							


							

				{if ""|in_array:$quote_missions.tech.linked_to_prod || "all_prod"|in_array:$quote_missions.tech.linked_to_prod}
				{assign var=keys value=$quote_missions.tech.linked_to_prod|@array_search|@array_pop}
						
							{if $quote_missions.tech.linked_to_prod|@count gt 0}

							{foreach from=$quote_missions.tech.linked_to_prod item=tmission name="tmission"}

								{assign var=tn_index value=$smarty.foreach.tmission.index}
									{assign var=tms_index value=$smarty.foreach.tmission.index+1}				
								{if ($tmission eq '') || ($tmission eq 'all_prod' && $quote_missions.tech.$tn_index.to_perform neq 'Before')}
										
									<!--{assign var=ms_index value=$smarty.foreach.misson.index+1}-->
									<div  id="mission_details_t{$tms_index}" class="{if $tmission eq ''} {else}prod_mission{/if}">	
										<div class="mission-details">								
											
											<table class="table table-bordered tech_list">		
												<tr>
												  <td class="col-md-3">
												  <div class="pull-left mission-title">
												  {if $quote_missions.tech.$tn_index.title_difference eq 'yes'}
														<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$quote_missions.tech.$tn_index.title_versions|escape|stripslashes}" data-html="true"> <i class="fa fa-bar-chart-o"></i> 
													{/if}
													{$quote_missions.tech.$tn_index.tech_type}</div>
												  <div class="pull-left grey-text" style="clear:both"> {$quote_missions.tech.$tn_index.language_name} </div>
												  </td>
												  {if $quote_missions.tech.$tn_index.tech_oneshot eq 'no'}
												  <td class="col-md-2" colspan="2">

												  <div class="text-center pull-left" style="width:50%">
												  <span class="p" id="missionlengtht_{$tms_index}">{$quote_missions.tech.$tn_index.tech_mission_length}</span>

													<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required"  style="background:#fff;">
												 
														 <div class="text-uppercase grey-text">Days</div>
													 </div>	 
													<div class="text-center pull-right " style="width:50%">
														<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
														
														<div class="text-uppercase grey-text">VOLUME</div>
														</div>
														
														<span class="col-md-12" style="border-top:1px solid #ddd;"></span>
														<div class="text-center text-uppercase" >
															<span class="col-md-12" style="padding:5px;">
															<strong>{$quote_missions.tech.$tn_index.volume_max}</strong>  <span class="grey-text">{$quote_missions.tech.$tn_index.delivery_volume_option}</span> <strong>{$quote_missions.tech.$tn_index.tempo_length}</strong> <span class="grey-text">{if $quote_missions.tech.$tn_index.tempo_length_option eq 'days'}JOURS{else}{$quote_missions.tech.$tn_index.tempo_length_option}{/if}
															</span>
														</span>
														</div>
														
														
														</div>
													</td>
												  {else}
												  <td class="col-md-1 text-center">
												  <div class="text-center">
												  <span class="p" id="missionlengtht_{$tms_index}">{$quote_missions.tech.$tn_index.tech_mission_length}</span>
													<input type="hidden"  id="mission_length_t{$tms_index}" name="mission_length_t{$tms_index}" value="{$quote_missions.tech.$tn_index.tech_mission_length}" class="input-small form-control validate[required"  style="background:#fff;">
												  </div>
														 <span class="text-uppercase grey-text">Days</span>
														 
													</td>

													<td class="col-md-1 text-center">
													<div class="text-center">
														<span class="p" id="volume_t{$tms_index}">{$quote_missions.tech.$tn_index.volume}</span>
														</div>
														<span class="text-uppercase grey-text">VOLUME</span>
													</td>
													{/if}
													<td class="col-md-1 text-center">
													
														<div class="">
														
														<input  id="unit_price_t{$tms_index}" size="5" name="unit_price_t{$tms_index}" value="{$quote_missions.tech.$tn_index.unit_price|zero_cut:2}" class="highQuote {if $quote_missions.tech.$tn_index.cost_difference eq 'yes'}new-version{/if}" readonly="readonly">
														<sup>&{$create_step1.currency};</sup>
														</div>
														<div class="text-uppercase grey-text">Selling P/art</div>
														<input  id="internal_cost_t{$tms_index}" name="internal_cost_t{$tms_index}" value="{$quote_missions.tech.$tn_index.internal_cost|zero_cut:2}" class="form-control highQuote"  type="hidden">
														{if $quote_missions.tech.$tn_index.cost_difference eq 'yes'}
														<span class="version-change pop_over" data-placement="top" data-original-title="Previous versions" data-content="{$quote_missions.tech.$tn_index.price_versions|escape|stripslashes}" data-html="true"> <span class="glyphicon glyphicon-th-list" ></span> 
														{/if}
														<!--<div class="col-md-12 text-center">
															<div class="input-group">
																<span class="input-group-addon">-</span>
															<input data-price="{$mission.unit_price|zero_cut:2}" class="form-control validate[required]" type="text" id="cost_diminish_{$ms_index}" name="cost_diminish_{$ms_index}" onkeyup="fnCalUnitPriceAndMargin('{$ms_index}',this.value);" value="0"><span class="input-group-addon">%</span>
															</div>
														</div>-->

													
													
												</td>
													<td class="col-md-1 text-center">
												<a {if $quotes.sales_review neq 'signed'} data-toggle="modal" href="" data-target="#editarticleprice" onClick="loadeditarticle('t{$tms_index}','')" {/if}>
														<div class="input-group" >
																<input type="text" readonly="readonly"  class="form-control validate[required]" id="margin_percentage_t{$tms_index}" name="margin_percentage_t{$tms_index}" onkeyup="fnCalTotalCosts('t{$tms_index}',this.value);" value="{$quote_missions.tech.$tn_index.margin_percentage}" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} style="cursor:pointer;"><span class="input-group-addon">%</span>
														</div>											
														<span class="text-uppercase grey-text">Margin</span>		
														</a>
													</td>
													
													<td class="mission-pakage col-md-3">
													<div style="display:none;">
														<select name="package_t{$tms_index}" id="package_t{$tms_index}" class="validate[required] pakage-select" onchange="updatepackage('t{$tms_index}',this.value,'{$tn_index}');" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} >
																<option value="lead" {if $quote_missions.tech.$tn_index.package eq 'lead'} selected{/if} >Lead</option>
																<option value="team" {if $quote_missions.tech.$tn_index.package eq 'team'} selected{/if}>Team</option>
																<option value="link" {if $quote_missions.tech.$tn_index.package eq 'link'} selected{/if}>Link</option>
																{*<option value="user" {if $quote_missions.tech.$tn_index.package eq 'user'} selected{/if}>User</option>*}
														</select>
													</div>
													<table>
															<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'team'}style="display:none"{/if} id="other_details_team_t{$tms_index}">
															<td>
															<div class="form-group col-md-12">
																<!--<span style=" display: block;padding-top: 0px;">Nombre de profils : {$mission.required_writes}</span>-->
																<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}">
															
																<input type="text" class="form-control validate[required]" id="team_packs_t{$tms_index}" name="team_packs_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}" onkeyup="fncalculateAutoTotal();" size="2" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}> x 		
																
																	<span class="input-group"><input type="text" class="form-control validate[required]" id="team_fee_t{$tms_index}" name="team_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_fee|zero_cut:2}" onkeyup="fncalculateAutoTotal();" size="2"><span class="input-group-addon" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>&{$create_step1.currency};/Pack</span></span>
																 =
																<input  id="team_fee_ca_t{$tms_index}" name="team_fee_ca_t{$tms_index}" value="" class="color-normal" style="cursor:text;" readonly="readonly" size="2">&{$create_step1.currency};
															</div>
																<span style=" display: block;padding-top: 0px;">
																	CA Total : 
																	<input  id="team_ca_t{$tms_index}" name="team_ca_t{$tms_index}" value="{$quote_missions.tech.$tn_index.team_package_turnover|zero_cut:2}" class=" highQuote color-normal" style="cursor:text;" readonly="readonly" size="5"> &{$create_step1.currency};
																</span>	
															</td>
														</tr>
														<tr class="misson-details-text" {if $quote_missions.tech.$tn_index.package neq 'user'}style="display:none"{/if} id="other_details_user_t{$tms_index}">
															<td >
															<div class="form-group col-md-12">
																<span style=" display: block;padding-top: 0px;">Nombre de profils : {$quote_missions.tech.$tn_index.required_writes}</span>
																<input type='hidden' name="profiles_t{$tms_index}" id="profiles_t{$tms_index}" value="{$quote_missions.tech.$tn_index.required_writer}">
																Fees offre user : 
																<div class="input-group">
																<input type="text" class="form-control validate[required]" id="user_fee_t{$tms_index}" name="user_fee_t{$tms_index}" value="{$quote_missions.tech.$tn_index.user_fee|zero_cut:2}"  onkeyup="fnCalUserTurnover('t{$tms_index}',{$quote_missions.tech.$tn_index.user_fee|zero_cut:2},1);" size="4"><span class="input-group-addon" {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if}>&{$create_step1.currency};</span>
																</div>
															
																<span style=" display: block;padding-top: 0px;">
																	CA Total :  
																	<input  id="user_ca_t{$tms_index}" name="user_ca_t{$tms_index}" value="" class="color-normal  highQuote" style="cursor:text;" readonly="readonly" size="5"><sup>&{$create_step1.currency};</sup>
																</span>	

																</div>
															</td>											
															</tr>
													</table>
													</td>

													<td class="mission-turnover col-md-2 text-right">
														<div class="input-group">
															<input  id="turnover_t{$tms_index}" name="turnover_t{$tms_index}" value="{$quote_missions.tech.$tn_index.turnover|zero_cut:2}" class="remove-border" readonly="readonly">&{$create_step1.currency};
															
														</div>
														<div class="free-mission">
															<label class="checkbox">
																<input type="checkbox" name="free_mission_t{$tms_index}" value="{if $quote_missions.tech.$tn_index.free_mission eq 'yes'}yes{else}no{/if}"  id="free_mission_t{$tms_index}" {if $quote_missions.tech.$tn_index.free_mission eq 'yes'}checked="checked"{/if} {if $user_type eq 'superadmin'  || $user_type eq 'salesmanager' || $user_type eq 'salesuser' || $user_type eq 'techuser' || $user_type eq 'techmanager'}{else}disabled="disable"{/if} class="icheck"/>
																<span class="free-label">Free</span>
															</label>	
														</div>
														
													</td>
													
												</tr>

											</table>
										</div>
									</div>	
									{/if}
								{/foreach}							
							{/if}
							{/if}		
				

			<div class="modal hide fade" id="prod_review" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			   <div class="modal-dialog " style="width:650px !important">
				<div class="modal-content">
						<div class="modal-header">
							<button class="close" data-dismiss="modal" >&times;</button>
							<h3>Challenge team</h3>
						</div>
						<div class="modal-body">
						
						<br>
							
								<div class="row">
									<div class="col-md-2">
							<input type="hidden" value="{$quotes.quote_id}" name="quote_id" />	
							<input type="hidden" value="{$quotes.currency}" name="currency" />		
									
											<img src="{$fo_path}/profiles/bo/{$userId}/logo.jpg">
										</div>
										
										<div class="col-md-10">														
											<textarea rows="3" name="quote_updated_comments" placeholder="Please detail your need" id="quote_updated_comments" class="col-md-12 form-control validate[required]" style="width:100%"></textarea>

										</div>												
									</div>			
						</div>
						<div class="modal-footer">
							<button class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" name="review_validate" class="btn btn-primary btn-fill review_validate validate" style="margin:10px;"><i class="fa fa-paper-plane"></i> Send</button>
						</div>
					</div>
				</div>
			</div>
			
		
			<div role="tabpanel" class="tab-pane hidden" id="details">
				<div class="col-md-12">
				{if $quote_missions|@count gt 0}
					{foreach from=$quote_missions item=missiondetails name="missiondetails"}
						{assign var=gn_index value=$smarty.foreach.missiondetails.index}
						{assign var=ms_index value=$smarty.foreach.missiondetails.index+1}
						{if $missiondetails.product_name} 	
						<div class="row">
							 <div class="col-md-12 pull-left miss_title">
								Mission {$ms_index}: {$missiondetails.product_name} 
							 </div>
							<table class="table table-bordered">
							<tr>
							<th class="text-uppercase">langage {if $missiondetails.product eq 'translation'} > language destination{/if}</th>
							<th class="text-uppercase">PRODUIT</th>
							<th class="text-uppercase">D&Eacute;LAI LIVRAISON</th>
							<th class="text-uppercase">Volume</th>
							<th class="text-uppercase">nb mots</th>
							</tr>
							<tr>
							<td>{$missiondetails.language_name} {if $missiondetails.product eq 'translation'} > {$missiondetails.languagedest_name}{/if}</td>
							<td>{$missiondetails.producttype_name} </td>
							<td>{$missiondetails.mission_length} JOURS</td>
							<td>{$missiondetails.volume}
							{if $missiondetails.oneshot eq 'no'}
							<p>{$missiondetails.volume_max} volume {$missiondetails.tempo_type} {$missiondetails.delivery_volume_option} {$missiondetails.tempo_length} {$missiondetails.tempo_length_option}</p>
							{/if}</td>
							<td>{$missiondetails.nb_words} </td>
							</tr>
							</table>		
						</div>
						{/if}
					{/foreach}							
				{/if}
				{if $quote_missions.tech|@count gt 0}
					{foreach from=$quote_missions.tech item=tmissiondetails name="tmissiondetails"}
						{assign var=gn_index value=$smarty.foreach.tmissiondetails.index}
						{assign var=ms_index value=$smarty.foreach.tmissiondetails.index+1}	
						{if  $tmissiondetails.tech_type}
							<div class="row">
							 <div class="col-md-12 pull-left miss_title">
								{$tmissiondetails.tech_type} 
							 </div>
							<table class="table table-bordered">
							<tr>
							<th class="text-uppercase">language </th>
							<th class="text-uppercase">PRODUIT</th>
							<th class="text-uppercase">D&Eacute;LAI LIVRAISON</th>
							<th class="text-uppercase">Volume</th>
							<th class="text-uppercase">Turnover</th>
							</tr>
							<tr>
							<td>{$tmissiondetails.language_name}</td>
							<td>{$tmissiondetails.product} </td>
							<td>{$tmissiondetails.tech_mission_length} {if $tmissiondetails.tech_mission_length_option eq 'days'}JOURS{else}$tmissiondetails.tech_mission_length_option{/if}</td>
							<td>{$tmissiondetails.volume}
							{if $tmissiondetails.tech_oneshot eq 'no'}
							<p>{$tmissiondetails.volume_max} volume {$tmissiondetails.tempo_type} {$tmissiondetails.delivery_volume_option} {$tmissiondetails.tempo_length} {$tmissiondetails.tempo_length_option}</p>
							{/if}</td>
							<td>{$tmissiondetails.turnover|zero_cut:2} </td>
							</tr>
							</table>		
						</div>
						{/if}
					{/foreach}							
				{/if}
				</div>	
			</div>							
							</div>	
						</div>		
					
			

			
					{if $user_type eq 'superadmin' || $user_type eq 'salesmanager' || $user_type eq 'salesuser'}
					<div class="card">
						<div class="content">
					
						<div class="row">
<div class="col-md-2 text-center">
	<br><br><br><i style="font-size: 72px" class="material-icons">group_add</i>
</div>
							<div class="col-md-10">
								<h4>Challenge a team<br><small>Didn't get any prices for 1 or several missions ? Please select the right team to challenge and <strong>save your quote</strong></small></h4>
							<label class="checkbox"><input type="checkbox" class="icheck send_team"  value="prod" name="send_team_prod"></i> Editorial team</label>				
							<label class="checkbox"><input type="checkbox" class="icheck send_team"   value="tech" name="send_team_tech"><i class="glyphicon glyphicon-hand-paper-o"></i> Technical team</label>	
							
							
							<label class="checkbox"><input type="checkbox" class="icheck send_team"  value="seo" name="send_team_seo"><i class="glyphicon glyphicon-hand-paper-o"></i> Content strategist</label>		
						</div>
					</div></div></div>
						<!--<a  data-target="#prod_review" class="btn btn-default submit-sales"><i class="glyphicon glyphicon-hand-paper-o"></i> Save quote</a>			

						<a  data-target="#tech_review" class="btn btn-default submit-sales"><i class="glyphicon glyphicon-hand-paper-o"></i> Technical team</a>	
					
						<a  data-target="#seo_review" class="btn btn-default submit-sales"><i class="glyphicon glyphicon-hand-paper-o"></i> Content strategist</a>-->
					{/if}
					</form>
					<hr>

					<div class="text-center">
					{if $quotes.sales_review neq 'signed'}
					<a href="/quote-new/create-quote-mission-view?qaction=briefing&quote_id={$quotes.quote_id}" class="btn btn-default btn-lg pull-left"><i class="glyphicon glyphicon-chevron-left"></i> Catch prices</a>		
						{else}		
						<a href="/quote-new/client-brief?qaction=briefing&quote_id={$quotes.quote_id}" class="btn btn-default btn-lg pull-left"><i class="glyphicon glyphicon-chevron-left"></i> Customer pitch</a>
					{/if}
					{if $user_type eq 'superadmin' || $user_type eq 'salesmanager' || $user_type eq 'salesuser'}
						{if $quotes.sales_review neq 'signed' && $quotes.sales_review neq 'validated'}
						<button class="btn btn-success btn-lg btn-fill review_validate validate" type="button">Save quote</button>
						<a  data-target="#prod_review" id="popupshow" class="btn btn-success btn-lg btn-fill hidden" type="button"> Save quote</a>
						{/if}
						<div class="btn-group {if $quotes.estimate_sign_date eq ""} hidden{else} {/if}">
							<a href="/quote-new/download-quote-xls?quote_id={$quotes.quote_id}" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-download"></i> Download xlsx (&euro;)</a>
							<a data-toggle="dropdown" class="btn btn-default btn-lg dropdown-toggle" href=""><i class="glyphicon glyphicon-chevron-down"></i></a>
							<ul class="dropdown-menu">
									<li><a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#change-currency" href="/quote-new/change-quote-currency?quote_id={$quotes.quote_id}">Change the currency</a></li>
							</ul>
						</div>						
						{if $quotes.sales_review neq 'signed'}
						<button class="btn btn-fill btn-primary btn-lg pull-right {if $sent_button eq 'hide' || $quotes.sales_review eq 'validated'} hidden{else} {/if}" id="saveFinal" type="submit">Move to sent</a>
						{/if}
					{else if $user_type eq 'multilingue' || $user_type eq 'prodsubmanager' || $user_type eq 'prodmanager' || $user_type eq 'seouser' || $user_type eq 'seomanager' || $user_type eq 'techuser' || $user_type eq 'techmanager'}
						{if $quotes.sales_review neq 'signed' && $quotes.sales_review neq 'validated'}
						<button class="btn btn-success btn-fill btn-lg {if $quotes.sales_review eq 'signed'} hidden{/if}" type="submit" onclick="$('#save_final_validation').submit(); return false;">Save quote</button>
						{/if}
						<a class="btn btn-default btn-lg {if $quotes.prod_extra_launch_days eq "" || $quotes.estimate_sign_date eq ""} hidden{else} {/if}" href="/quote-new/download-quote-xls?quote_id={$quotes.quote_id}"><i class="fa fa-file-excel-o"></i> Download quote</a>
					{/if}
					{if $quotes.sales_review eq 'signed'}
							{if $quotes.signed_exist eq '1'}
								<a href="/contractmission/contract-edit?contract_id={$quotes.signed_contractid}" class="btn btn-fill btn-primary btn-lg pull-right">See contract</a>
							{else}
								<a href="/contractmission/create-contract?quote_id={$quotes.quote_id}" class="btn btn-fill btn-success btn-lg pull-right">Create contract</a>	
							{/if}													
					{/if}

				</div>

		</div>	


<!-- end of the list -->



		<div class="modal hide fade" id="delivery_time_calc_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" >&times;</button>
				<h3>Outil  de calcul de d&eacute;lai de livraison</h3>
			</div>
			<div class="modal-body">		
			</div>
			<div class="modal-footer">
			</div>
		</div>		
		</div>
	</div>
</div>

<div class="popover-markup"> 
				<div id="popover-head" class="hide head"><h3 class="popover-title">Add a sub mission</h3></div>
				<div id="popover-content" class="hide"><form name="autureForm" id="autureForm"><label>nb of writers</label>
				          <div class="text-center">
				          <input type="text" name="autrewriter" id="autrewriter" class="validate[required]" value="" />
				          <input type="hidden" name="autrecurrency" id="autrecurrency"  value="{$quotes.currency}" />
				          </div>
				           <label>Cost</label>
				          <div>
				          <input type="text"  name="sub_mission_cost" id="sub_mission_cost" size="5" value=""  class="validate[required]" />
				          <strong>&{$quotes.currency};</strong>
				          </div>
				          <div class="text-center">
				          <button type="button" class="btn btn-primary btn-fill btn-xs text-uppercase" id="add_costoversubmit">Validate</button>
				          </div></form>
				  </div>
			</div>
	





 
