<div style="padding-left:6px;padding-top:52px;padding-bottom:30px;">
	<b>The mission was successfully created. It is online www.edit-place.com and accessible now.</b>
</div>

<br>

{if $duplicate=="yes"} 
	<button type="submit" value="Dupliquer cette mission" class="btn btn-info" onClick="window.location='/ao/ao-create1?submenuId=ML2-SL3'" >Duplicate this mission</button>&nbsp;&nbsp;
	<button type="submit" value="New AO" class="btn btn-info" onClick="window.location='/ao/ao-create1?submenuId=ML2-SL3&delsession=1'" >New AO</button>
{/if}