{literal}
<script>
	$(document).ready(function() {
		$('#pollconfiguration').dataTable({
			"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"aaSorting": [[ 0, "asc" ]],
			"aoColumns": [
				{ "sType": "formatted-num" },
				{ "sType": "string" },
				{ "sType": "string" },
				{ "sType": "natural" }
			]

		});
	});	
	
	function editquestion(ques)
	{
		var target_page = "/ao/questionedit?quesid="+ques;

		$.post(target_page, function(data){ 
			$("#editquestioncontent").html(data);
		});
	}		
		
	function deletequestion(ques)
	{
		if(confirm("Do you really want to delete the question?"))
		{
			var target_page = "/ao/questiondelete?quesid="+ques;

			$.post(target_page, function(data){ 
				smoke.alert("Deleted successfully !!");
				window.location="/ao/pollconfiguration?submenuId=ML2-SL23";
			});
		}
	}	
		
</script>

{/literal}
	<div class="row-fluid">
  		<div class="span12">
			<h3 class="heading">Quote Configuration</h3>
			<div align="right" style="padding-bottom:10px;">
				<input type="button" class="btn btn-info" onClick="window.location='/ao/smicconfigure?submenuId=ML2-SL23';" value="SMIC / COUNTRY" />
				<input type="button" class="btn btn-info" onClick="window.location='/ao/categorydifficulty?submenuId=ML2-SL23';" value="% of difficulty / category" />
				<input type="button" class="btn btn-info" data-toggle="modal" data-target="#editquestion" name="add_question" id="add_question"  onClick="editquestion();" value="Add a question" />
			</div>	
			
			<table id="pollconfiguration" class="table table-bordered table-striped table_vam" style="text-align:left">
				<thead>
					<tr>
					  <th>SI</th>
					  <th>Question</th>
					  <th>Type of response expected</th>
					  <th>Action</th>
					</tr>
				</thead>
				<tbody>
				{foreach from=$pquestionlist item=ques name=quesloop}
					<tr>
					   <td>{math assign="loopindex" equation='x+1' x=$smarty.foreach.quesloop.index} {$smarty.foreach.quesloop.index+1}</td>
					   <td style="text-align:left">{$ques.title|stripslashes|wordwrap:15:"\n":true}</td>
					   <td>{$ques.type}</td>
					   <td>
							<a data-toggle="modal" data-target="#editquestion" href="javascript:void(0);" onclick="editquestion('{$ques.id}');"><i class="splashy-application_windows_edit"></i></a>
							<a href="javascript:void(0);" onclick="deletequestion('{$ques.id}');"><i class="splashy-remove"></i></a>
						</td>
					</tr>
				{/foreach}
				</tbody>
			</table>
		</div>
	</div>
	
	<!--Edit question-->
	<div class="modal hide fade" id="editquestion">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Add Question</h3>
		</div>
		<div class="modal-body" id="editquestioncontent">
		</div>
		<div class="modal-footer">
		</div>
	</div>
