{literal}
<script type="text/javascript" charset="utf-8" src="/BO/script/datempicker.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		optiontext();
	});
	var counter = $("#editcounter").val();
	
	if(counter=="")
		counter = 1;
		
	function optiontext()
	{
		var opt = $("#type").val();
		
		if(opt=='price')
			$("#typeinfo").html("The expected response is an amount (in euros).");
		else if(opt=='bulk_price')
			$("#typeinfo").html('The expected response is an amount (in euros) after reduction to give a wholesale price \ 's there are several items. This type of question should be related to a matter of "price" type when creating the quote.');
		else if(opt=='range_price')
			$("#typeinfo").html('The expected response will be an amount (in euros) between two amounts defined when creating the quote.');
		else if(opt=='timing')
			$("#typeinfo").html('The expected response is a time in days, hours or minutes, parameter set when creating the quote. This type of question should be related to a matter of "price" or "wholesale price" when creating the quote.');
		else if(opt=='radio')
			$("#typeinfo").html('The expected answer is to select from the list of answers you need to define below (only one choice is possible for the contributor).');
		else if(opt=='checkbox')
			$("#typeinfo").html('The/the expected response (s) will check from a list of answers you need to define below (multiple choices are possible for the contributor).');
	}
	
	function showoptions()
	{ 
		var opt = $("#type").val();
		
		optiontext();
			
		if(opt == 'radio' || opt == 'checkbox')
		{
			$("#TextBoxesGroup").show();
			
			var fldtext = '<div id="TextBoxDiv2"><input type="text" name="option[]"/></div>';
			$("#option_block").show();
			$("#TextBoxesGroup").html(fldtext);
		}
		else
		{
			$("#TextBoxesGroup").hide();
		}
	}
	
	function loadoptions()
	{
		//var cnt = $("#noofoptions").val();
		
		var fldtext = '';
		
		/*for(var i=1; i<=cnt; i++)
		{*/
			fldtext+='<div id="TextBoxDiv2"><input type="text" name="option[]"/></div>';
		//}
		$("#option_block").show();
		$("#TextBoxesGroup").html(fldtext);
	}
	
	function addfield()
	{
		if (counter > 10) {
                alert("Only 10 textboxes allowed");
                return false;
            }
            $('<div/>',{'id':'TextBoxDiv' + counter})
            .append( $('<input type="text" name="option[]">') )
            .appendTo( '#TextBoxesGroup' )       
            counter++;
	}
	
	function removefield()
	{
			if (counter == 1) {
                alert("No more textbox to remove");
                return false;
            }
            
            $("#TextBoxDiv" + counter).remove();
			counter--;
	}
</script>

{/literal}	

	<form action="/ao/pollconfiguration?submenuId=ML2-SL23" name="pollconfig_form_step{$smarty.foreach.quesloop.index+1}" method="post"  >
		<table align="center" width="100%" cellpadding="4" cellspacing="4" style="padding:10px">
		<tr>
			<td valign="top" width="15%" colspan="2">Title of the question</td>
		</tr>
		<tr>	
			<td colspan="2">
				<textarea name="title" rows="3" class="span5" placeholder="Entrer your question...">{$quesdetail[0].title|stripslashes|utf8_encode}</textarea>
			</td>
		</tr>
		<tr>
			<td colspan="2">Type of reponse expected</td>
		</tr>
		<tr>		
			<td colspan="2">
				<select name="type" id="type" onChange="showoptions();" >
					<option value="price" {if $quesdetail[0].type=="price"}selected{/if}>Price</option>
					<option value="bulk_price" {if $quesdetail[0].type=="bulk_price"}selected{/if}>Wholesale price</option>
					<option value="range_price" {if $quesdetail[0].type=="range_price"}selected{/if}>Price Range</option>
					<option value="timing" {if $quesdetail[0].type=="timing"}selected{/if}>Duration</option>
					<option value="radio" {if $quesdetail[0].type=="radio"}selected{/if}>Radio buttons</option>
					<option value="checkbox" {if $quesdetail[0].type=="checkbox"}selected{/if}>Checkboxes</option>
					<!--<option value="calendar" {if $quesdetail[0].type=="calendar"}selected{/if}>Calendar</option>-->
				</select>
			</td>
		</tr>
		<tr>
			<td id="typeinfo" colspan="2">
				The expected response is an amount (in euros).
			</td>
		</tr>
		<tr id="option_block" {if $quesdetail[0].type!="radio" && $quesdetail[0].type!="checkbox"}style="display:none;"{/if}>	
			<td valign="top">Options</td>
			<td>
				<div id="TextBoxesGroup">
					{if $quesdetail[0].optionlist|@count>0}
						{foreach from=$quesdetail[0].optionlist item=opt name=optloop}
						{math assign="loopindex" equation='x+1' x=$smarty.foreach.optloop.index} 
							<div id="TextBoxDiv{$loopindex}">
								<input type="text" name="option[]" value="{$opt|utf8_encode}" />
							</div>
						{/foreach}
						<input type="hidden" name="editcounter" id="editcounter" value="{$quesdetail[0].optionlist|@count}" />
					{/if}
				</div>
				<a href="javascript:void(0);" class="hint--bottom hint--info" data-hint="Add Option" onClick="addfield();"><i class="splashy-add"></i></a>&nbsp;
				<a href="javascript:void(0);" class="hint--bottom hint--info" data-hint="Remove Option" onClick="removefield();"><i class="splashy-remove"></i></a>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td style="float:right">&nbsp; <samp id="222"><input type="submit" name="submit_config" id="submit_config" value="Add"  class="btn btn-info" /></samp> </td>
		</tr>
		</table>
		<input type="hidden" name="quesid" id="quesid" value="{$quesdetail[0].id}"/>
	</form>
