{literal}
<script type="text/javascript">
    $(document).ready(function() {
		
        $('#user_type_error').hide();
        $('#rank_error').hide();
        $('#lang_error').hide();
        $('#status_error').hide();

        $('#search_submit').click(function(){
            var usertype=$('#user_type').val();
            var rank=$('#rank').val();
            var lang=$('#lang').val();
            var status=$('#status').val();
			
            var flag = 0;

            if(!usertype){
                $('#user_type_error').show();
                flag=1;
            }
            if(!rank){
                $('#rank_error').show();
                flag=1;
            }
            if(!lang){
                $('#lang_error').show();
                flag=1;
            }
            if(!status){
                $('#status_error').show();
                flag=1;
            }
            if (flag == 0) {
                $('#search_form').submit();
            }

        });
    });
</script>
{/literal}
   <form id="search_form" action="check" method="post" role="form">
    <div >
        <label>User Type</label>
        <select name="user_type[]" id="user_type" class="chzn_a span8" multiple="multiple">
            <option value="">Select User Type</option>
            <option value="writer">Writer</option>
            <option value="corrector">Corrector</option>
            <option value="translator">Translator</option>
        </select>
        <span id="user_type_error">Reqired</span>
    </div>
    <div >
        <label>Rank</label>
        <select name="rank[]" id="rank" class="chzn_a span8" multiple="multiple">
            <option value="">Select Rank</option>
            <option value="senior">Senior</option>
            <option value="junior">Junior</option>
            <option value="3">Sub Junior</option>
        </select>
        <span id="rank_error">Reqired</span>
    </div>
    <div >
        <label>Language</label>
        <select name="lang[]" id="lang" class="chzn_a span8" multiple="multiple">
            <option value="">Select Language</option>
            {foreach from=$ep_lang key=name item=value}
            <option value="{$name}">{$value}</option>
            {/foreach}
        </select>
        <span id="lang_error">Reqired</span>
    </div>
    <div >
        <label>Status</label>
        <select name="status[]" id="status" class="chzn_a span8" multiple="multiple">
            <option value="">Select Status</option>
            <option value="1">Active</option>
            <option value="2">Inactive</option>
        </select>
        <span id="status_error">Reqired</span>
    </div>
    <div >
        <button type="button" name="search_submit" id="search_submit">Search</button>
    </div>
</form>