{literal}
<script language="JavaScript">
function getHTTPObject() {
  var xmlHttp;
  try{
    // Firefox, Opera 8.0+, Safari
    xmlHttp=new XMLHttpRequest();
    }
  catch (e){
    // Internet Explorer
    try{
      xmlHttp=new ActiveXObject("Msxml2.XMLHTTP");
      }catch (e){
        try{
        xmlHttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
      catch (e){
        alert("Your browser does not support AJAX!");
        return false;
        }
      }
    }
    return xmlHttp;
  }

var commentload = getHTTPObject();
var site = document.domain;

function searchpage(formname,pagename)
{      
    var param = 'formname='+formname+'&pagename='+pagename;
    
    if(pagename == '')
    {
        alert("Please enter page name");
        return false;
    }
    
    if(formname == 'process')    
    commentload.open("POST",'https://'+site+'/process/searchpage', true);
    
    if(formname == 'processdaco')    
    commentload.open("POST",'https://'+site+'/processdaco/searchpage', true);
    
    if(formname == 'processmanage')    
    commentload.open("POST",'https://'+site+'/processmanage/searchpage', true);

    if(formname == 'processeditplace')    
    commentload.open("POST",'https://'+site+'/processeditplace/searchpage', true);
        
    commentload.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    commentload.setRequestHeader("Content-length", param.length);
    commentload.setRequestHeader("Connection", "close");
    commentload.onreadystatechange = function()
    {
        if (commentload.readyState == 4)
        {
            results = commentload.responseText;
            document.getElementById('cpage').innerHTML='SegmentName => '+results;
        }
        else if(commentload.readyState == 1)
        {
            document.getElementById('cpage').innerHTML="<img src='/image/toggle/datloader.gif'>";
        }
    };
    commentload.send(param);
}

function changeprocss(elementRef,site)
{
	var selectedIndex = elementRef.selectedIndex;
	if(selectedIndex == 1)
		document.location.href="https://"+site+"/process/page?domainSel=1";
	else if(selectedIndex == 2)
		document.location.href="https://"+site+"/processdaco/page?domainSel=2";
	else if(selectedIndex == 3)
		document.location.href="https://"+site+"/processmanage/page?domainSel=3";
	else if(selectedIndex == 4)
		document.location.href="https://"+site+"/processeditplace/page?domainSel=4";
}
</script>
{/literal}
<center><font color="red"><h2>{$fail_update}</h2></font></center>
<form method="get" name="sitechange">
<input type="hidden" name="domainSel" value="{$domainSel}" />
<input type="text" size="25" name="pagecheckit" id="pagecheckit"/>&nbsp;&nbsp;<input type="button" class="button" size="25" onclick="javascript:searchpage('{$controllerName}',document.getElementById('pagecheckit').value);" value="%Search% Page" name="btnPagecheckit"/>&nbsp;<span id="cpage" style="font: bold italic 14px/1.2 Georgia, sans-serif;"></span>
<div class="divLn"></div>
<div class="tAlignCenter">
<input type="hidden" id="procss" name="procss" value="indexDoc" />
<div align="center" class="nbredocs">
<span class="txtcourant">Select Site :</span>
<select name="domain" id="domain" class="button" onChange="javascript:changeprocss(this,'{$siteName}');">
<option>None</option>
<option value="1" {if $domainSel eq '1'} selected{/if}>Process Oboulo</option>
<option value="2" {if $domainSel eq '2'} selected{/if}>Process Dacodoc</option>
<option value="3" {if $domainSel eq '3'} selected{/if}>Process Management</option>
<option value="4" {if $domainSel eq '4'} selected{/if}>Edit-Place</option>
</select>
</div>
</form>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<form action="page" method="get" name="doFilter">
<input type="hidden" name="domainSel" value="{$domainSel}" />
<input type="hidden" name="action" value="indexDoc" />
<div align="center" class="nbredocs">
<span class="txtcourant">Select Segment :</span>
<select name="segment" class="button" onChange="doFilter.submit()">
{html_options options=$segmentList selected=$segment}
</select>
&nbsp;&nbsp;&nbsp;<span class="txtcourant"><a target="_blank" href="https://{$siteName}/process/arrayindex?arrayName={$segmentArrayName}&fileName=process.php">Create Segment</a></span>
</div>
</form>
</div>
<div class="divLn"></div>
<div class="divLn"></div>
<div class="fondTitle">PAGE MANAGMENT</div>
<table width="100%">
<tr class="fondtitre2">
<td width=10></td>
<td class="txtcourant" align="center">Name</td>
<td width=10></td>
<td class="txtcourant" align="center">Description</a></td>
<td width=10></td>
<td class="txtcourant" align="center">Pattern</a></td>
<td width=10></td>
<td class="txtcourant" align="center">Meta Details</a></td>
<td width=10></td>
<td class="txtcourant" align="center">ProcessCode</a></td>
<td width=10></td>
<td class="txtcourant" align="center">Section</a></td>
<td width=10></td>
<td class="txtcourant" align="right">Edit</a></td>
</tr>
{foreach from=$pageList item=p}
	<tr class="{cycle values="couleurpanier,txtcourant"}"  height="30">
		<td width="10"></td>
		<td>
			<span class="txtcourant"><a href="module?mod={$p->getNodeName()}" class="nbredocs">{$p->getNodeName()}</a></span>
		</td>
		<td width="10"></td>
		<td>
			<span class="txtcourant">{$p->getNodeValue()|utf8_decode}</span>
		</td>
		<td width="10"></td>
		<td>
		<!-- 	<span class="txtcourant">
			<a href="pattern?pat={$p->getPatterns()}" class="nbredocs">{$p->getPatterns()}</a>
			</span>
		 -->
		 	{assign var='pageList2' value=$p->getPatterns()}
		 	{if $pageList2|strpos eq 'false'}
		 	<span class="txtcourant">
			<a href="pattern?pat={$p->getPatterns()}" class="nbredocs">{$p->getPatterns()}</a>
			</span>
			{else}
			{assign var=pageListArr value="|"|explode:$pageList2} 
		 	{foreach from=$pageListArr item=p3}
		 	<span class="txtcourant">
			<a href="pattern?pat={$p->getPatterns()}" class="nbredocs">{$p->getPatterns()}</a><div style="height:5px;line-height:5px;" class="divLn"></div>
			</span>
			{/foreach}
			{/if}
		</td>
		</td>
		<td width="10"></td>
		<td>
			<span class="txtcourant"><a href="javascript:xpopen('metadetail?metaDescr={$p->getmetaDescription()}&metaKeywords={$p->getmetaKeywords()}&metaTitle={$p->getmetaTitle()}',900,400)" class="nbredocs">Meta Details</a></span>
		</td>
		<td width="10"></td>
		<td  align="center">
			<span class="txtcourant">{$p->getprocessCode()} <font style="color:red;">|</font> {$p->getaccessCode()}</span>
		</td>
		<td width="10"></td>
		<td>
			<span class="txtcourant">{assign var='j' value=$p->getsection()}{$sectionList.$j}</span>
		</td>
		<td width="10"></td>
		<td align="right" height="19" width="50">
			<a href="?page={$p->getNodeName()}&do=update&segment={$segment}#page" ><img height="19" width="20" src="/image/picto/edit.png" border="0" title="%Edit_array%" alt="%Edit_array%"/></a>
			<a href="?page={$p->getNodeName()}&do=delete&segment={$segment}" ><img height="16" width="16" src="/image/delete.gif" border="0" title="%Delete_array%" alt="%Delete_array%"/></a>
		</td>
	</tr>
{/foreach}
</table>
<div class="divLn"></div>
<div class="divLn"></div>
<form action="page" method="get" id="page" onSubmit="return checkformmodulesite();">
<input type="hidden" name="domainSel" value="{$domainSel}" />
<input type="hidden" name="do" value="add"/>
<input type="hidden" name="update_check" value="{$update_check}"/>
<input type="hidden" name="segment" value="{$selectedPage->getSegment()}"/>
<table class="profitTable" align="center" width="100%">
<tr><td align="center" colspan="20" class="fondtitre2">ADD PAGE</td></tr>
<tr class="couleurpanier" height="38">
<td width="10"></td>
<td class="txtcourant" align="center">Name</td>
<td width="10"></td>
<td class="txtcourant" align="center">Description</td>
<td width="10"></td>
<td class="txtcourant" align="center">Segment</td>
<td width="10"></td>
<td class="txtcourant" align="center">Pattern</td>
<td width="10"></td>
<td class="txtcourant" align="center">Code</td>
<td width="10"></td>
<td class="txtcourant" align="center">Section(Admin only)</td>
<td width="10"></td>
<td align="center"></td>
</tr>
<tr class="couleurpanier" height="38">
<td width="10"></td>
<td class="txtcourant" align="center"><input type="text" size="20" name="page" id="page" value="{$selectedPage->getNodeName()}" onblur="checkpageexistence(this.value,'{$siteName}/{$controller}')" class="required"><div id="code1" class="validation-advice"><span class="form-row"></span></div></td>
<td width="10"></td>
<td class="txtcourant" align="center" ><input type="text" size="20" name="description" value="{$selectedPage->getNodeValue()|utf8_decode}" /></td>
<td width="10"></td>
<td><select name="segment" class="button">
{html_options options=$segmentList selected=$selectedPage->getSegment()}
</select></td>
<td width="10"></td>
<td>
<select name="selectPattern[]" id="selectPattern" multiple="multiple" class="buttonMultiple" style="height:75px;width:200px;">
 {html_options values=$patternList selected=$selectedPage->getPatternsasarray() output=$patternList}
<!--{foreach from=$patternList item=page}
				<option value="{$page}">{$page}</option>
			{/foreach} -->
</select></td>
<td width="10"></td>
<td class="txtcourant" align="center"><input type="text" size="02" name="processCode" value="{$selectedPage->getprocessCode()}" title="Enter Number like 0,1,2 etc"/> <input type="text" size="02" name="accessCode" value="{$selectedPage->getaccessCode()}" title="Enter Number like 0,1,2 etc"/></td>
<td width="10"></td>
<td><select name="section" class="button" title="For Admin only">
			{html_options options=$sectionList selected=$selectedPage->getsection()}
		</select></td>
<td width="10"></td>		
</tr>
</table>
<table class="profitTable" align="center" width="100%">
<tr class="couleurpanier" height="38">
<td class="txtcourant" align="center">MetaTitle </td>
<td class="txtcourant" align="center" ><input type="text" size="135" name="metaTitle" value="{$selectedPage->getmetaTitle()}" /></td>
</tr>
<tr class="couleurpanier" height="38">
<td class="txtcourant" align="center">MetaKeyword </td>
<td class="txtcourant" align="center" ><input type="text" size="135" name="metaKeywords" value="{$selectedPage->getmetaKeywords()}" /></td>
</tr>
<tr class="couleurpanier" height="38">
<td class="txtcourant" align="center">MetaDescription </td>
<td class="txtcourant" align="center" ><input type="text" size="135" name="metaDescription" value="{$selectedPage->getmetaDescription()}" /></td>
</tr>
</table>
<div class="divLn"></div>
<center>
<input type="submit" name="ajouter" value="Submit" class="button"></center>
</form>
{literal}
<script type="text/javascript">
	function formCallback(result, form)
	{
		window.status = "valiation callback for form '" + form.id + "': result = " + result;
	}
	var valid = new Validation('page', {immediate : true, onFormValidate : formCallback});
</script>
{/literal}
<div class="divLn"></div>
