{literal}
<script type="text/javascript">
$(document).ready(function(){
    
  $("#toggle-notofication").click(function(){
    $("#activities").addClass('show');
  });

  $("#clearActivities").click(function(){
    $("#activities").removeClass('show');
  });
  
});
</script>

{/literal}

<div class="container-fluid">  

	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		
	</div>
	<a class="brand" href="#"><img src="/BO/theme/lbd/img/workplace-logo.svg" width="130"></a>
	<div class="collapse navbar-collapse">       
		
		<!--<a id="menu-toggle" class="btn btn-default" href="#menu-toggle">Toggle Menu</a>-->
		  
		<ul class="nav navbar-nav navbar-right">
		<li>
				<!-- toggle to show activation -->
				<a id="toggle-notofication"><i class="material-icons" >notifications_active</i></a>
			</li>
				
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					 <img src="{$fo_path}profiles/bo/{$userId}/logo.jpg?123" alet="{$loginName}" width="32" height="32"/> <b class="caret"></b>
					</a>
	
				<ul class="dropdown-menu">
					<li><a href="/user/profile-edit?tab=profileedit">Modify Profile</a></li>
						<li><a href="/index/logout">Log Out</a></li>
					
				</ul>
			</li>

			
		</ul>
	</div>
</div>
