<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Ebookers - Weekly report</title>
	<link rel="stylesheet" href="{$baseurl}/BO/theme/ebooker-report/stylesheets/app.css" />
</head>
<body>
	<!--///////////////////////////// THIS IS THE HEADER \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
	<header>
		<div class="row">
			<img class="hide-for-print"  src="{$baseurl}/BO/theme/ebooker-report/images/eb-logo-header.png" alt="">
			<img class="print-only"  src="{$baseurl}/BO/theme/ebooker-report/images/eb-logo-header-print.png" alt="">
			<h1>Weekly report</h1>			
			
			{if $type neq 'html'}
				<form name="language_report" method="GET">
					<select name="language" style="height: 30px; margin-left: 30px; margin-top: 14px; width: 250px;" onchange="this.form.submit();">						
						{html_options options=$languages selected=$language_selected}
					</select>
				</form>	
			{/if}	
				
			
			{if $type eq 'html'}				
				<a href="http://clients.edit-place.com/excel-devs/ebookers/weekly-report.php?download=xlsx&language={$language_selected}" style="float:right;color:#FFF"><span>Download XLSX</span></a>
			{/if}	
			
			
		</div>
	</header>
	<!--////////////////////////////////// HEADER END \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

	<!--///////////////////////////// MAIN STAT CONTENT \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
	<div class="row" >
		<div class="projectWrapper">
			<div class="projectComplete">
				<h4>Project achievement</h4>
				<div class="chartDisplay">
					<span class="chart" data-percent="{$completion_percentage}">
						<span class="percent"></span>
					</span>
					<span>
					{$total_intergrated_count} stencils are integrated over {$total_stencils_count}
					</span>
				</div>
			</div>
		</div>

		<div class="dataWrapper">
			<ul class="statsDisplay">
				<li class="stat1">
					<div class="statWrapper">
						<div class="small-4 columns">
							<i class="fa fa-pencil"></i>
						</div>
						<div class="small-8 columns">
							<span class="stencilsCount">
							{$total_written_count}
								<span class="stencilType">
									written stencils
								</span>	
							</span>
						</div>
					</div>
					<div class="wordCount">
						{$total_written_words} words
					</div>									
				</li>
				<li class="stat2">
					<div class="statWrapper">
						<div class="small-4 columns">
							<i class="fa fa-eye"></i>
						</div>
						<div class="small-8 columns">
							<span class="stencilsCount">
								{$total_proofreaded_count}
								<span class="stencilType">
									Proofreaded stencils
								</span>	
							</span>
						</div>
					</div>
					<div class="wordCount">
						{$total_proofreaded_words} words
					</div>									
				</li>				
				<li class="stat3">
					<div class="statWrapper">
						<div class="small-4 columns">
							<i class="fa fa-check"></i>
						</div>
						<div class="small-8 columns">
							<span class="stencilsCount">
							{$total_validated_count}
								<span class="stencilType">
									Validated stencils
								</span>	
							</span>
						</div>
					</div>
					<div class="wordCount">
						{$total_validated_words} words
					</div>									
				</li>				
				<li class="stat4">
					<div class="statWrapper">
						<div class="small-4 columns">
							<img src="{$baseurl}/BO/theme/ebooker-report/images/eb-logo-small.png" alt="">
						</div>
						<div class="small-8 columns">
							<span class="stencilsCount">
								{$total_intergrated_count}
								<span class="stencilType">
									Integrated stencils
								</span>	
							</span>
						</div>
					</div>
					<div class="wordCount">
						{$total_integrated_words} words
					</div>									
				</li>
			</ul>
		</div>
	</div>

	<!--/////////////////////////// STATS TABLE STARTS HERE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

	<div class="row tableStats">
		<table cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<th colspan="6" >Split per category</th>
				</tr>
			</thead>
			<tbody>
				<tr class="tableSummary">
					<td>Category</td>
					<td>Stencils</td>
					<td>Written</td>
					<td>Proof readed</td>
					<td>Validated</td>
					<td>Integrated</td>
				</tr>
				{if $themeStencilsDetails|@count > 0}
					{foreach from=$themeStencilsDetails item=theme}
						<tr>
							<td>{$theme.theme_name}</td>				
							<td>{if $theme.stencils_count}{$theme.stencils_count}{else}-{/if}</td>
							<td>{if $theme.written_stencils_count}{$theme.written_stencils_count}{else}-{/if}</td>
							<td>{if $theme.proofread_stencils_count}{$theme.proofread_stencils_count}{else}-{/if}</td>
							<td>{if $theme.validated_stencils_count}{$theme.validated_stencils_count}{else}-{/if}</td>	
							<td>{if $theme.integrated_count}{$theme.integrated_count}{else}-{/if}</td>				
						</tr>
					{/foreach}
				{/if}															
			</tbody>
		</table>
	</div>

	<!--////////////////////////////// END STATS DISPLAY \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->



	<!--//////////////////////// FOOTER AREA WITH DOWNLOAD BTN\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
	<footer>
		<div class="row">
			<a href="#" data-reveal-id="dlModal" class="dlCta"><i class="fa fa-download"></i><span>Download datas</span></a>
		</div>
		<div class="row">			
			<img src="{$baseurl}/BO/theme/ebooker-report/images/ep-logo.png" alt="">
		</div>
	</footer>
	<!--/////////////////////////////  END FOOTER AREA \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->


	<!--/////////////////////////////  FILE EXPORT MODAL \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
	<div id="dlModal" class="reveal-modal full" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">

	<!--//////////////////////////  1ST STEP FILE TYPE EXPORT \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

		<div class="columns fileSelection">
			<h2 id="modalTitle">Download your datas</h2>
			<h3>Please select your outpout format</h3>
			<ul class="outputFileList">
				<li>
					<a href="/ebookers/download-report?type=pdf&language={$language_selected}">
						<i class="fa fa-file-pdf-o"></i>
						<span>pdf</span>
					</a>
				</li>
				<li>
					<a href="/ebookers/download-report?type=xlsx&language={$language_selected}">
						<i class="fa fa-file-excel-o"></i>
						<span>excel</span>
					</a>
				</li>
				<!--<li>
					<a href="">
						<i class="fa fa-file-text-o"></i>
						<span>csv</span>
					</a>
				</li>-->
			</ul>				
		</div>

	<!--//////////////////////////  2ND STEP FILE EXPORT LOADING \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

		<!-- <div class="columns fileCurrentDl">
			<svg class="spinner" width="65px" height="65px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
				<circle class="path" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
			</svg>
			<span>Processing Download</span>
		</div> -->

	<!--//////////////////////////  3RD STEP FILE DL SUCCESS \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->

		<!-- <div class="columns dlSuccess">
			<i class="fa fa-thumbs-o-up"></i>
			<h3>Your file has successfully been exported !</h3> 
		</div> -->

	<!--//////////////////////////  3RD STEP FILE DL ERROR \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
		<!-- <div class="columns dlError">
			<i class="fa fa-times"></i>
			<h3>Oops sorry, something went wrong...<br>Please try again or contact our <a href="mailto:support@edit-place.com">support team</a></h3> 
		</div> -->
		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
	</div>
	<script src="{$baseurl}/BO/theme/ebooker-report/js/jquery.min.js"></script>
	<script src="{$baseurl}/BO/theme/ebooker-report/js/foundation.min.js"></script>
	<script src="{$baseurl}/BO/theme/ebooker-report/js/app.js"></script>	
	<script src="{$baseurl}/BO/theme/ebooker-report/js/jquery.easing.min.js"></script>
	<script src="{$baseurl}/BO/theme/ebooker-report/js/jquery.easypiechart.min.js"></script>
	{literal}	
	<script>
		$(function() {
			$('.chart').easyPieChart({
				easing: 'easeOutBounce',
				onStep: function(from, to, percent) {
					$(this.el).find('.percent').text(Math.round(percent));
				}
			});
			var chart = window.chart = $('.chart').data('easyPieChart');
			$('.js_update').on('click', function() {
				chart.update(Math.random()*200-100);
			});
		});
	</script>
	{/literal}

</body>
</html>
