<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{$meta_title}</title>
<meta name="keywords" content="{$meta_keywords}"/>
<meta name="description" content="{$meta_description}"/>
<meta name="rating" content="general"/>
<meta name="language" content="{$lang}" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="image/favicon/favicon.ico" rel="shortcut icon" />
{foreach from=$cssList item=css}
<link href="{$css}" type="text/css" rel="stylesheet" />
{/foreach}
{foreach from=$javascriptList item=javascript}
<script language="JavaScript" type="text/javascript" src="{$javascript}"></script>
{/foreach}
</head>

<body class="body">

	<div class="main">
	
		<div class="mainFrameAdmin">

			<div class="centerFrame2">
			{foreach from=$mainList item=frame}
			{include file="$frame"}
			{/foreach}
			</div>
			
			<div class="footerFrame">
			{foreach from=$footerList item=frame}
			{include file="$frame"}
			{/foreach}
			</div>
			
	
			<div class="headerFrame">
			{foreach from=$headerList item=frame}
			{include file="$frame"}
			{/foreach}
			</div>
		</div>
	</div>
	
</html>
