<!DOCTYPE html>
<html lang="en" class="login_page">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="{$meta_keywords}"/>
<meta name="description" content="{$meta_description}"/>
<meta name="rating" content="general"/>
<title>Edit-Place Admin : Login</title>
<link href="image/favicon/favicon.ico" rel="shortcut icon" />
{foreach from=$cssList item=css}
<link href="/BO/{$css}" type="text/css" rel="stylesheet" />
{/foreach}
 <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
{foreach from=$javascriptList item=javascript}
<script language="JavaScript" type="text/javascript" src="/BO/{$javascript}"></script>
{/foreach}

</head>
<body>
	{foreach from=$rightList item=frame}
		{include file="$frame"}
	{/foreach}

</body>
</html>





