<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-type" content="text/html; charset=ISO-8859-1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="{$meta_keywords}"/>
<meta name="description" content="{$meta_description}"/>
<meta name="rating" content="general"/>
<meta name="language" content="{$lang}" />
{foreach from=$SubMenusLeftPanel key=myId item=i name=count}
    {if $myId eq $submenuId}
        <title>Edit-Place Admin : {$i|escape:"htmlall"|stripslashes}</title>
    {/if}
{/foreach}
<link href="image/favicon/favicon.ico" rel="shortcut icon" />
{assign var='cssfiles' value=''}
{foreach from=$cssList item=css}
{assign var='cssfiles' value=$cssfiles$css,}
<link href="/BO/{$css}" type="text/css" rel="stylesheet" />
{/foreach}
<!--<link type="text/css" rel="stylesheet" href="/min/b=BO&f={$cssfiles|substr:-1}"/>-->
<!--<link href="/BO/{$css}" type="text/css" rel="stylesheet" />-->
 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans" />
{foreach from=$javascriptList item=javascript}
<script language="JavaScript" type="text/javascript" src="/BO/{$javascript}"></script>
{/foreach}
</head>
<body  class="menu_hover">
<div id="loading_layer" style="display:none"><img src="/BO/theme/gebo/img/ajax_loader.gif" alt="" /></div>		
<!-- header -->
<div id="maincontainer" class="clearfix">
	<header>
	{foreach from=$headerList item=frame}
		{include file="$frame"}
		{/foreach}
	</header>

	<!-- sidebar -- left panel -->
	<a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Hide Sidebar">Sidebar switch</a>
	<div class="sidebar">
	{foreach from=$mainList item=frame}
	  {include file="$frame"}
	{/foreach}
	</div>

	<!-- main content -->
	<div id="contentwrapper">
		<div class="main_content">
			{foreach from=$rightList item=frame}
				{include file="$frame"}
			{/foreach}
	   </div>
	</div>
	{literal}
	<script type="text/javascript">
	$(document).ready(function() {
		/* show all elements & remove preloader*/
		setTimeout('$("html").removeClass("js")',1000);
		var flash_message="{/literal}{$actionmessages[0]}{literal}";
		var flash_type="{/literal}{$actionmessages[1]}{literal}";
		if(flash_message)
		{
			if(flash_type=='error')ftype='st-error';else ftype='st-success';
			$.sticky(flash_message, {autoclose : 5000, position: "top-center", type: ftype });
		}
	});	

	</script>
	{/literal}
</div>
</body>
</html>
