<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>{$meta_title}</title>
        <meta name="keywords" content="{$meta_keywords}"/>
        <meta name="description" content="{$meta_description}"/>
        <meta name="rating" content="general"/>
        <meta name="language" content="{$lang}" />
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <link href="image/favicon/favicon.ico" rel="shortcut icon" />

        {foreach from=$cssList item=css}
            <link href="/BO/{$css}" type="text/css" rel="stylesheet" />
        {/foreach}
        {literal}
            <style type="text/css">
            *
            {
                text-transform:none;
            }
            .main_content {
                margin-left:0px;
            }
            </style>
        {/literal}
 <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans" />
        {foreach from=$javascriptList item=javascript}
        <script language="JavaScript" type="text/javascript" src="/BO/{$javascript}"></script>
        {/foreach}

    </head>

    <body style="background: none;">
    
        <header>
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container-fluid">
                        <a class="brand"><i class="icon-eye-open icon-white"></i> Result View</a>
                    </div>
                </div>                           
            </div>
        </header>
        <div id="seoviewresultspage" class="main_content">      
                <div class="control-group">
					<div class="row-fluid">        
						{$table}
					</div>
				</div>
        </div>
    
    </body>
{literal}

        <script type="text/javascript">
        $(document).ready(function() {
{/literal}{foreach from=$sheet_count item=sheet}{literal}
	    if($('#smpl_tbl{/literal}{$sheet}{literal}').length) {
                $('#smpl_tbl{/literal}{$sheet}{literal}').dataTable({
                    "sPaginationType": "bootstrap",
					"iDisplayLength" : 100,
                    "sDom": "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
                    "oTableTools": {
                        "aButtons": [
                            "copy",
                            "print",
                            {
                                "sExtends":    "collection",
                                "sButtonText": 'Save <span class="caret" />',
                                "aButtons":    [ "csv", "xls", "pdf" ]
                            }
                        ],
                        "sSwfPath": "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
                    },
		    "aaSorting": [[1, 'natural-asc']]
                });
            }
{/literal}{/foreach}{literal}
        });
    </script>
{/literal}
</html>
