{literal}
<script type="text/javascript">
function getUrlVars()
{
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}

var ctype = getUrlVars()["counttype"];
var count = getUrlVars()["count"];

$(document).ready(function() {

    $("#newusertab").addClass('active');

    //////////////////////////////////////////////////////////////
    $("#sel_type").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#sel_status").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#type").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#status").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#sel_group").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#sel_user").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#category").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#nationalism").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#language").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#language2").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#contrib").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#country").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#aotitle").chosen({ allow_single_deselect: false,search_contains: true  });
    $("#contribquiz").chosen({ allow_single_deselect: false,search_contains: true  });
    $(".uni_style").uniform();
    gebo_validation.reg();

});
function checkEmailExist()
{
    var email = $("#email").val();
    var target_page = "/user/email-exits?email="+email;
    $.post(target_page, function(data){ //alert(data);
        var data1 = data.trim();
        if(data1 == "yes")
        {
            smoke.alert("email id is already exist");
            $("#emai").val('');
            return false;
        }
        else
        {

            return true;
        }
    });
}

//* validation
gebo_validation = {
    reg: function() {
        reg_validator = $('.form_validation_reg').validate({
            onkeyup: false,
            errorClass: 'error',
            validClass: 'valid',
            highlight: function(element) {
                $(element).closest('div').addClass("f_error");
            },
            unhighlight: function(element) {
                $(element).closest('div').removeClass("f_error");
            },
            errorPlacement: function(error, element) {
                $(element).closest('div').append(error);
                $('.error').css("font-size", "10px");
                $('.error').css("padding-top", "5px");
            },
            rules: {
                first_name: { required: true, minlength: 3 },
                last_name: { required: true, minlength: 2 },
                login: { required: true, minlength: 2 },
                password: { required: true, minlength: 2 },
                phone_number: { required: true },
                address2: { required: true, minlength: 5 },
                country: { required: true, minlength: 2 },
                email: { required: true, minlength: 3 },
                type: { valueNotEquals: "default" } ,
                status: { valueNotEquals: "default" }
            },
            invalidHandler: function(form, validator) {
                $.sticky("There are some errors. Please correct them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
            }
        })
    }
};


///////validating the search form/////
function valSearchContribs()
{
    if($('#minage').val()!= '')
    {
        if ($.isNumeric($('#minage').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#minage').focus();
            return false;
        }
        else if ($.isNumeric($('#maxage').val()) == false || $('#maxage').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#maxage').focus();
            return false;
        }
        else if ($('#minage').val() >=  $('#maxage').val())
        {
            smoke.alert("min value is greater than max value");
            $('#maxage').focus();
            return false;
        }
    }
    if($('#min_arts_validated').val()!= '')
    {
        if ($.isNumeric($('#min_arts_validated').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#min_arts_validated').focus();
            return false;
        }
        else if ($.isNumeric($('#max_arts_validated').val()) == false || $('#max_arts_validated').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#max_arts_validated').focus();
            return false;
        }
    }
    if($('#min_total_parts').val()!= '')
    {
        if ($.isNumeric($('#min_total_parts').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#min_total_parts').focus();
            return false;
        }
        else if ($.isNumeric($('#max_total_parts').val()) == false || $('#max_total_parts').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#max_total_parts').focus();
            return false;
        }
    }
    if($('#min_arts_sent').val()!= '')
    {
        if ($.isNumeric($('#min_arts_sent').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#min_arts_sent').focus();
            return false;
        }
        else if ($.isNumeric($('#max_arts_sent').val()) == false || $('#max_arts_sent').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#max_arts_sent').focus();
            return false;
        }
    }
    if($('#min_parts_refused').val()!= '')
    {
        if ($.isNumeric($('#min_parts_refused').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#min_parts_refused').focus();
            return false;
        }
        else if ($.isNumeric($('#max_parts_refused').val()) == false || $('#max_parts_refused').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#max_parts_refused').focus();
            return false;
        }
    }
    if($('#min_arts_refused').val()!= '')
    {
        if ($.isNumeric($('#min_arts_refused').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#min_arts_refused').focus();
            return false;
        }
        else if ($.isNumeric($('#max_arts_refused').val()) == false || $('#max_arts_refused').val()=="")
        {
            smoke.alert("please enter only numeric values");
            $('#max_arts_refused').focus();
            return false;
        }
    }
    if($('#noof_disapproved').val()!= '')
    {
        if ($.isNumeric($('#noof_disapproved').val()) == false)
        {
            smoke.alert("please enter only numeric values");
            $('#noof_disapproved').focus();
            return false;
        }
    }
    else
        return true;
}
//* bootstrap datepicker
gebo_datepicker = {
    init: function() {
        $('#dp1').datepicker();
        $('#dp2').datepicker();
        $('#actdp1').datepicker();
        $('#actdp2').datepicker();
    }};
function changeStatusUser(userid, status)
{
    if(status == 'Inactive')
        var statusmsg = 'Active';
    else
        var statusmsg = 'Inactive';
    smoke.confirm("Do you really want to make user "+statusmsg,function(e){
        if (e)
        {
           // window.location.href="users-list?submenuId=ML2-SL7&tab="+tab+"&delete=yes&userId="+userid;
            var target_page = "/user/changeuserstatus?status="+statusmsg+"&user_id="+userid;
            $.post(target_page, function(data){ //alert(data);
                $('#userstatus_'+userid).html("<a onclick=\"changeStatusUser('"+userid+"', '"+statusmsg+"');\">"+statusmsg+"</a>");
                window.location.reload();
            });
        }
        else
        {
            return false;
        }
    });
}
</script>
{/literal}
<div class="row-fluid">
  <div class="span12" >
      <div class="tabbable">
          <div class="tab-content" style="overflow:hidden;">
              <div class="tab-pane " id="newusertab">
                  <div class="alert alert-warning"><b> Cr&eacute;ation d'un nouveau BO user</b></div>
                  <form class="form_validation_reg" action="/user/new-bo-user?submenuId={$submenuId}"  style="padding-left: 50px;" method="post" id="user" name="user" enctype="multipart/form-data">
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4">Initial  <span class="f_req">*</span></label>
                                  <label class="uni-radio">
                                      <input type="radio" name="initial" id="initialmr" checked="" value="mr" class="uni_style"/> mr
                                  </label>
                                  <label class="uni-radio">
                                      <input type="radio" name="initial" id="initialmme" value="mme"  class="uni_style"/> mme
                                  </label>
                                  <label class="uni-radio">
                                      <input type="radio" name="initial" id="initialmlle" value="mlle" class="uni_style"/> mlle
                                  </label>
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4">Email<span class="f_req">*</span></label>
                                  <input type="text" name="email" id="email" value=""/>
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4">First name <span class="f_req">*</span></label>
                                  <input type="text" name="first_name" id="first_name" value="" />
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4">Last name <span class="f_req">*</span></label>
                                  <input type="text" name="last_name" id="last_name" value="" />
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4"> Login Name <span class="f_req">*</span></label>
                                  <input type="text" name="login" id="login" value=""/>
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4">Password<span class="f_req">*</span></label>
                                  <input type="password" name="password" id="password" value=""/>
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4"> City   </label>
                                  <input type="text" name="city" id="city" value="" />
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4">State </label>
                                  <input type="text" name="state" id="state" value=""/>
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4"> Type </label>
                                  <select name="type" id="type"  placeholder="type">
                                      <option value=""></option>
                                      {html_options  options=$usergroups selected='editor'}
                                  </select>
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4"> Active </label>
                                  <select name="status" id="status" class="text-field-big" placeholder="active">
                                      <option value=" "></option>
                                      <option value="Active" selected="selected">Active</option>
                                      <option value="Inactive">Inactive</option>
                                  </select>
                              </div>

                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4">Zip Code </label>
                                  <input type="text" name="zipcode" id="zipcode" value=""/>
                              </div>
                              <div class="span5 form-inline">
                                  <label class="span4">Phone Number  <span class="f_req">*</span></label>
                                  <input type="text" name="phone_number" id="phone_number" value=""/>
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4">Country<span class="f_req">*</span></label>
                                  <select name="country" id="country"  placeholder="country">
                                      <option value=" "></option>
                                      {html_options  options=$country_array }
                                  </select>
                              </div>
                              <div class="controls span5 form-inline">
                                  <label class="span4"> Upload picture <span class="f_req">*</span></label>
                                  <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" value="" name="">
                                          <span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span>
                                              <input type="file" name="uploadfile" id="uploadfile" /></span>
                                      <span class="fileupload-preview"></span>
                                      <a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">&times;</a>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <label class="span4"> Adress </label>
                                  <textarea name="address" rows="3" id="address" value=""></textarea>
                              </div>

                          </div>
                      </div>
                      <div class="formSep">
                          <div class="row-fluid">
                              <div class="span5 form-inline">
                                  <button type="submit" name="usersubmit"  class="btn btn-success pull-right">Create New User</button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>

<div style="visibility:hidden" >
    <form id="user_login_form" name="user_login_form" method="post" action="" target="_blank">
        <input type="text" id="login_name" name="login_name" value="">
        <input type="password" id="login_password" name="login_password" value="{$user_detail[0].password}" >
        <input type="submit" value="Login" />
    </form>
</div>

{literal}
<script type="text/javascript" >
    function connect_fo(user,email,pwd)
    {
        document.forms["user_login_form"].action="http://ep-test.edit-place.co.uk/index/userfologin";
        $('#login_name').val(email);
        $('#login_password').val(pwd);
        document.forms["user_login_form"].submit();
    }
</script>
{/literal}


