
   <table class="table table-striped table-bordered table-condensed">
       <tr>
           <td> <span class="pull-right"> Name </span> </span> </td>
           <td> <span class="pull-left"> {$user_detail[0].last_name|utf8_encode}&nbsp;{$user_detail[0].first_name|utf8_encode} </span> </td>
       </tr>
      <!-- <tr>
           <td>  <span class="pull-right">Profession  </span> </td>
           <td> <span class="pull-left">{$profession|utf8_encode}  </span> </td>
       </tr>
       <tr>
           <td>  <span class="pull-right"> Education </span> </td>
           <td> <span class="pull-left"> {$education} </span> </td>
       </tr>
       <tr>
           <td> <span class="pull-right"> Language </span> </td>
           <td> <span class="pull-left"> {$language|utf8_encode} </span> </td>
       </tr>
       <tr>
           <td>  <span class="pull-right">Favourite Categories  </span> </td>
           <td> <span class="pull-left">{$favourite_category}  </span> </td>
       </tr>-->
       <tr>
           <td>  <span class="pull-right"> Total Participations  </span> </td>
           <td> <span class="pull-left">{$parti_detail[0].no_participations}  </span> </td>
       </tr>
       <tr>
           <td> <span class="pull-right">  Total Articles Published </span> </td>
           <td> <span class="pull-left"> {$parti_detail[1].no_approved} </span> </td>
       </tr>
       <tr>
           <td>  <span class="pull-right">  Total Articles Refused  </span> </td>
           <td> <span class="pull-left"> {$parti_detail[2].no_disapproved} </span> </td>
       </tr>

   </table>

			
