{literal}
<style>
.wrapper table
{
	width: 100%;
}

.wrapper .table thead th
{
	background-color: inherit !important;
}

.wrapper table thead th:last-child
{
	background-color: #1fbba6 !important;
}
.realtotal{
    color: #89c0f7;
    font-weight: bold;
    text-transform: uppercase;
}
.realtotal a{
font-size: 26px;
 }
</style>
{/literal}

		<section id="">
		
				<div class="row-fluid">
					<h1> Real Turnover {$year}:<span class="realtotal"> {$totalturnovereuro|zero_cut_t:2} &euro; - {$totalturnoverpound|zero_cut_t:2} &pound;</span></h1>
				</div>
			<div class="row-fluid">	
			<div class="" style="margin-top:-20px">
			<form id="filter_rturn">
					<select data-placeholder="Years" id="yearlist" name="year" class='yearselect submit'>
					<option></option>
						{foreach from=$year_list item=years name=year_loop}
							{if $years eq $year}
							   <option value="{$years}" selected="selected" >{$years}</option>
							{else}
							   <option value="{$years}" >{$years}</option>
							{/if}
						{/foreach}
					</select>
					<select data-placeholder="All Clients" id="all_clients" name="client" class='clientselect' >
						<option value="">All Clients</option>
						{foreach from=$clients item=user name=users key=userkey}
						{if $userkey eq $client}
							<option value="{$userkey}" selected>{$user}</option>
						{else}
							<option value="{$userkey}" >{$user}</option>
						{/if}
						{/foreach}
					</select>
					<select data-placeholder="All Sales" id="all_sales" class='saleselect' name="sales_id" >
										<option></option>
									
											{foreach from=$salesusers item=user name=users key=usrkey}
											{if $usrkey eq $smarty.get.sales_id}
										<option value="{$usrkey}" selected="selected">{$user}</option>
												{else}
											<option value="{$usrkey}" >{$user}</option>
											{/if}
									
										{/foreach}
					</select>
					<a class="btn submit" id="search-filter" style="margin-top:-23px">Refine</a>
			</form>
			</div>
			<div class="wrapper" id="">
				<table class="table table-hover" id="client-turnover">
					<thead>
						<tr class="displayDatas">
							<th>Code</th>
							<th style="width:250px">Client Name</th>
							<th>{$month_array_val.01}</th>
							<th>{$month_array_val.02}</th> 
							<th>{$month_array_val.03}</th>
							<th>{$month_array_val.04}</th>
							<th>{$month_array_val.05}</th>
							<th>{$month_array_val.06}</th>
							<th>{$month_array_val.07}</th>
							<th>{$month_array_val.08}</th>
							<th>{$month_array_val.09}</th>
							<th>{$month_array_val.10}</th>
							<th>{$month_array_val.11}</th>
							<th>{$month_array_val.12}</th>
							<th>total <span class="yearTotal">{$year}</span></th>
						</tr>					
					</thead>
					<tbody>		
					{if $monthturnovers|@count> 0}
					{foreach from=$monthturnovers item="monthturnover" name="monthturnover"}
						<tr>
							<td>{$monthturnover.other_info.client_code}</td>
							<td>
								<a href="/turnover/real-month-client-focus?client={$monthturnover.other_info.user_id}&year={$year}&sales_id={$smarty.get.sales_id}">
								{$monthturnover.other_info.company_name}
								</a>
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'01'}
								{assign var='total' value=$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'02'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'03'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'04'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'05'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'06'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'07'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'08'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
							{assign var=month_year value=$year|cat:'-'|cat:'09'}
							{assign var='total' value=$total+$monthturnover.$month_year}
							{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'10'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'11'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td>
								{assign var=month_year value=$year|cat:'-'|cat:'12'}
								{assign var='total' value=$total+$monthturnover.$month_year}
								{$monthturnover.$month_year|zero_cut_t:2}
							</td>
							<td style="text-align:right">{$total|zero_cut_t:2} &{$monthturnover.other_info.currency};</td>						
						</tr>	
					{/foreach}
					{else}
						<tr>
							<th colspan="14" style="text-align:center">No record found!</th>
						</tr>
					{/if}
					</tbody>
				</table>
		{*	<a class="btn btn-primary" style="margin-top: 10px;" href="/turnover/real-turnover-report?download=pdf{if $smarty.get.client}&client={$smarty.get.client}{/if}{if $year}&year={$year}{/if}">Export PDF</a>
			<a class="btn btn-primary" style="margin-top: 10px;" href="/turnover/real-turnover-report{if $year}?year={$year}{/if}{if $smarty.get.client}&client={$smarty.get.client}{/if}" >Export XLS</a>	*}
			</section>
					
	{literal}

	<script>
		$(document).ready(function(){
			$("#yearlist").chosen({allow_single_deselect:false,search_contains: true});
	  	    $("#all_clients").chosen({allow_single_deselect:false,search_contains: true});
			$("#all_sales").chosen({allow_single_deselect:true,search_contains: true});
			$(".submit").on('click',function(){
				$("#filter_rturn").submit();
			})
			
			$('#client-turnover').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"iDisplayLength" : 50,
				 "aaSorting": [[ 0, "asc" ]],
				"aoColumns": [
					{ "sType": "string"  },
					{ "sType": "string"  },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" },
					{ "sType": "natural" }
				]
			});

		});

	</script>
	{/literal}
