<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
{literal}
<script type="text/javascript" >

    $(document).ready(function() {
	$("#manager_id").chosen({allow_single_deselect: true});
	//onload getting deliveries linked to client
			var client_id=$("#clients").val();
			fnloaddeliveries(client_id,'');
	
       if($('#ongoing_list').length) {
                $('#ongoing_list').dataTable({
                    "sPaginationType": "bootstrap",
					"iDisplayLength" : 25,
                     "sDom": "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
					"aoColumns": [
						{ "sType": "formatted-num" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "eu_date" },
						{ "sType": "string" },
						{ "sType": "string" },
						/*{ "sType": "natural" },
						{ "sType": "natural" },*/
						{ "sType": "string" }
					],
					"aaSorting": [[ 0, "asc" ]],
                    "oTableTools": {
                        "aButtons": [
                            "copy",
                            "print",
                            {
                                "sExtends":    "collection",
                                "sButtonText": 'Save <span class="caret" />',
                                "aButtons":    [ "csv", "xls", "pdf" ]
                            }
                        ],
                        "sSwfPath": "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
                    }
                });
            }
    });
</script>
{/literal}

<!--Bread Crumbs-->
<!--<nav>
	<div id="jCrumbs" class="breadCrumb module">
		<ul>
			<li>
				<a href="/index"><i class="icon-home"></i></a>
			</li>
			<li>
				<a>Ongoing AO</a>
			</li>			
		</ul>
	</div>
</nav>-->

<div class="row-fluid">
  <div class="span12">
    <h3 class="heading">ONGOING / EDIT OF TENDER		
			<a class="btn btn-gebo1" id="ong_search">Search</a>
	</h3>
	<div class="{if !$smarty.get.search}hide{/if} well clearfix" id="search_block">
		<div class="row-fluid">
			<form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >				
				 <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
				<!--<div class="row-fluid">-->
					<span class="sepV_c">
						<input type="text" placeholder="From" id="dp_start" name="startdate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/>
					</span>
					<span class="sepV_c">
						<input type="text"  placeholder="To" id="dp_end" name="enddate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.enddate}"/>
					</span>
					<span class="sepV_c">
						<select name="client_id" id="clients" data-placeholder="Clients" onChange="fnloaddeliveries(this.value);">
							{html_options  options=$client_array  selected=$smarty.get.client_id}	
						</select>	
					</span>									
					<span class="sepV_c"  id="aolistall">
						<select name="ao_id" id="deliveries" data-placeholder="Deliveries">
							<option value=""></option>
							{html_options  options=$delivery_array  selected=$smarty.get.ao_id  selected=$smarty.get.ao_id}				  
						</select>	
						  
					</span>
					<span class="sepV_c" style="float:left;clear:both;">
						<select name="manager_id" id="manager_id" data-placeholder="Project manager">
							<option value="0"></option>
							{html_options options=$projectm_array selected=$manager_id}	
						</select>	
					</span>	
					<span class="sepV_c">
						<select id="sorttype" name="sorttype" data-placeholder="Trier par">
							<option value=""></option>
							<option value="all" {if $smarty.get.sorttype eq 'all' OR $smarty.get.sorttype eq ''}selected{/if}>ALL</option>
							<option value="onging" {if $smarty.get.sorttype eq 'onging'}selected{/if}>Ongoing</option>
							<option value="close" {if $smarty.get.sorttype eq 'close'}selected{/if}>Closed</option>
							<option value="new" {if $smarty.get.sorttype eq 'new'}selected{/if}>New</option>
						</select>	
					</span>
					<span class="sepV_c">
						<select id="pay_status" name="pay_status" data-placeholder="Payment Status">
							<option value=""></option>
							<option value="all" {if $smarty.get.pay_status eq 'all'}selected{/if}>ALL</option>
							<option value="paid" {if $smarty.get.pay_status eq 'paid'}selected{/if}>Paid</option>
							<option value="notpaid" {if $smarty.get.pay_status eq 'notpaid'}selected{/if}>Pending</option>							
						</select>	
					</span>					
				<!--</div>	
				<div class="row-fluid">-->		
					<span class="sepV_c">
						<button class="btn btn-danger pull-center" id="search" name="search" type="submit" value="search" >Search</button>
						<button class="btn btn-info pull-center" id="clear" name="clear" type="button" value="clear" onclick="clearAll();" >Clear</button>	
					</span>
				<!--</div>-->
			</form>	
		  
		</div>
	</div>     
       
	<table class="table table-striped table-bordered dTableR" id="ongoing_list">
		<thead>
			<tr>
				<th>S.No.</th>
				<th>AO Title</th>
				<th>Client</th>
				<th>Date of creation</th>
				<th>Project manager</th>
				<th>Progression</th>
				<!--<th>Pay&eacute; (&euro;)</th>
				<th>Total (&euro;)</th>-->
				<th>Type</th>
			</tr>
		</thead>
		<tbody>
	{if $ongoingAO |@count gt 0}
		{foreach item=delivery from=$ongoingAO name="aoDetails"} 
			<tr>
			  <td>{$smarty.foreach.aoDetails.index+1}</td>
              <td><div style="display:none;">{$delivery.title}</div><a href="/ongoing/ao-details?client_id={$delivery.user_id}&ao_id={$delivery.id}&submenuId={$smarty.get.submenuId}">{$delivery.title|stripslashes|wordwrap:40:"<br>":true}</a></td>
			  <td>{$delivery.client}</td>
			  <td>{$delivery.created_at|date_format:"%d/%m/%Y"}</td>
			  {math equation="a - b" a=$delivery.totalArticle b=$delivery.published_articles assign="pending_article"}
			  <td>{$delivery.projectmanager}</td>
			  <td>
			      <div style="display: none;">{$delivery.progressbar}</div>
                  <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="{$delivery.progressbar}" aria-valuemin="0" aria-valuemax="100"
                      {if $delivery.progressbar eq 0} style="width: 100%;  background:#E3E5F4;"
                      {else} style="width: {$delivery.progressbar}%; color:#000000; background:{$delivery.progresscolorcode};"{/if}>
                      {$delivery.progressbar}%  </div>
                  </div>
			  </td>
			  <!--<td><span class="label label-success">{$delivery.amount_paid|zero_cut:2}</span></td>
			  <td><span class="label label-inverse">{$delivery.totalAmount|zero_cut:2}</span></td>-->
			  <td>
					{if $delivery.missiontest eq 'yes'}
						<i class="splashy-star_boxed_half hint--left  hint--info" data-hint="Test Mission"></i>
					{elseif $delivery.premium_option !='0' && $delivery.premium_option!=''}
						<i class="splashy-star_boxed_full hint--left  hint--warning" data-hint="Premium Mission"></i>
					{else}
						<i class="splashy-star_boxed_empty hint--left  hint--info" data-hint="Freedom Mission" ></i>
					{/if}					
			 </td>
			</tr>
		{/foreach}
	{/if}	
					
		</tbody>
	</table>
                        
  </div>
</div>
    <input type="hidden" id="hide_total" name="hide_total"  />

<!--///for the article profiles popup///-->
<div class="modal4 hide fade" id="artprofile">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h3>Article Profiles</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>





