{if $quoteDetails|@count gt 0}
	{foreach from=$quoteDetails item=quote name="quote"}
		<table>
			<tr>
				<td align="left" colspan="9"><img src="/BO/theme/gebo/img/edit-place.png"></td>
			</tr>
		</table>	
		<table>
			<tr><td colspan="9"></td></tr>
		</table>	
		<table border="1" width="100%">
			<tr>
				<td colspan="2">{$quote.client_code}</td>
				<td align="center" colspan="5"  style="font-size:22px;"><b>Quote / Purchase Order</b></td>
				<td colspan="2"></td>
			</tr>
			<tr>
				<td style="font-size:14px;" colspan="2"><b>EDIT-PLACE UK</b></td>				
				<td colspan="5" align="center"></td>				
				<td style="font-size:16px;" colspan="2"><b>{$quote.company_name}<b></td>
			</tr>
			
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2">67-70 Charlotte Road </td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.address|strip_tags}</td>
			</tr>
			<tr>
				<td>London</td><td>EC2A 3PE</td>
				<td colspan="5"></td>
				<td>{$quote.zipcode}</td>  <td>{$quote.city|lower|ucfirst}</td>
			</tr>
			<tr>
				<td colspan="2">UK</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.country_name|lower|ucfirst}</td>
			</tr>			
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2"><u>Commercial Contact</u></td>
				<td colspan="5"></td>
				<td colspan="2"><u>Commercial Contact</u></td>
			</tr>
			<tr>
				<td colspan="2">{$quote.quote_user_name}</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.client_contact_name}</td>
			</tr>
			<tr>
				<td colspan="2"><a href="mailto:mgaude@edit-place.com">{$quote.email}</a></td>
				<td colspan="5"></td>
				<td colspan="2"><a href="mailto:{$quote.client_contact_email}">{$quote.client_contact_email}</a></td>
			</tr>	
			<tr>
				<td colspan="2">&nbsp;{$quote.phone_number}</td>
				<td colspan="5"></td>
				<td colspan="2">&nbsp;{$quote.client_contact_phone}</td>
			</tr>
			<tr><td colspan="9"></td></tr>
			<tr>
				<td colspan="2"><u>Financial Contact</u></td>
				<td colspan="5"></td>
				<td>Start date</td>
				<td></td>
			</tr>
			<tr>
				<td colspan="2"><a href="mailto:comptabilite@edit-place.com">comptabilite@edit-place.com</a></td>
				<td colspan="5"></td>
				<td>End date</td>
				<td></td>
			</tr>
			<tr>
				<td colspan="2">44 20 3302 7440</td>
				<td colspan="5"></td>
				<td>Duration</td>
				<td>{$quote.total_duration} working {$quote.final_mission_length_option}</td>
			</tr>		
		</table>
		<table>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
		</table>
		<table border="1" width="100%">
			<tr>
				<td bgcolor="#F2F2F2"><b>Ref</b></td>
				<td bgcolor="#F2F2F2" colspan="3"><b>Project type</b></td>
				<td bgcolor="#F2F2F2"><b>Product</b></td>
				<td bgcolor="#F2F2F2"><b>No. or words</b></td>
				<td bgcolor="#F2F2F2"><b>Quantity</b></td>
				<td bgcolor="#F2F2F2"><b>Price</b></td>
				<td bgcolor="#F2F2F2"><b>TOTAL</b></td>
			</tr>	
			{if $quote.mission_details|@count gt 0}
				{assign var=ref_number value=0}
				{foreach from=$quote.mission_details item=mission name="misson"}							
					{assign var=ms_index value=$smarty.foreach.misson.index+1}	
					{if $mission.before_prod eq 'yes'}{assign var="before_prod" value="yes}{/if}					
					{if $mission.package neq 'user'}						
						{assign var=ref_number value=$ref_number+1}
						<tr>	
							<td align="left">{$ref_number}</td>							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}
									<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} {if $mission.before_prod eq 'yes'}*{/if}</td>
								{else}
									<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'} - {$mission.language_dest_name|utf8_decode}{/if} {$mission.product_type_other} {if $mission.before_prod eq 'yes'}*{/if}</td>
								{/if}							
							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}
									<td>{$mission.product_name}</td>
								{else}
									<td>{$mission.product_type_name}</td>
								{/if}
							
							<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
							<td align="right">{$mission.volume}</td>
							<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}FREE in &{$quote.sales_suggested_currency}; {$mission.unit_price|num_format:2} {else} &{$quote.sales_suggested_currency}; {$mission.unit_price|num_format:2} {/if}{else}{if $mission.free_mission eq 'yes'}FREE in {$mission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.turnover|num_format:2}{else}{$mission.turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
						{if $mission.package eq 'team'}
							{assign var=ref_number value=$ref_number+1}
							<tr>
								<td align="left">{$ref_number}</td>								
									{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy' }
										{assign var="missionType" value=$mission.product_name}
										<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} - Staffing - Pack of {$mission.team_packs} CVs</td>
									{else}
										{assign var="missionType" value=$mission.product_type_name}
										<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'}- {$mission.language_dest_name|utf8_decode}{/if} {$mission.product_type_other} - Staffing - Pack of {$mission.team_packs} CVs</td>
									{/if}								
								<td>{$missionType}</td>
								<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
								<td align="right">{$mission.team_packs}</td>
								<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}FREE in &{$quote.sales_suggested_currency}; {$mission.team_fee|num_format:2} {else} &{$quote.sales_suggested_currency}; {$mission.team_fee|num_format:2}{/if}{else}{if $mission.free_mission eq 'yes'}FREE in {$mission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
								<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.team_package_turnover|num_format:2}{else}{$mission.team_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
							</tr>
						{/if}
					{elseif $mission.package eq 'user'}
						{assign var=ref_number value=$ref_number+1}
						<tr>
							<td align="left">{$ref_number}</td>
							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy' }
									{assign var="missionType" value=$mission.product_name}
									<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} - Number of profiles {$mission.required_writes}</td>
								{else}
									{assign var="missionType" value=$mission.product_type_name}
									<td colspan="3">{$mission.product_name} in {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'}- {$mission.language_dest_name|utf8_decode}{/if} {$mission.product_type_other} - Number of profiles {$mission.required_writes}</td>
									
								{/if}							
							<td>{$missionType}</td>
							<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
							<td align="right">{$mission.required_writes}</td>
							<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}FREE in  &{$quote.sales_suggested_currency};  {$mission.user_fee|num_format:2}{else} &{$quote.sales_suggested_currency}; {$mission.user_fee|num_format:2} {/if}{else}{if $mission.free_mission eq 'yes'}FREE in {$mission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.user_package_turnover|num_format:2}{else}{$mission.user_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
					{/if}
				{/foreach}
			{/if}
			{if $quote.tech_mission_details|@count gt 0}
				{foreach from=$quote.tech_mission_details item=tmission name="tmission"}					
				{if $tmission.before_prod eq 'yes'}{assign var="before_prod" value="yes}{/if}					
					{if $tmission.package neq 'user'}						
						{assign var=ref_number value=$ref_number+1}
						<tr>	
							<td align="left">{$ref_number}</td>
							<td colspan="3">{$tmission.title}{if $tmission.before_prod eq 'yes'}*{/if}</td>
							<td>Technical mission</td>
							<td align="right">-</td>
							<td align="right">{$tmission.volume}</td>
							<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}FREE in &{$quote.sales_suggested_currency};  {$tmission.unit_price|num_format:2} {else}&{$quote.sales_suggested_currency}; {$tmission.unit_price|num_format:2}{/if}{else}{if $tmission.free_mission eq 'yes'}FREE in {$tmission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.turnover|num_format:2} {else}{$tmission.turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>						
						{if $tmission.package eq 'team'}
							{assign var=ref_number value=$ref_number+1}							
							<tr>
								<td align="left">{$ref_number}</td>
								<td colspan="3">{$tmission.title} - Pack of {$tmission.team_packs} CVs</td>
								<td>Technical mission</td>
								<td align="right">-</td>
								<td align="right">{$tmission.team_packs}</td>
								<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}FREE in &{$quote.sales_suggested_currency}; {$tmission.team_fee|num_format:2} {else}&{$quote.sales_suggested_currency}; {$tmission.team_fee|num_format:2} {/if}{else}{if $tmission.free_mission eq 'yes'}FREE in {$tmission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
								<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.team_package_turnover|num_format:2}{else}{$tmission.team_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>									
							</tr>
						{/if}
					{elseif $tmission.package eq 'user'}
						{assign var=ref_number value=$ref_number+1}	
						<tr>
							<td align="left">{$ref_number}</td>
							<td colspan="3">{$tmission.title} - Number of profiles {$tmission.required_writes}</td>
							<td>Technical mission</td>
							<td align="right">-</td>
							<td align="right">{$tmission.required_writes}</td>
							<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}FREE in &{$quote.sales_suggested_currency}; {$tmission.user_fee|num_format:2} {else} &{$quote.sales_suggested_currency}; {$tmission.user_fee|num_format:2}{/if}{else}{if $tmission.free_mission eq 'yes'}FREE in {$tmission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.user_package_turnover|num_format:2}{else}	{$tmission.user_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
					{/if}
				{/foreach}
			{/if}
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2">Advance payment 30%</td>
				<td colspan="2">no</td>
				<td>Time to launch project</td>
				<td>{$quote.total_staff_setup_time} working {$quote.final_mission_length_option}</td>
				<td></td>
				<td><b>TOTAL EXCL. VAT</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.final_turnover|num_format:2}{else}{$quote.final_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
			<tr>
				<td colspan="2">Payment term</td>
				<td colspan="2">30 days from invoice date</td>
				<td>Delivery time</td>
				<td>{$quote.total_delivery_time} working {$quote.final_mission_length_option}</td>
				<td></td>
				<td><b>VAT</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.tva|num_format:2}{else}{$quote.tva|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
			<tr>
				<td colspan="7"></td>
				<td><b>TOTAL INC. VAT</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.total_htc|num_format:2}{else}{$quote.total_htc|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
		</table>			
		{if $before_prod eq 'yes'}
			<table>
				<tr>
					<td colspan="9">*This mission must be completed in order to start production</td>
				</tr>
			</table>
		{/if}
		<table>
			<tr>
				<td align="center" bgcolor="#F2F2F2" colspan="9">Comments</td>
			</tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9" align="center" rowspan="3" height="50px">Insert your comments here</td></tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
			<tr>
				<td align="center" colspan="9">The prices quoted in this document are valid for 21 days, once the PO has been signed the prices are fixed</td>
			</tr>
			<tr>
				<td align="center" colspan="9">Before starting the project you must sign and date both the T&S and the purchase order.</td>
			</tr>
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
			<tr>
				<td colspan="2"><b>Edit-Place signature and stamp</b></td>
				<td colspan="5"></td>
				<td colspan="2"><b>Customer signature and date</b></td>
			</tr>
			<tr>
				<td colspan="2">Read and approved</td>
				<td colspan="5"></td>
				<td colspan="2">Read and approved</td>
			</tr>
			<tr>
				<td colspan="2"><b>{$smarty.now|date_format:"%d/%m/%Y"}</b></td>
				<td colspan="5"></td>
				<td colspan="2"></td>
			</tr>				
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
				
				<tr><td colspan="9" align="center" style="font-size:10px;">EDIT-PLACE UK Ltd - 67-70 Charlotte Road, London EC2A 3PE - Tel. +44 (0) 20 3302 4494</td></tr>
				<tr><td colspan="9" align="center" style="font-size:10px;">Registered under the laws of England and Wales: #8610398 - VAT NUMBER : 182 0572 18</td></tr>						
		</table>
	{/foreach}
{/if}
