{literal}

<script type="text/javascript" >
$(document).ready(function() {

    $('#closemissionsgrid').dataTable({
        "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "aaSorting": [[ 0, "asc" ]],
        "aoColumns": [
            { "sType": "formatted-num" },
            { "sType": "string" , "sWidth": "15%"
            },
            { "sType": "string" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" }
        ]

    });

});

</script>
{/literal}
<div class="row-fluid">
  <div class="span12" style="">
<!--    <h3 class="heading">Mod&eacute;ration mission libert&eacute;<a href="#searchblock" onclick="showSearch();"  class="label label-inverse alignright">Search</a></h3>
-->     <div class="hide" id="searchblock">

     </div>
     <div class="tabbable">

          <div class="tab-content">
              <ul class="nav nav-tabs">
             <li {if $smarty.get.tab == 'newaos' || $smarty.server.REQUEST_URI == '/processao/liberte-newaos?submenuId=ML2-SL1'} class="active" {/if}><a href="/processao/liberte-newaos?tab=newaos&submenuId=ML2-SL1" class="lable-danger"><strong>New missions</strong></a></li>
             <li {if $smarty.get.tab == 'ongoingaos'} class="active" {/if}><a href="/processao/liberte-ongoingaos?tab=ongoingaos&submenuId=ML2-SL1"  class="lable-info"><strong>Ongoing Missions</strong></a></li>
             <li {if $smarty.get.tab == 'validaos'} class="active" {/if}><a href="/processao/liberte-validaos?tab=validaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions finished</strong></a></li>
             <li {if $smarty.get.tab == 'refusedaos'} class="active" {/if}><a href="/processao/liberte-refusedaos?tab=refusedaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions refused</strong></a></li>
             <li {if $smarty.get.tab == 'cancelledaos'} class="active" {/if}><a href="/processao/liberte-cancelledaos?tab=cancelledaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions cancelled</strong></a></li>
         </ul>
              <table id="closemissionsgrid" class="table table-bordered table-striped table_vam" style="overflow-x: scroll;">
                  <thead>
                  <tr>
                    <th>SL.NO</th>
                    <th>Title</th>
                    <th>Client</th>
                    <th>Created</th>
                    <th>Type of content</th>
                    <th>Language</th>
                    <th>Writing/ Translating</th>
                    <th>History</th>
                    <th>Status</th>
                    <th>Nb of Participations</th>
                    <th>Invoice</th>
                    <th>Action</th>
                    <th>Turnover</th>
                </tr>
                  </thead>
                  <tbody>
                  {foreach from=$cancelledlist key=closedaos_key item=closedaos_item name=closedaos_loop}
                  <tr>
                      <td>{$smarty.foreach.closedaos_loop.index+1}</td>
                      <td><a data-target="#artprofile" role="button" href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$closedaos_item.id}">{$closedaos_item.title|stripslashes|wordwrap:20:"\n":true|upper}</a></td>
                      <td><a href="/user/client-edit?submenuId=ML10-SL2&tab=viewclient&userId={$closedaos_item.user_id}" class="hint--bottom hint--info" data-hint="since : {$closedaos_item.doj|date_format:'%d/%m/%Y'}">{if $closedaos_item.company_name neq ''}{$closedaos_item.company_name|upper}{else}{$closedaos_item.email}{/if}</a></td>
                      <td>{$closedaos_item.created_at|date_format:"%d/%m/%Y"}</td>
                      <td>{$closedaos_item.deltype}</td>
                      <td>{$closedaos_item.language}</td>
                      <td>{if $closedaos_item.content_type == 'writing'}R&eacute;daction{else}Traduction{/if}</td>
                      <td><a href="/ongoing/ao-history?ao_id={$closedaos_item.id}"  data-toggle="modal" data-hint="history" data-target="#ao_history" ><i class="splashy-information"></i></a></td>
                      <td>{$closedaos_item.latestStatus}</td>
                      <td>{$closedaos_item.contributors}</td>
                      <td>{if $closedaos_item.paid_status == 'notpaid'}Non pay&eacute;{else}pay&eacute;{/if}</td>
                      <td><!--<a data-toggle="modal" data-target="#publishao" id="publishaopop" href="/processao/showpraoinfo?aoid={$closedaos_item.id}&function=publish"><i class="splashy-check"></i></a>-->
                          <a data-toggle="modal" data-target="#editao" id="editaopop" href="/processao/showpraoinfo?aoid={$closedaos_item.id}&function=edit"><i class="splashy-pencil"></i></a>
                          <a href="/processao/mission-split?submenuId=ML2-SL1&aoid={$closedaos_item.id}" data-hint="split mission" class="hint--left hint--danger"><i class="splashy-diamonds_4"></i></a>
                          <a href="/BO/downloadpremiumquote.php?id={$newaos_item.quoteid}" class="hint--left hint--danger" data-hint="Download XSL"><i class="splashy-download"></i></a>
                      </td>
                      <td>{$closedaos_item.cost|string_format:"%.2f"}<b> &euro;</b></td>
                  </tr>
                  {/foreach}
                  </tbody>
              </table>
          </div>
     </div>
 </div>
</div>

<!--///for the edit ao detials popup///-->
<div class="modal container hide fade" id="editao">
    <div class="modal-header">
        <button class="close" onclick="closePopup('editao');">&times;</button>
        <h3>Edit AO Details</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--///for the publish ao  popup///-->
<div class="modal2 hide fade" style="overflow: hidden" id="publishao">
    <div class="modal-header">
        <button class="close" onclick="closePopup('publishao');">&times;</button>
        <h3>Publish AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

<!--History of AO-->
<div class="modal container hide fade" id="ao_history">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Historique des actions men&eacute;es sur l'AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--Comments of AO-->
<div class="modal hide fade" id="refusal_reasons">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Message to client</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>



