{literal}

<script type="text/javascript" >
$(document).ready(function() {
    $('#newmissionsgrid').dataTable({
        "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "aaSorting": [[ 0, "asc" ]],
        "sScrollXInner" : '200px',
        "aoColumns": [
            { "sType": "formatted-num" },
            { "sType": "string", "sWidth": "15%" },
            { "sType": "string" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" },
            { "sType": "natural" }
        ]

    });


});
/*$("#editaopop").live('click',function(e) { //alert("hello");
    e.preventDefault();
    var href = $(this).attr('href');
    $("#editao").removeData('modal');
    $('#editao .modal-body').load(href);
    $("#editao").modal();
    $(".modal-backdrop:gt(0)").remove();
    //$('.modal-backdrop').css('opacity','0.0');

});
$("#publishaopop").live('click',function(e) { //alert("hello");
    e.preventDefault();
    var href = $(this).attr('href');
    $("#publishao").removeData('modal');
    $('#publishao .modal-body').load(href);
    $("#publishao").modal();
    $(".modal-backdrop:gt(0)").remove();

});*/
</script>
{/literal}
<div class="row-fluid">
  <div class="span12" style="">
<!--    <h3 class="heading">Mod&eacute;ration mission libert&eacute;<a href="#searchblock" onclick="showSearch();"  class="label label-inverse alignright">Search</a></h3>
-->     <div class="hide" id="searchblock">
      <!--<form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >
          <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
        <table id="searchtable" class="table tdleftalign">
            <tr><td class="span1"><input type="text"  placeholder="From" id="dp1" name="startdate" data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/></td>
                <td class="span5">
                    <select id="clientId" name="clientId" onChange=fnloadao(this.value); data-placeholder="clients" class="span8">
                        {html_options options=$client_array  selected=$smarty.get.clientId }
                    </select>
                </td>
                <td class="span1"><button class="btn btn-info pull-left" id="clear" name="clear" type="button" value="clear" onclick="clearAll();" >Clear</button></td>
            </tr>
            <tr>
                <td class="span1"><input type="text"  placeholder="To" id="dp2" name="enddate" data-date-format="dd-mm-yyyy" value="{$smarty.get.enddate}"/></td>
                <td  class="span5" id="aolist" style="display:none;"> <span id="ao_load"></span></td>
                <td  class="span"id="aolistall" >
                    <select  name=aoId id=aoId data-placeholder="deliveries" class="span8">
                        {html_options  options=$delivery_array  selected=$smarty.get.aoId}
                    </select>
                </td>
                <td class="span1"><button class="btn btn-info pull-left" id="search" name="search" type="submit" value="search" onclick="return validateSearch();" >Search</button>&nbsp;&nbsp;</td>
            </tr>
        </table>
      </form>-->
     </div>
     <div class="tabbable">
        <!-- <h3 class="heading">Nouvelles missions libert&eacute; <a class="label label-inverse pull-right"  id="return">retour</a></h3>-->
         <ul class="nav nav-tabs">
             <li {if $smarty.get.tab == 'newaos' || $smarty.server.REQUEST_URI == '/processao/liberte-newaos?submenuId=ML2-SL1'} class="active" {/if}><a href="/processao/liberte-newaos?tab=newaos&submenuId=ML2-SL1" class="lable-danger"><strong>New missions</strong></a></li>
             <li {if $smarty.get.tab == 'ongoingaos'} class="active" {/if}><a href="/processao/liberte-ongoingaos?tab=ongoingaos&submenuId=ML2-SL1"  class="lable-info"><strong>Ongoing Missions</strong></a></li>
             <li {if $smarty.get.tab == 'validaos'} class="active" {/if}><a href="/processao/liberte-validaos?tab=validaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions finished</strong></a></li>
             <li {if $smarty.get.tab == 'refusedaos'} class="active" {/if}><a href="/processao/liberte-refusedaos?tab=refusedaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions refused</strong></a></li>
             <li {if $smarty.get.tab == 'cancelledaos'} class="active" {/if}><a href="/processao/liberte-cancelledaos?tab=cancelledaos&submenuId=ML2-SL1"  class="lable-info"><strong>Missions cancelled</strong></a></li>
         </ul>
          <div id="newmissiontab" class="tab-pane tab-content" >
             <table id="newmissionsgrid" class="table table-bordered table-striped table_vam"  style="overflow-x: scroll;">
                <thead>
                <tr>
                    <th>SL.NO</th>
                    <th>Title</th>
                    <th>Client</th>
                    <th>Created</th>
                    <th>Type of content</th>
                    <th>Language</th>
                    <th>Writing/ Translating</th>
                    <th>History</th>
                    <th>Status</th>
                    <th>Nb of Participations</th>
                    <th>Invoice</th>
                    <th>Action</th>
                    <th>Trunover</th>
                </tr>
                </thead>
                <tbody>
                {foreach from=$paginator key=newaos_key item=newaos_item name=newaos_loop}
                <tr>
                    <td>{$smarty.foreach.newaos_loop.index+1}</td>
                    <td><a data-target="#artprofile" role="button" href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$newaos_item.id}">{$newaos_item.title|stripslashes|wordwrap:20:"\n":true|upper}</a></td>
                    <td><a href="/user/client-edit?submenuId=ML10-SL2&tab=viewclient&userId={$newaos_item.user_id}" class="hint--bottom hint--info" data-hint="since : {$newaos_item.doj|date_format:'%d/%m/%Y'}">{if $newaos_item.company_name neq ''}{$newaos_item.company_name|upper}{else}{$newaos_item.email}{/if}</a></td>
                    <td>{$newaos_item.created_at|date_format:"%d/%m/%Y"}</td>
                    <td>{$newaos_item.deltype}</td>
                    <td>{$newaos_item.language}</td>
                    <td>{if $newaos_item.content_type == 'writing'}R&eacute;daction{else}Traduction{/if}</td>
                    <td><a href="/ongoing/ao-history?ao_id={$newaos_item.id}"  data-toggle="modal" data-hint="history" data-target="#ao_history" ><i class="splashy-information"></i></a></td>
                    <td>{if $newaos_item.status_bo == ''}NEW{else}{$newaos_item.status_bo}{/if}</td>
                    <td>{$newaos_item.contributors}</td>
                    <td>{if $newaos_item.paid_status == 'notpaid'}Non pay&eacute;{else}pay&eacute;{/if}</td>
                    <td><!--<a data-toggle="modal" data-target="#publishao" id="publishaopop" href="/processao/showpraoinfo?aoid={$newaos_item.id}&function=publish"><i class="splashy-check"></i></a>-->
                        <a data-toggle="modal" data-target="#editao" id="editaopop" href="/processao/showpraoinfo?aoid={$newaos_item.id}&function=edit"><i class="splashy-pencil"></i></a>
                        <a href="/processao/mission-split?submenuId=ML2-SL1&aoid={$newaos_item.id}" data-hint="split mission" class="hint--left hint--danger"><i class="splashy-diamonds_4"></i></a>
                        <a href="/BO/downloadpremiumquote.php?id={$newaos_item.quoteid}" class="hint--left hint--danger" data-hint="Download XSL"><i class="splashy-download"></i></a>
                    </td>
                    <td>{$newaos_item.cost|string_format:"%.2f"}<b> &euro;</b></td>
                </tr>
                {/foreach}
                </tbody>
             </table>
          </div>
     </div>
 </div>
</div>

<!--///for the edit ao detials popup///-->
<div class="modal container hide fade" id="editao">
    <div class="modal-header">
        <button class="close" onclick="closePopup('editao');">&times;</button>
        <h3>Edit AO Details</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--///for the publish ao  popup///-->
<div class="modal2 hide fade" style="overflow: hidden" id="publishao">
    <div class="modal-header">
        <button class="close" onclick="closePopup('publishao');">&times;</button>
        <h3>Publish AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

<!--History of AO-->
<div class="modal container hide fade" id="ao_history">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Historique des actions men&eacute;es sur l'AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--Comments of AO-->
<div class="modal hide fade" id="refusal_reasons">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Message to client</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>



